"""Source-grounded one-page journalism companions to N00–N36.

Scenes are editorial reconstructions of what the cited service entails, not
attributed eyewitness reports. Every quotation is from the linked source.
"""


def a(number, title, kicker, deck, region, source_label, source_url, story=None,
      quote_note="Cita de la fuente indicada; fotografía conceptual.", pilot_pdf=None,
      extra_sources=None):
    item = dict(id=f"N{number:02d}", title=title, kicker=kicker, deck=deck,
                region=region, source_label=source_label, source_url=source_url,
                story=story or [], quote_note=quote_note,
                extra_sources=extra_sources or [])
    if pilot_pdf:
        item["pilot_pdf"] = pilot_pdf
    return item


ARTICLES = [
    a(0, "Diez mil turnos por día. ¿Por dónde empezar?", "El contrato del viaje",
      "Una línea de salud porteña muestra por qué antes de elegir una herramienta conviene seguir el recorrido de una persona.",
      "Argentina", "Buenos Aires, 2025",
      "https://buenosaires.gob.ar/gcaba_historico/noticias/la-ciudad-refuerza-la-linea-147-que-da-mas-de-10-mil-turnos-por-dia-en",
      [
          "Alguien necesita un turno médico. Puede escribirle a un bot, llamar al 147 o acercarse a un centro de salud. Desde afuera parecen tres puertas a la misma respuesta. En la práctica, cada puerta tiene personas, horarios, reglas y una forma diferente de seguir lo que pasa después.",
          "En noviembre de 2025, la Ciudad de Buenos Aires informó que la línea 147 gestionaba unos diez mil turnos de salud por día. Sumó un centro de atención con más de trescientos operadores, supervisores y coordinadores; no presentó ese refuerzo como una nueva pantalla sino también como capacitación en derivaciones y protocolos.",
          "«Vamos a seguir impulsando un sistema de salud accesible, de calidad y en constante mejora», dijo Jorge Macri al presentar el refuerzo.",
          "Esa promesa no se mide contando llamadas atendidas. La persona necesitaba llegar a una consulta útil. Para comprender el servicio hay que preguntar qué ocurre si no hay turnos, si la derivación es incorrecta o si alguien no puede usar el canal digital. El trabajo continúa después del primer contacto.",
          "N00 propone precisamente ese contrato de lectura. No ofrece treinta y seis recetas: plantea un viaje en el que cada paso obliga a revisar decisiones anteriores. El mismo caso reaparece con nuevas preguntas porque un problema real no se agota en una sola materia ni en una sola mirada.",
          "Empezar por el resultado que importa cambia la conversación. Antes de celebrar el volumen de turnos, preguntémonos cuántas personas llegaron a la atención que necesitaban y qué aprendió el sistema de las que no llegaron. Ahí empieza METSI."
      ]),
    a(1, "La canilla empezó a decidir sola. La pregunta venía de antes.", "Antes de automatizar",
      "Un invernadero de Chubut sirve para discutir qué hace una metodología cuando todavía no conocemos bien el problema.",
      "Argentina", "INTA Esquel, 2025",
      "https://www.argentina.gob.ar/noticias/presentan-un-equipo-para-automatizar-el-sistema-de-riego-con-ia-para-invernaderos",
      [
          "En un invernadero, abrir la canilla parece una decisión simple. Si el suelo está seco, se riega. Pero el agua puede escasear, la temperatura cambia durante el día y una planta puede recibir demasiado aunque otra necesite más. Automatizar el gesto no resuelve, por sí solo, la pregunta agronómica.",
          "Un equipo del INTA Esquel acompañó en 2025 el desarrollo de un dispositivo que combina sensores y un sistema de IA para regar cultivos protegidos. El objetivo declarado era usar mejor el agua y mejorar las condiciones de producción. La noticia describe una propuesta; no demuestra todavía el resultado de cada cosecha.",
          "«La Inteligencia Artificial analiza los datos y determina con precisión cuándo y cómo debe realizarse el riego», explicó el extensionista Eduardo Miserendino.",
          "La frase entusiasma. También invita a hacer mejores preguntas: ¿qué se mide exactamente?, ¿qué pasa si falla un sensor?, ¿quién corrige una recomendación que no coincide con la observación del productor? Antes de pedir más funciones conviene acordar qué resultado sería una mejora y cuál sería un daño.",
          "N01 llama metodología a esa disciplina de formular el problema, elegir un primer paso y dejar visible lo que todavía no sabemos. No es una secuencia que garantice éxito. Es una forma de no convertir la primera solución disponible en la definición del problema.",
          "La prueba valiosa no es que la válvula se abra sola. Es que, al final, alguien pueda explicar por qué se abrió, cuánto agua se usó y qué haría distinto mañana."
      ]),
    a(2, "Avisaron que el sistema fallaba. Los acusaron a ellos.", "Cuando el dato desplaza a la persona",
      "El caso Horizon muestra qué pasa cuando una organización confunde la cifra de una pantalla con la verdad de lo ocurrido.",
      "Global", "Investigación Horizon, 2025",
      "https://www.postofficehorizoninquiry.org.uk/about-inquiry",
      pilot_pdf="output/pdf/METSI-cronicas-N02-piloto.pdf"),
    a(3, "El pasaje cambió de tarjeta. El descuento no siempre.", "Efectos que vuelven",
      "La llegada de nuevos medios de pago al transporte de Neuquén revela que una mejora local puede dejar otro problema a la vista.",
      "Argentina", "Neuquén Capital, 2025",
      "https://www.neuquencapital.gov.ar/prensa/en-neuquen-el-cole-podra-abonarse-con-nuevos-medios-de-pago/",
      [
          "Un pasajero apoya el celular en el colectivo y viaja. La escena parece el final de una mejora tecnológica. Sin embargo, la pregunta del día siguiente puede ser otra: ¿la persona pagó lo mismo? ¿Conservó el descuento al cambiar de medio de pago?",
          "En abril de 2025, Neuquén anunció que COLE aceptaría, además de SUBE física y digital, tarjetas bancarias y dispositivos con NFC. Para muchas personas sería más cómodo. La propia comunicación oficial, sin embargo, aclaró una diferencia importante: los beneficios nacionales y locales seguían disponibles solo con SUBE.",
          "«Los descuentos por beneficios nacionales y locales [...] continúan estando disponibles solo a través de la tarjeta SUBE», advirtió el funcionario municipal Espinosa.",
          "La incorporación de un medio de pago no es buena o mala por definición. Depende de quién viaja y de qué resultado se considera importante. Una persona sin saldo en la SUBE puede ganar una alternativa; otra puede perder un beneficio si interpreta que todas las opciones son equivalentes.",
          "N03 llama a mirar estos efectos de segundo orden. Una intervención cambia relaciones: entre el lector, la tarjeta, la cuenta bancaria, la tarifa y la información que recibe el usuario. Si uno dibuja solo el validador, la consecuencia desaparece del mapa aunque siga apareciendo en el bolsillo.",
          "La próxima vez que se anuncie una opción más, conviene preguntar quién gana una salida, quién recibe una sorpresa y cómo se enterará a tiempo. Una mejora que no prevé sus rebotes todavía está a medio diseñar."
      ]),
    a(4, "El índice subió. La pregunta siguió abierta.", "Dato, supuesto y evidencia",
      "Un tablero de transparencia puede mostrar progreso y, al mismo tiempo, no responder si la gente consiguió la información que necesitaba.",
      "Argentina", "AAIP, 2026",
      "https://www.argentina.gob.ar/noticias/la-aaip-participo-de-las-primeras-jornadas-iberoamericanas-de-academia-y-gobierno-abierto",
      [
          "Un número llega a una presentación: 61,9 sobre 100. Es el promedio de un índice de transparencia. Puede ser una señal útil. Pero si una vecina pidió un dato para entender una obra y no obtuvo respuesta a tiempo, ese promedio no cuenta toda la historia.",
          "En mayo de 2026, la Agencia de Acceso a la Información Pública informó una mejora de 37,5% en su índice respecto del primer semestre de 2024. También registró más de 10.700 solicitudes durante 2025 y 660 reclamos. Son tres medidas distintas: publicación, demanda y desacuerdo. Ninguna debería reemplazar a las otras.",
          "Beatriz Anchorena planteó en otra asamblea de 2026 que transparencia y protección de datos son «pilares estratégicos de gestión». No son solo indicadores para exhibir.",
          "N04 pide separar observaciones, relatos, hipótesis y decisiones. La cifra publicada es un dato; que la ciudadanía ahora comprende mejor es una hipótesis. Para sostenerla habría que mirar tiempos de respuesta, utilidad de lo entregado y experiencias de quienes reclamaron.",
          "Tampoco se trata de desconfiar de todo número. Se trata de preguntarle qué puede demostrar. Un índice puede orientar una investigación o comparar cambios bajo una misma regla; no puede, sin más, certificar el resultado que cada persona recibió.",
          "El buen uso de la evidencia no apaga las dudas: las ordena. A veces el dato más valioso no es el que confirma la mejora, sino el reclamo que muestra dónde todavía no llega."
      ], quote_note="La cita procede de una segunda fuente oficial de 2026; fotografía conceptual.",
      extra_sources=[("Cita AAIP", "https://www.argentina.gob.ar/node/504558")]),
    a(5, "El formulario llegó. ¿Quién recibió el problema?", "Las voces que faltan",
      "La ventanilla educativa porteña permite ver por qué usuarios, equipos de soporte y responsables de decisión no cuentan la misma historia.",
      "Argentina", "Buenos Aires Educación, 2025",
      "https://buenosaires.gob.ar/gcaba_historico/noticias/la-ventanilla-unica-de-educacion-sigue-creciendo",
      [
          "Una directora necesita resolver un alta de usuario. Antes escribía a una mesa de ayuda; ahora encuentra una ventanilla común. El cambio parece administrativo, pero la espera puede afectar a una docente que necesita entrar a un sistema para trabajar al día siguiente.",
          "En septiembre de 2025, el Ministerio de Educación porteño informó que su Ventanilla Única reunía diez mesas de ayuda y había gestionado más de 21.000 consultas. Incluía títulos, limpieza, conectividad y altas de usuarios. Esa variedad es la pista: una misma puerta no convierte en igual el trabajo que hay detrás.",
          "La comunicación oficial dice que la plataforma busca «unificar las fuentes de información y habilitar decisiones basadas en evidencia certera». Es una aspiración, no una prueba de que cada consulta esté resuelta.",
          "N05 obliga a escuchar al menos tres posiciones: quien solicita, quien ejecuta y quien recibe las consecuencias. Para la directora importa saber a quién acudir; para soporte, identificar la causa; para la docente, poder dar clase. El indicador de tickets cerrados puede dejar fuera esa última mirada.",
          "Un mapa de actores no es una lista ceremonial. Sirve para encontrar desacuerdos que cambian el problema. Si una consulta rebota entre áreas, quizá no falta una función en el formulario: falta un acuerdo sobre quién tiene autoridad para resolverla.",
          "La pregunta editorial es sencilla: cuando el sistema dice «resuelto», ¿quién tendría que poder confirmarlo? Si la respuesta es solo el área que cerró el ticket, todavía falta una voz."
      ], quote_note="Frase institucional del comunicado; no atribuida a una persona."),
    a(6, "Podía detectar doscientos virus. Todavía había que decidir para qué.", "Investigar antes de apostar",
      "Un acuerdo del Malbrán muestra que incorporar una capacidad nueva no equivale a demostrar dónde cambia una decisión sanitaria.",
      "Argentina", "ANLIS Malbrán, 2026",
      "https://www.argentina.gob.ar/noticias/malbran-firma-un-acuerdo-con-illumina-para-fortalecer-la-vigilancia-genomica-en-argentina",
      [
          "Cuando aparece una tecnología capaz de detectar cerca de doscientos virus, el primer impulso es usarla para todo. Pero un laboratorio no decide en el vacío. Hay muestras, tiempos, equipos, brotes y una pregunta clínica o epidemiológica que vuelve útil un resultado.",
          "En agosto de 2026, ANLIS Malbrán anunció un convenio con Illumina. La primera iniciativa prevista es validar un panel de vigilancia viral. Prevista y validada no son la misma cosa: el anuncio no prueba que el método ya haya cambiado la respuesta frente a un brote.",
          "«Generar evidencia científica que fortalezca la toma de decisiones», dijo Claudia Perandones, directora del Malbrán, al explicar el objetivo de la cooperación.",
          "N06 pregunta qué hace falta averiguar antes de comprometerse con una solución. Aquí convendría elegir algunos escenarios: ¿qué virus se detecta tarde hoy?, ¿cuánto demora el circuito completo?, ¿cuándo una detección temprana modifica una acción pública? Sin esa cadena, la capacidad técnica puede ser impresionante y, aun así, difícil de evaluar.",
          "La investigación no retrasa necesariamente la intervención. Puede hacerla más pequeña y más precisa: validar muestras, comparar resultados con métodos existentes, medir el tiempo hasta una decisión y registrar qué casos no mejoraron.",
          "La potencia de un panel no está en el número de patógenos de su folleto. Está en las decisiones que permite tomar mejor y en los errores que ayuda a evitar."
      ]),
    a(7, "Preguntaron si gustaba la app. Nadie preguntó si resolvía el trámite.", "Entrevistar sin inducir",
      "La asistencia digital del Estado abre una pregunta clásica: una entrevista puede confirmar una solución sin entender la dificultad real.",
      "Argentina", "Mi Argentina / MIA, 2025",
      "https://www.argentina.gob.ar/noticias/se-presento-mia-el-primer-agente-de-inteligencia-artificial-del-estado-nacional",
      [
          "Imaginemos la prueba de una nueva asistente digital. «¿Te resulta fácil hablar con ella?». La respuesta puede ser sí. La persona, sin embargo, quizá sigue sin saber si terminó el trámite, si falta un documento o a quién recurrir cuando la respuesta es incorrecta.",
          "En 2025 el Gobierno presentó MIA para acompañar gestiones en Mi Argentina, una aplicación con 26 millones de usuarios. La comunicación prometía ahorrar tiempo a ciudadanos y equipos de soporte. Es una hipótesis razonable; medir satisfacción con el chat no alcanza para confirmarla.",
          "Darío Genua sostuvo que la IA debía avanzar hacia una administración «más ágil, innovadora y centrada en las necesidades de la ciudadanía». La última parte de la frase exige escuchar sin sugerir la respuesta.",
          "N07 enseña a preguntar por episodios concretos. «Contame la última vez que intentaste hacer este trámite», abre más información que «¿te gustó la app?». Después se puede reconstruir dónde comenzó, qué esperaba, qué hizo cuando se confundió y cómo supo si había terminado.",
          "También importa entrevistar a quien atiende las excepciones. Si el canal digital deriva mal, la carga no desaparece: se traslada a otro equipo. Una entrevista que solo mira la pantalla omite el costo del error.",
          "La pregunta correcta no es la más amable para el producto. Es la que nos deja cambiar de opinión antes de que una solución bonita se vuelva un problema obligatorio."
      ], quote_note="La primera escena es hipotética; cita textual del anuncio de MIA."),
    a(8, "El robot ordeñó. El trabajo siguió en otra parte.", "Trabajo invisible",
      "En un tambo del INTA, automatizar una tarea vuelve más importante mirar todo lo que ocurre alrededor.",
      "Argentina", "INTA Rafaela, 2025",
      "https://www.argentina.gob.ar/noticias/en-la-argentina-hay-mas-de-400-tambos-robotizados-en-funcionamiento",
      [
          "En una demostración, el robot hace el trabajo más visible: identifica a una vaca, la guía y registra el ordeñe. La cámara se queda con la máquina. Fuera de cuadro siguen las personas que observan la salud del rodeo, interpretan datos, limpian, mantienen equipos y deciden qué hacer cuando algo no encaja.",
          "El INTA Rafaela cumplió diez años de trabajo con ordeñe robotizado y, en 2025, informó que había más de cuatrocientos robots funcionando en el país. También publica indicadores mensuales sobre producción, calidad, sanidad, dieta y ambiente. El éxito no se resume en un contador de animales atendidos.",
          "«Las vacas aprenden rápidamente el recorrido porque asocian el ordeñe con el confort y el alimento», explicó el especialista Miguel Taverna.",
          "N08 invita a observar el trabajo real y los arreglos que no suelen figurar en un manual. ¿Quién detecta una vaca que no entra? ¿Cómo se reconoce un dato extraño? ¿Qué ocurre cuando se corta la conexión? Esas preguntas no desacreditan al robot: permiten diseñar alrededor de la vida que el robot no reemplaza.",
          "Observar no es mirar una visita guiada. Es seguir un episodio completo, incluir las excepciones, anotar quién ayuda a quién y contrastar lo visto con los registros. Lo informal puede ser el soporte invisible del proceso oficial.",
          "La innovación más interesante quizá no sea que una máquina trabaje sola. Es que el equipo pueda ver, discutir y mejorar el trabajo que antes quedaba oculto detrás del gesto repetido."
      ]),
    a(9, "La credencial funciona sin internet. Ese detalle no es menor.", "El servicio desde quien lo usa",
      "Mi PAMI muestra cómo una decisión aparentemente pequeña puede sostener un trámite cuando la conexión falla.",
      "Argentina", "PAMI, 2025",
      "https://www.argentina.gob.ar/noticias/esteban-leguizamo-la-aplicacion-permite-modernizar-y-agilizar-el-acceso-los-servicios-de",
      [
          "Una persona llega a una consulta y su teléfono no tiene señal. Si la credencial solo existe detrás de una conexión, la aplicación pudo funcionar perfectamente en la oficina donde se diseñó y fallar justo en la puerta donde se la necesita.",
          "Al presentar Mi PAMI en 2025, la obra social explicó que la app reúne información del médico de cabecera, recetas, órdenes, turnos y trámites. Su director, Esteban Leguízamo, subrayó una característica poco vistosa: la credencial digital estaría disponible incluso sin conexión.",
          "«Van a contar siempre, incluso sin conexión, con la credencial digital», dijo Leguízamo. Esa frase habla menos de tecnología que de continuidad de atención.",
          "N09 propone seguir el recorrido de quien usa el servicio, no el menú de funciones. ¿Puede encontrar la orden? ¿Sabe si está vigente? ¿Puede pedir ayuda? ¿Qué pasa si otra persona hace el trámite por ella o si necesita una alternativa presencial? Una interfaz clara no compensa un recorrido interrumpido.",
          "También hay que distinguir disponibilidad de uso efectivo. El comunicado anuncia capacidades; no demuestra que todos los afiliados puedan completar sus gestiones sin asistencia. Para saberlo habría que observar episodios reales, incluidos los difíciles.",
          "A veces la decisión de diseño que más valor agrega no gana una presentación. Está en prever el instante en que el mundo deja de parecerse al laboratorio: sin señal, con apuro y con alguien esperando del otro lado."
      ]),
    a(10, "El reclamo cerró. La vereda siguió rota.", "Definir el problema",
      "Una plataforma de reclamos urbanos permite ver por qué cerrar un expediente no equivale a mejorar la experiencia de un vecino.",
      "Argentina", "BA Colaborativa",
      "https://buenosaires.gob.ar/gcaba_historico/innovacionytransformaciondigital/ba-colaborativa",
      [
          "Una persona informa una vereda rota. Recibe un número y puede ver su solicitud en un mapa. Son avances reales: hay registro y seguimiento. Pero el trámite puede pasar a «cerrado» cuando el área terminó una acción administrativa, no necesariamente cuando la vereda volvió a ser segura.",
          "BA Colaborativa ofrece más de trescientas prestaciones, desde alumbrado y limpieza hasta reparación de calles y veredas. La plataforma promete vincular directamente a quien solicita con el área responsable. Precisamente por su amplitud, la palabra «resuelto» necesita una definición distinta según el servicio.",
          "La Ciudad describe la herramienta como una forma de «simplificar procesos y reducir tiempos de resolución». Es una promesa institucional que conviene poner a prueba en cada tipo de reclamo.",
          "N10 pide construir el problema antes de proponer la mejora. Para la vereda, el resultado no es un ticket actualizado: es un paso transitable. Habría que seguir una muestra de reclamos desde el aviso hasta la reparación, distinguir esperas de trabajo, preguntar al vecino y revisar casos reabiertos.",
          "La formulación importa porque cambia lo que se optimiza. Si el objetivo es disminuir tickets pendientes, cerrar rápido puede parecer una victoria. Si el objetivo es reducir riesgos y molestias, la misma acción puede resultar insuficiente.",
          "La pregunta que cierra esta lectura incomoda a cualquier tablero: ¿qué tendría que pasar en la calle para que podamos decir, sin comillas, que el problema se resolvió?"
      ], quote_note="Frase institucional de la descripción oficial de BA Colaborativa."),
    a(11, "El PBI cambió después de publicado. No era un error de tipeo.", "Leer datos sin obedecerlos",
      "Una revisión oficial británica recuerda que una cifra temprana y una cifra completa no son el mismo producto.",
      "Global", "Oficina de Estadísticas del Reino Unido, 2025",
      "https://www.ons.gov.uk/economy/nationalaccounts/uksectoraccounts/articles/gdprevisionsinbluebook2020/2025",
      [
          "El PBI se publica y se vuelve titular. Meses después cambia. La primera reacción suele ser acusar a alguien de haber calculado mal. A veces ocurre algo más simple: cuando se difundió la primera estimación todavía faltaba información.",
          "La Oficina de Estadísticas del Reino Unido explicó en octubre de 2025 cómo revisa sus cifras. El proceso puede durar hasta tres años: entran encuestas, registros administrativos y correcciones de método. Para los trimestres de 2020 a mediados de 2025, la revisión absoluta media fue de 0,66 puntos porcentuales; la pandemia hizo ese período especialmente inestable.",
          "La oficina lo resume así: «Hay un equilibrio entre la oportunidad y la precisión de las estimaciones». Publicar pronto permite actuar; esperar permite saber más. Ambas cifras tienen sentido si sabemos qué versión estamos usando.",
          "N11 propone tratar los datos como evidencia con procedencia. Antes de repetir una cifra, hay que conocer su unidad, período, fuente, fecha de corte, versión y margen de incertidumbre. Si un tablero mezcla una primera estimación con un valor revisado sin avisarlo, fabrica una comparación engañosa.",
          "El indicador tampoco responde cualquier pregunta. Una economía puede crecer mientras un grupo pierde ingresos. Por eso conviene separar medición de interpretación y sumar otra evidencia cuando la decisión se juega en una región, sector o población concreta.",
          "Corregir un número no lo vuelve inútil. Lo peligroso es presentarlo como definitivo cuando todavía es una primera lectura de lo que pasó."
      ], quote_note="Cita traducida del inglés; fotografía conceptual."),
    a(12, "La receta apareció. El medicamento todavía no.", "Tres estados distintos",
      "Mi Argentina permite consultar recetas electrónicas, pero prescribir, dispensar y tratar siguen siendo hechos diferentes.",
      "Argentina", "Ministerio de Salud, 2026",
      "https://www.argentina.gob.ar/node/501404",
      [
          "Una paciente abre Mi Argentina y ve su receta. Es un paso útil: la información antes dispersa ahora está a mano. Pero la pantalla no prueba que la farmacia tenga el medicamento ni que la persona haya podido iniciar el tratamiento.",
          "Desde mayo de 2026, la aplicación permite consultar prescripciones electrónicas emitidas en los sesenta días anteriores por plataformas registradas. Una clave única identifica cada receta y evita duplicar registros. Para verlas, la persona debe adherir al servicio y autorizar el intercambio de datos.",
          "En un encuentro sobre salud digital, la representante de OPS en Argentina, Eva Jané Llopis, resumió la escala del desafío: «la transformación digital requiere rectoría pública, visión a largo plazo, cooperación entre actores».",
          "N12 insiste en separar intención, autorización, ocurrencia y estado posterior. «Receta emitida» no es «medicamento entregado»; «medicamento entregado» no es «tratamiento cumplido». Cada transición tiene actor, condición y evidencia. Si todos usan la palabra «hecho» para estados diferentes, el sistema produce certezas falsas.",
          "El diseño también debe prever excepciones: receta vencida, plataforma desconectada, farmacia sin stock, paciente que necesita asistencia. Esas situaciones no son defectos anecdóticos; ayudan a definir el modelo de estados que la operación necesita.",
          "La digitalización vale más cuando permite responder una pregunta concreta: ¿qué ocurrió, quién puede actuar ahora y cómo sabremos si la persona obtuvo lo que necesitaba?"
      ], quote_note="Cita de OPS en segunda fuente oficial de 2026; fotografía conceptual.",
      extra_sources=[("Cita OPS", "https://www.argentina.gob.ar/noticias/salud-impulsa-la-interoperabilidad-para-consolidar-un-sistema-de-salud-digital-integrado")]),
    a(13, "Pagó dos veces. Cada sistema dijo que la otra vez no contaba.", "Lo que pasa entre eventos",
      "El boleto híbrido brasileño muestra por qué una operación correcta en cada canal puede producir un resultado incorrecto en conjunto.",
      "América Latina", "Banco Central de Brasil, 2026",
      "https://www.bcb.gov.br/detalhenoticia/21066/noticia",
      [
          "Un mismo cobro ofrece código de barras y QR. Una persona paga por un canal; otra, con acceso a la misma factura, paga por el otro antes de que la confirmación se propague. Cada canal podría registrar una operación válida. La deuda, sin embargo, no debería cobrarse dos veces.",
          "Brasil debatió en 2026 mejoras para Pix y los instrumentos de cobro que conviven con él. El riesgo de duplicación no es una anécdota de interfaz: surge cuando dos mensajes llegan en momentos diferentes y cada sistema cree tener el estado más reciente.",
          "«Después, las sugerencias serán evaluadas y, si corresponde, reglamentadas por el Banco Central», dijo Breno Lobo al explicar que las reglas aún estaban en discusión.",
          "N13 pone el foco en demoras, reintentos y acciones simultáneas. Un evento necesita identidad propia y una regla para saber si ya fue procesado. También hacen falta estados compartidos y una salida cuando el orden de llegada no es el esperado. Sin eso, «intentar de nuevo» puede convertirse en «cobrar de nuevo».",
          "El ejemplo es hipotético; no informa un incidente concreto en Pix. Sirve para diseñar una prueba: ejecutar pagos cercanos en ambos canales, demorar confirmaciones y verificar que el saldo y los comprobantes queden consistentes.",
          "El problema de fondo no es que una red sea lenta. Es confiar en que el mundo entregará los mensajes una sola vez, en el orden conveniente y sin que nadie actúe mientras esperamos."
      ], quote_note="Escena de prueba hipotética; cita traducida del portugués."),
    a(14, "Sacó turno. El trabajo recién empezaba.", "Seguir el flujo completo",
      "Una nueva versión de la agenda pública uruguaya recuerda que reservar un horario no equivale a recibir el servicio.",
      "América Latina", "Agesic Uruguay, 2026",
      "https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/comunicacion/noticias/sistema-agenda-electronica-incorpora-mejoras-seguridad-digital",
      [
          "Un turno confirmado da alivio. Pero puede faltar un documento, cambiar la disponibilidad o aparecer una barrera de acceso el día de la visita. Desde la perspectiva de la plataforma, la reserva está terminada. Desde la perspectiva de la persona, la tarea recién comenzó.",
          "Uruguay publicó en marzo de 2026 una nueva versión de su Sistema de Agenda Electrónica. Reforzó la autenticación de quienes administran agendas, mejoró accesibilidad y usabilidad, y anunció que dejaría de dar soporte a versiones anteriores. Son cambios de seguridad y operación, además de cambios de pantalla.",
          "La agencia informó que la actualización busca «una gestión más eficiente de las agendas para los trámites y servicios». El criterio decisivo aparece cuando seguimos una gestión hasta su resultado.",
          "N14 propone observar una unidad de trabajo de punta a punta: desde la necesidad que abre la búsqueda de turno hasta la atención, la derivación o el rechazo. En ese trayecto importan las esperas, los traspasos, las vueltas atrás y los casos que no caben en el camino ideal.",
          "También conviene separar flujo de ciudadano y flujo de cambio tecnológico. Una nueva versión puede desplegarse sin incidentes y, sin embargo, dejar a un organismo sin una forma clara de manejar excepciones. El mapa tiene que mostrar ambos recorridos y quién responde cuando se cruzan.",
          "La agenda no termina al asignar una hora. Termina —para esa persona— cuando puede hacer lo que vino a hacer."
      ], quote_note="Frase institucional del comunicado de Agesic."),
    a(15, "El sensor dijo «bien». La bolsa de granos decía otra cosa.", "Un modelo para cada pregunta",
      "La vigilancia de granos almacenados en Argentina muestra que ninguna vista describe por completo un sistema.",
      "Argentina", "INTA Balcarce, 2025",
      "https://www.argentina.gob.ar/noticias/monitoreo-inteligente-para-preservar-la-calidad-de-los-granos",
      [
          "Desde afuera, una bolsa de granos parece quieta. Adentro cambian la humedad, la temperatura y el riesgo de pérdida. Una cifra remota puede avisar que algo ocurre; para decidir qué hacer, alguien necesita saber dónde, desde cuándo y con qué consecuencias.",
          "En 2025, especialistas del INTA describieron distintas herramientas para vigilar la condición de granos en silobolsa. No era una carrera por juntar sensores: buscaban información útil para reducir pérdidas y decidir a tiempo sobre mercadería que no se ve.",
          "«Se han desarrollado herramientas cada vez más prácticas para que el usuario tenga mejor información sobre lo que pasa en la bolsa», explicó Cardoso en el encuentro sectorial.",
          "N15 trata de elegir representaciones según la pregunta. Una curva temporal permite ver cuándo empezó una anomalía. Un mapa de ubicación muestra dónde actuar. Una tabla compara lotes. Un relato de la persona que inspeccionó puede explicar por qué un sensor marcó un dato extraño. Ninguna vista reemplaza a las demás.",
          "El error sería pedir un gran diagrama que explique todo. Cada representación recorta y, por eso, también oculta. La prueba profesional consiste en declarar qué decisión ayuda a tomar y qué información deja fuera.",
          "El mejor modelo no es el más impresionante. Es el que permite a alguien detectar a tiempo una pérdida, discutirla con evidencia y actuar sin fingir que una cifra conoce toda la cosecha."
      ]),
    a(16, "Dos sistemas dijeron «paciente». No hablaban de lo mismo.", "Cuando los modelos chocan",
      "Las pruebas federales de intercambio clínico sirven para pensar dónde se descubren las contradicciones: antes o después de atender.",
      "Argentina", "Salud Digital Argentina, 2026",
      "https://www.argentina.gob.ar/noticias/salud-impulsa-la-interoperabilidad-para-consolidar-un-sistema-de-salud-digital-integrado",
      [
          "Una institución registra una consulta. Otra recibe un dato con el mismo nombre y lo interpreta de otra manera. La conexión técnica funcionó: el mensaje llegó. La continuidad de atención puede fallar igual si los campos no significan lo mismo.",
          "En junio de 2026, el Ministerio de Salud organizó una «Conectatón» para probar intercambio de información clínica en tiempo real entre equipos y jurisdicciones. El encuentro también buscó validar estándares comunes. Es una señal importante: conectar sistemas exige acordar significados, no solo direcciones de red.",
          "Eva Jané Llopis, de la OPS, sostuvo que la transformación requiere «cooperación entre actores y capacidad de articulación federal». La frase nombra un trabajo que ningún manual de integración puede hacer solo.",
          "N16 compara representaciones: registros, procesos, estados y responsabilidades. Si un modelo llama «atendido» a quien consiguió turno y otro a quien completó una consulta, la contradicción tiene que aparecer en una mesa de revisión antes de convertirse en un error operativo.",
          "La salida no es imponer una palabra y dar el tema por cerrado. Es definir equivalencias, excepciones y dueño de cada dato; probar ejemplos reales; registrar cambios; y revisar qué consumidores se romperían si una definición evoluciona.",
          "Una integración exitosa no es un cable conectado. Es que dos equipos puedan reconstruir el mismo episodio y tomar una decisión compatible con él."
      ]),
    a(17, "El sistema de turnos cambió. Los turnos viejos no desaparecieron.", "Elegir cómo cambiar",
      "La migración de la IGJ ofrece una lección poco vistosa: una transición buena conserva obligaciones mientras crea un camino nuevo.",
      "Argentina", "IGJ, 2026",
      "https://www.argentina.gob.ar/noticias/igj-implementa-un-nuevo-sistema-de-turnos",
      [
          "Una persona ya tiene turno. La institución anuncia una plataforma nueva. En ese momento, la pregunta más importante no es cómo se ve la pantalla: es si el compromiso anterior sigue valiendo y quién puede demostrarlo cuando llegue a la oficina.",
          "En mayo de 2026, la Inspección General de Justicia migró al Sistema Nacional de Turnos. El comunicado aclaró que se respetarían los turnos otorgados con el sistema previo. También mantuvo una franja temprana de atención urgente sin reserva. Dos decisiones de transición que pueden ser más importantes que el cambio de software.",
          "La IGJ presentó el objetivo como una atención «más ágil, ordenada y eficiente». Para comprobarlo habría que observar no solo reservas nuevas, sino cancelaciones, reprogramaciones, esperas y casos urgentes.",
          "N17 distingue maneras de hacer un cambio: planificar lo irreversible, probar donde hay incertidumbre y entregar por cortes cuando conviene aprender. Una migración de turnos puede requerir inventario de compromisos existentes, ensayo de datos, doble lectura durante un tiempo y criterios claros para volver atrás.",
          "No todo debe hacerse en una sola noche ni todo admite un piloto indefinido. La estrategia depende del riesgo, del costo de corregir y de quién sufriría una falla. Lo importante es que la transición tenga una política explícita, no solo una fecha de lanzamiento.",
          "El mejor estreno es aquel en que nadie tiene que discutir en la ventanilla si la promesa de ayer todavía existe."
      ], quote_note="Frase institucional del comunicado de la IGJ."),
    a(18, "Cambió la línea telefónica. La alarma no podía dejar de llamar.", "Cambiar sin borrar",
      "La migración digital británica muestra que lo antiguo puede sostener una protección que el proyecto no ve.",
      "Global", "Reino Unido, transición telefónica 2026",
      "https://www.gov.uk/government/publications/public-switched-telephone-network-charter/public-switched-telephone-network-charter",
      [
          "Para una persona mayor, el teléfono fijo puede ser algo más que un teléfono. Una alarma de asistencia conectada a esa línea permite pedir ayuda después de una caída. Cambiar la tecnología de voz sin revisar la alarma puede cortar, sin advertirlo, un servicio de cuidado.",
          "El Reino Unido está retirando su red telefónica analógica. La guía oficial recuerda que alarmas, porteros y equipos de teleasistencia también dependen de ella. La migración no consiste solamente en que se escuche bien una llamada: exige descubrir qué dispositivos heredados siguen conectados y qué pasa durante un corte de luz.",
          "La carta de compromisos de 2026 es explícita: «Ningún usuario de teleasistencia será migrado» sin confirmar antes una solución compatible y funcional. Es una protección, no una nostalgia tecnológica.",
          "N18 invita a inventariar el sistema existente antes de sustituirlo. Hay que mirar usuarios, equipos, datos, dependencias y arreglos cotidianos. Algunas piezas son viejas y conviene retirarlas; otras contienen una función protectora que debe conservarse en la nueva arquitectura.",
          "La transición requiere pruebas con casos reales, respaldo de energía cuando corresponde y una salida transitoria para quien todavía no puede migrar. También necesita un responsable de verificar que la alarma efectivamente llegue a alguien después del cambio.",
          "Modernizar no es borrar lo anterior. Es poder explicar qué se perdió, qué se mantuvo y por qué ninguna persona quedó peor protegida al apagar la red vieja."
      ], quote_note="Cita traducida del inglés; fotografía conceptual.",
      extra_sources=[("Guía de transición", "https://www.gov.uk/guidance/moving-landlines-to-digital-technologies")]),
    a(19, "El dato salió del banco. La decisión siguió siendo tuya.", "Comprar, conectar o construir",
      "El crecimiento del Open Finance brasileño ilustra el valor y el costo de conectar capacidades que ya existen.",
      "América Latina", "Banco Central de Brasil, 2025",
      "https://www.bcb.gov.br/detalhenoticia/20813/noticia",
      [
          "Una persona quiere comparar un crédito. Sus datos están repartidos entre instituciones. Podría volver a cargarlos a mano, aceptar una oferta sin comparar o autorizar que viajen por una infraestructura compartida. La tercera opción puede mejorar la experiencia, pero solo si entiende qué comparte y con quién.",
          "El Banco Central de Brasil informó en 2025 que Open Finance contaba con 103 millones de autorizaciones activas y 68 millones de cuentas involucradas. También describió un crecimiento fuerte de pagos iniciados por esta vía. Los números muestran adopción, no prueban que cada consumidor haya obtenido una mejor decisión.",
          "«El avance de las autorizaciones demuestra el crecimiento de la infraestructura y la confianza de los usuarios», afirmó Matheus Rauber. La confianza, sin embargo, necesita límites y capacidad de revocar.",
          "N19 compara opciones reales: construir, comprar, adaptar, conectar o mantener una parte manual. No se decide por prestigio tecnológico. Se miran dependencia, costo total, capacidad interna, reversibilidad y consecuencias de una falla.",
          "Open Finance es una infraestructura compartida, no una solución completa para cada producto. Las instituciones que se conectan todavía deben explicar consentimiento, corregir datos, atender reclamos y demostrar un beneficio. La interfaz más rápida no justifica un intercambio que la persona no puede gobernar.",
          "La pregunta profesional no es «¿podemos conectarlo?». Es «¿qué decisión mejora al conectarlo, quién asume el riesgo y qué alternativa queda si deja de servir?»."
      ], quote_note="Cita traducida y abreviada del portugués; fotografía conceptual."),
    a(20, "Treinta y seis millones de contactos. ¿Cuántos problemas terminaron?", "Gestionar la transición",
      "La línea 311 de Nueva York enseña que una puerta única también necesita dueños, límites y criterios de cierre.",
      "Global", "Nueva York, 311, 2026",
      "https://www.nyc.gov/mayors-office/news/2026/03/mayor-mamdani-visits-nyc311-call-center-to-thank-staff--take-cal",
      [
          "Una vecina llama por un auto abandonado. Otra quiere entender una regla de reciclaje. Las dos usan el 311; sus pedidos terminan en lugares distintos. Desde afuera hay una sola puerta. Detrás trabajan centenares de servicios, áreas y organizaciones.",
          "La ciudad de Nueva York informó que en 2025 su 311 recibió 36.510.581 contactos por teléfono, web, aplicación, mensajes y redes. Atiende asuntos de más de doscientas agencias y entidades, las veinticuatro horas. En cuatro días de tormenta de 2026 recibió más de 800.000 contactos. Esa escala exige decisiones de operación, no solo una interfaz reconocible.",
          "La comisionada Lisa Gelobter dijo que la información debía quedar «a una llamada, mensaje o clic». Pero llegar a la puerta no equivale a obtener una respuesta final: alguien tiene que aceptar, seguir y cerrar cada caso.",
          "N20 propone gestionar el cambio con etapas y criterios visibles. ¿Qué tipo de pedido se incorpora primero? ¿Quién resuelve la excepción? ¿Qué evidencia permite declarar lista una nueva ruta? ¿Cuándo se transfiere del proyecto al servicio que la sostendrá?",
          "Una puerta única puede esconder colas distintas. Hay que medir el recorrido de la solicitud, no solo el volumen de contactos, y decirle al ciudadano qué área responde y cuándo volver a preguntar. Las fronteras del proyecto deben ser tan claras como la promesa pública.",
          "El lanzamiento de un canal es un hito. El cierre de una etapa se gana cuando las personas saben qué esperar y los equipos pueden cumplirlo incluso durante la próxima tormenta."
      ], quote_note="Cita traducida del inglés; fotografía conceptual."),
    a(21, "Abrió el call center. La espera no terminó ahí.", "El proyecto y el servicio",
      "El refuerzo de la línea 147 de Buenos Aires separa dos trabajos que suelen confundirse: inaugurar y sostener.",
      "Argentina", "Buenos Aires Salud, 2025",
      "https://buenosaires.gob.ar/gcaba_historico/noticias/la-ciudad-refuerza-la-linea-147-que-da-mas-de-10-mil-turnos-por-dia-en",
      [
          "La cinta de inauguración dura unos minutos. Un servicio de turnos sigue al día siguiente, cuando vuelven las llamadas, cambian las agendas y aparecen personas que no encontraron una respuesta por WhatsApp.",
          "La Ciudad reforzó en 2025 el 147 con un nuevo centro y más de trescientos operadores, supervisores y coordinadores. Informó que el canal gestionaba unos diez mil turnos de salud por día. El equipo recibió formación en derivación, protocolos y normas del sistema público. Esa formación no es un anexo: es parte del servicio que seguirá operando cuando termine el proyecto de ampliación.",
          "Jorge Macri habló de un sistema «en constante mejora». Tomar la frase en serio implica presupuesto, responsables, mediciones y una forma de reparar lo que falla después del anuncio.",
          "N21 distingue producto de operación. Entregar una plataforma y abrir puestos de atención son hitos finitos. Sostener calidad, adaptar horarios, corregir derivaciones y responder incidentes es un compromiso continuo. Si el proyecto se cierra sin transferir esa responsabilidad, deja una deuda invisible.",
          "El traspaso debe incluir manuales, datos de seguimiento, alertas, capacidad para cambiar reglas y un criterio de cuándo escalar una excepción. También alguien que escuche a los pacientes que quedaron fuera de la estadística de turnos otorgados.",
          "No hay fracaso en que un servicio siga necesitando trabajo. El fracaso sería declarar terminado el cambio justo cuando empieza su vida real."
      ]),
    a(22, "Detectar antes no alcanza si nadie cambia la respuesta.", "Poner la hipótesis a prueba",
      "El acuerdo del Malbrán para vigilancia genómica plantea una prueba exigente: demostrar que la detección temprana cambia una decisión.",
      "Argentina", "ANLIS Malbrán, 2026",
      "https://www.argentina.gob.ar/noticias/malbran-firma-un-acuerdo-con-illumina-para-fortalecer-la-vigilancia-genomica-en-argentina",
      [
          "Hay una diferencia enorme entre detectar un virus y evitar que un brote se agrande. El resultado de un laboratorio debe llegar a alguien que tenga tiempo, autoridad y medios para actuar. Si se pierde en el camino, una prueba técnicamente brillante puede no modificar nada.",
          "En 2026, el Malbrán anunció la validación prevista de un panel capaz de detectar cerca de doscientos virus. El comunicado habla de capacidad futura y de mejores tiempos de respuesta. No ofrece una comparación de brotes antes y después, porque esa prueba todavía debía hacerse.",
          "«Detectar un virus o una variante nueva a tiempo», dijo el ministro Mario Lugones, puede separar un brote controlado de un problema mayor.",
          "N22 invita a convertir esa afirmación en una hipótesis refutable. ¿En qué escenarios cambiaría la acción sanitaria? ¿Cuál es el tiempo total desde la muestra hasta la notificación? ¿Qué errores aceptaríamos y cuáles obligarían a frenar? Una prueba piloto debería comparar no solo exactitud, sino oportunidad y consecuencias.",
          "También hay que buscar el contrajemplo: un hallazgo más rápido que no permite una intervención distinta, o una señal nueva que produce alarmas sin mejorar la decisión. Si ocurre, el equipo necesita libertad para ajustar el diseño o abandonar una promesa demasiado amplia.",
          "La prueba profesional no es una ceremonia para confirmar la compra. Es una ocasión para descubrir, a tiempo, si el cambio merece crecer."
      ]),
    a(23, "Invitaron a siete mil docentes. Era apenas el comienzo.", "La primera entrega útil",
      "Una beta educativa británica muestra cómo empezar con un recorte pequeño sin perder el recorrido completo.",
      "Global", "Educación británica, 2025",
      "https://becoming-a-teacher.design-history.education.gov.uk/teacher-success/launching-the-service/",
      [
          "Una persona está por empezar a enseñar. No necesita todavía una plataforma que resuelva toda su carrera; necesita saber qué hacer ahora y cómo prepararse para el primer día. Si recibe cien funciones irrelevantes, lo grande puede ser menos útil que lo pequeño.",
          "En agosto de 2025, el equipo británico de educación lanzó la beta privada de Get ready to teach. Su primer grupo rondaba los siete mil futuros docentes. El servicio aspiraba a acompañarlos durante años, pero empezó por una etapa concreta: orientar a quienes estaban por iniciar la formación.",
          "El equipo lo presentó como «el primer paso» de una plataforma para toda la trayectoria profesional. Esa frase importa si el paso inicial funciona por sí mismo, no solo si promete lo que vendrá.",
          "N23 pregunta cómo definir una primera entrega útil. Un corte pequeño no es un botón suelto ni una demo: debe permitir que un grupo específico complete una necesidad reconocible. Hay que dejar claro dónde empieza el servicio, qué puede hacer hoy la persona y qué ocurre si necesita ayuda.",
          "La beta permite observar abandonos, dudas y efectos inesperados antes de ampliar el público. Pero invitar usuarios no demuestra valor por sí solo. Haría falta comprobar si llegaron más preparados, si entendieron el siguiente paso y qué parte del recorrido siguió fuera de la plataforma.",
          "Reducir alcance puede ser una forma de respeto. Le promete menos al primer usuario para poder cumplirle algo completo, medirlo y corregirlo antes de invitar a todos."
      ], quote_note="Cita traducida del inglés; fotografía conceptual."),
    a(24, "El agua alcanzaba. Hasta que llegaron los días de calor.", "Elegir con capacidad finita",
      "Ciudad del Cabo puso un límite diario para actuar antes de que la escasez obligara a restricciones mayores.",
      "Global", "Ciudad del Cabo, 2025",
      "https://www.capetown.gov.za/Media-and-news/Think%20water-wise,%20to%20keep%20the%20vibe%20this%20festive%20season",
      [
          "Después de un año con menos lluvia, el verano empezó a empujar el consumo de agua. No había una sequía declarada, pero esperar a tenerla podía dejar poco margen. Ciudad del Cabo tuvo que elegir qué hacer antes de que la urgencia eligiera por ella.",
          "En diciembre de 2025, los embalses estaban quince puntos por debajo del nivel de un año antes. La ciudad pidió mantener el uso total por debajo de 975 millones de litros diarios. El consumo ya había tocado mil millones en un día. También priorizó reparaciones, mantenimiento y coordinación con la autoridad nacional del agua.",
          "El concejal Zahid Badroodien lo llamó «el paso responsable» para reducir el riesgo de restricciones en 2027. La frase no convierte la meta en un resultado; muestra que la decisión tenía un costo visible hoy y un beneficio incierto mañana.",
          "N24 lleva esa lógica a cualquier organización. Tiempo, personas, dinero y atención son finitos. Priorizar exige decir qué entra, qué espera, qué obligación no se puede desplazar y cuánto puede costar la demora. No basta con ordenar una lista por entusiasmo.",
          "La reserva de capacidad parece ociosa hasta que llega una falla. Como en una red de agua, usar todo el margen en condiciones normales puede dejar al sistema sin respuesta cuando cambie el clima. Por eso conviene combinar señales tempranas con reglas explícitas de revisión.",
          "Una prioridad se vuelve real cuando aparece una demanda nueva y alguien puede explicar qué se mueve, quién asume la espera y qué evidencia haría cambiar la elección."
      ], quote_note="Cita traducida y abreviada del inglés; fotografía conceptual."),
    a(25, "Le dieron el alta. Seguía ocupando una cama.", "El tiempo que no figura en el alta",
      "Un hospital londinense descubrió que terminar la atención médica no siempre significa terminar el recorrido de una persona.",
      "Global", "St Thomas’, 2026",
      "https://www.guysandstthomas.nhs.uk/news/nurse-led-discharge-unit-helps-free-hospital-beds",
      pilot_pdf="output/pdf/METSI-cronicas-N25-piloto.pdf"),
    a(26, "Cuatro países, una identidad. ¿Quién responde si falla?", "El servicio cruza fronteras",
      "La identidad digital compartida del Mercosur muestra que interoperar también exige repartir responsabilidades.",
      "América Latina", "BID, Mercosur Digital",
      "https://www.iadb.org/en/news/mercosur-digital-citizen-initiative-enhance-service-delivery-and-simplify-procedures",
      [
          "Una empresa brasileña quiere realizar un trámite en Uruguay sin crear desde cero otra identidad digital. La idea parece sencilla: reconocer una credencial del país vecino. Debajo hay acuerdos técnicos, normativos y humanos entre organizaciones que no responden al mismo jefe.",
          "El BID presentó Mercosur Digital Citizen para permitir trámites transfronterizos con identidades nacionales. Informó que Brasil y Uruguay habían integrado 39 procedimientos y que Argentina y Paraguay formaban parte de la iniciativa. También describió años de preparación legal y técnica.",
          "«El reconocimiento regional de identidades digitales facilitará los intercambios y ahorrará costos y tiempo», dijo Paula Acosta, del BID.",
          "N26 pregunta qué ocurre cuando el servicio depende de varios actores. Si la validación falla, ¿a quién llama la persona? ¿Quién conserva el registro? ¿Qué evidencia necesita el organismo receptor? Una integración puede funcionar en el contrato y fallar en la mesa de ayuda si nadie acepta el caso de punta a punta.",
          "Los acuerdos deben cubrir disponibilidad, seguridad, cambios de versión, incidentes y alternativas para quien no puede usar la vía digital. No basta con conectar APIs: hace falta una promesa común de servicio y una forma de reparar su incumplimiento.",
          "Cruzar una frontera debería quitarle trabajo al ciudadano, no obligarlo a convertirse en coordinador de cuatro instituciones."
      ], quote_note="Cita traducida del inglés; fotografía conceptual."),
    a(27, "El mensaje llegó. La atención no entendió lo mismo.", "Acordar significados",
      "Las pruebas de intercambio clínico en Argentina muestran que interoperabilidad no es solo mover datos.",
      "Argentina", "Salud Digital Argentina, 2026",
      "https://www.argentina.gob.ar/noticias/salud-impulsa-la-interoperabilidad-para-consolidar-un-sistema-de-salud-digital-integrado",
      [
          "Un médico envía un dato. Otro sistema lo recibe sin error. En la pantalla de destino aparece la palabra correcta, pero el equipo que atiende le da un significado distinto. La red funcionó. La decisión clínica puede quedar peor informada.",
          "En junio de 2026, el Ministerio de Salud reunió equipos de varias jurisdicciones en pruebas de intercambio de información clínica en tiempo real. También trabajaron sobre estándares comunes. Es la parte menos espectacular y más decisiva de una integración: acordar qué quiere decir cada mensaje y qué hará quien lo reciba.",
          "«Avanzar hacia una interoperabilidad real, con orden y reglas claras», pidió el ministro Mario Lugones. Esa regla tiene que poder leerse en ejemplos, no solo en un documento general.",
          "N27 propone contratos semánticos: campos, eventos, responsables, respuestas esperadas y manejo de errores. Si «alta» significa egreso clínico en un sistema y fin administrativo en otro, el contrato debe distinguirlos. Si una corrección llega tarde, debe quedar claro cuál versión rige.",
          "La prueba útil no se limita a mandar un caso perfecto. Incluye datos incompletos, duplicados, correcciones y demoras. También pregunta quién investiga un desacuerdo y quién puede detener una automatización insegura.",
          "El mensaje más importante de una integración es quizá el que dice: «No entendí lo mismo». Conviene que aparezca en la prueba, no frente al paciente."
      ]),
    a(28, "El turno existía. El paciente no pudo llegar a la consulta.", "Probar el servicio real",
      "Los varios canales de atención porteños invitan a ensayar situaciones que una prueba de pantalla no ve.",
      "Argentina", "Buenos Aires Salud, 2026",
      "https://buenosaires.gob.ar/gcaba_historico/noticias/la-ciudad-transformo-un-viejo-galpon-ferroviario-en-un-nuevo-centro-de",
      [
          "Una persona consigue turno por teléfono. Otra por un bot. Una tercera llega en persona porque no pudo usar ninguno de los dos. El sistema puede mostrar disponibilidad en los tres canales y aun así fallar si una derivación, un dato de ubicación o un requisito no llega a tiempo.",
          "Al presentar un nuevo centro de salud en Colegiales en 2026, la Ciudad enumeró vías de acceso: 147, Boti, BAX, web y atención presencial. El ministro Fernán Quirós resumió la aspiración: que cada vecino tenga «un equipo de salud que lo conozca» y pueda vincularlo con otros niveles de atención cuando sea necesario.",
          "N28 pide comprobar funcionamiento desde quien necesita el servicio. No solo si un botón responde, sino si la persona pudo orientarse, llegar, ser atendida y continuar el cuidado. Una prueba realista incluye cambios de horario, ausencia de conexión, una derivación urgente y alguien que requiere ayuda.",
          "Cada caso difícil enseña algo distinto: accesibilidad, continuidad, consistencia entre canales o recuperación ante un error. Si el equipo solo ensaya el camino feliz, el primer usuario real termina haciendo la prueba de estrés sin haberlo consentido.",
          "La calidad no está en que todos los canales existan. Está en que la persona no tenga que empezar de cero cada vez que pasa de uno a otro."
      ]),
    a(29, "Prometieron una tarjeta nueva. Tuvieron que conservar la vieja.", "Puesta en marcha con red de seguridad",
      "Singapur frenó una transición de pagos en transporte y dejó una lección sobre reversión y confianza pública.",
      "Global", "Singapur, SimplyGo, 2024",
      "https://www.lta.gov.sg/content/ltagov/en/newsroom/2024/2/news-releases/new-cbt-cards-available-for-eligible-commuters-from-18-march-202.html",
      [
          "Una tarjeta de transporte puede parecer una tecnología menor hasta que deja de mostrar el saldo al pasar por el molinete. Para quien calcula cada viaje, ese detalle es parte del servicio. Cambiar el sistema de cobro sin conservarlo podía sentirse como perder control.",
          "Singapur había anunciado que retiraría ciertas tarjetas antiguas en junio de 2024 para avanzar hacia SimplyGo. La autoridad de transporte explicó que el nuevo sistema permitía consultar viajes desde el teléfono, pero el saldo ya no aparecía al instante en los lectores. Tras la respuesta pública, decidió mantener el sistema anterior en paralelo al menos hasta 2030 y ofrecer tarjetas de retorno a quienes ya habían migrado.",
          "El reporte anual de la autoridad dice que la extensión se hizo «en respuesta a los comentarios del público». No fue un detalle cosmético: cambió la secuencia del despliegue y el costo de sostener dos sistemas.",
          "N29 trata la puesta en marcha como una operación con red de seguridad. Hay que ensayar, comunicar diferencias, medir problemas reales y definir de antemano cuándo limitar, corregir o revertir un cambio. La reversión necesita datos, capacidad y responsables; no se improvisa durante la fila de la mañana.",
          "También hay que distinguir adopción de aceptación. Muchas personas pueden usar una tarjeta porque no tienen otra opción. Una transición buena pregunta qué perdieron, qué aprendieron y si pueden seguir viajando mientras la organización corrige.",
          "La confianza no nace de prometer que nunca hará falta volver atrás. Nace de demostrar que, si hace falta, la organización sabe hacerlo sin dejar al pasajero en el andén."
      ], quote_note="Cita traducida del inglés; fotografía conceptual.",
      extra_sources=[("Reporte LTA", "https://www.lta.gov.sg/content/dam/ltagov/who_we_are/statistics_and_publications/report/pdf/LTA_AR2324.pdf")]),
    a(30, "El ataque terminó. El incidente, no.", "Responder y aprender",
      "El Banco Central de Brasil mira la ciberseguridad como una responsabilidad de toda la red financiera, no de una institución aislada.",
      "América Latina", "Banco Central de Brasil, 2026",
      "https://www.bcb.gov.br/detalhenoticia/21106/noticia",
      [
          "Una institución recupera su servicio tras un incidente. Aun así quedan preguntas: ¿qué datos pudieron alterarse?, ¿qué proveedor sigue expuesto?, ¿a quién hay que avisar?, ¿qué decisión debe cambiar para que el mismo daño no reaparezca?",
          "En 2026, el Banco Central de Brasil reunió a bancos, proveedores de software, tecnología y seguridad para tratar resiliencia cibernética. Su director Rodrigo Teixeira señaló que Pix y otras infraestructuras se volvieron cotidianas y críticas, con beneficios que también ampliaron la exposición a riesgos.",
          "«La resiliencia del sistema no se construye de forma aislada», dijo Teixeira. La frase desplaza la idea de que cada organización pueda cerrar su parte y desentenderse del resto.",
          "N30 une detección, respuesta y aprendizaje. Detectar requiere señales confiables; responder exige responsables, límites y rutas de escalamiento; aprender implica revisar causas y cambiar controles. Un informe que nadie convierte en acción no cierra el ciclo.",
          "Hay que separar restauración de resolución. El servicio puede volver y todavía necesitar investigación, reparación de datos, atención a afectados y pruebas de que la medida correctiva funciona. Las métricas de tiempo de recuperación no cuentan, por sí solas, esa historia completa.",
          "Un incidente no termina cuando deja de aparecer en el tablero. Termina cuando el sistema —incluidas las personas y los terceros— quedó en mejores condiciones para resistir el siguiente."
      ], quote_note="Cita traducida del portugués; fotografía conceptual."),
    a(31, "La IA respondió en segundos. ¿Quién responde por ella?", "Elegir una tarea concreta",
      "El nuevo asistente estatal argentino obliga a separar una respuesta útil de una decisión que todavía requiere personas.",
      "Argentina", "Secretaría de Innovación, 2025",
      "https://www.argentina.gob.ar/noticias/se-presento-mia-el-primer-agente-de-inteligencia-artificial-del-estado-nacional",
      [
          "Una emprendedora pregunta qué necesita para iniciar un trámite. Un asistente contesta con una lista impecable. Pero la respuesta que importa no es solo si suena clara: ¿está vigente?, ¿corresponde a su caso?, ¿qué pasa si falta un requisito y ella actúa confiada?",
          "En septiembre de 2025, el Estado argentino presentó MIA, una evolución de TINA con IA generativa. La primera etapa se orientó a emprendedores y pequeñas empresas, además de asistir a usuarios de Mi Argentina. Según el anuncio oficial, se alimenta de una base cerrada de información sobre trámites y servicios; eso reduce algunos riesgos, pero no equivale a demostrar que todas sus respuestas sean correctas.",
          "Darío Genua planteó el objetivo de una administración «más ágil, innovadora y centrada en las necesidades de la ciudadanía». El adjetivo decisivo es «centrada»: la velocidad solo importa si la persona puede completar lo que vino a hacer.",
          "N31 propone decidir dónde la IA ayuda y dónde no. Una tarea acotada puede ser orientar, buscar una norma o explicar un requisito. Distinto es aprobar un derecho, rechazar una solicitud o interpretar una excepción. Para cada función hay que definir fuentes, límites, riesgo del error y una salida hacia atención humana.",
          "También hay que poder atribuir responsabilidad. Si el asistente inventa una condición, ¿quién la detecta, corrige la información y repara el perjuicio? Una pantalla conversacional no es un empleado a quien se le pueda pedir cuentas.",
          "La pregunta no es si la IA responde bien en una demo. Es si la institución sabe qué le permitió hacer, qué le prohibió y cómo ayudará a la persona cuando la respuesta falle."
      ]),
    a(32, "Antes de soltar la IA, Uruguay la puso a prueba.", "Experimentar bajo condiciones",
      "Los entornos controlados de prueba uruguayos ofrecen una forma de aprender sin convertir al público en conejillo de Indias.",
      "América Latina", "Agesic, 2026",
      "https://www.gub.uy/agencia-gobierno-electronico-sociedad-informacion-conocimiento/comunicacion/noticias/uruguay-presento-iniciativa-entornos-controlados-prueba",
      [
          "Un sistema de IA puede contestar cien preguntas fáciles y equivocarse justo en la que afecta una beca, una consulta médica o un reclamo. Por eso una prueba no debería medir solo cuántas veces acierta: debe buscar los errores que sería más costoso descubrir después.",
          "Uruguay presentó en mayo de 2026 una iniciativa de entornos controlados de prueba para proyectos innovadores. Su diseño combina tiempo limitado, supervisión y condiciones específicas antes de una adopción más amplia. Es un marco para probar y aprender; no una certificación anticipada de que todo producto será seguro.",
          "Pablo Siris describió la apuesta como un «modelo de IA basado en el equilibrio inteligente». Ese equilibrio requiere decidir qué se va a observar, quién puede detener la prueba y qué evidencia justificaría ampliar el uso.",
          "N32 baja la evaluación a casos concretos. Hay que probar entradas ambiguas, personas con necesidades distintas, datos incompletos, indicaciones contradictorias y situaciones en las que una respuesta plausible puede causar daño. Conviene comparar la IA con el proceso vigente, no con un ideal imaginario.",
          "Las pruebas necesitan registros de error, criterios de aceptación y revisión humana. Si una herramienta falla con un grupo pequeño o se vuelve opaca ante una excepción, no basta con promediarla con sus éxitos más fáciles. El peor caso también forma parte del desempeño.",
          "Salir del entorno controlado debe ser una decisión argumentada, reversible y proporcional al riesgo. La prudencia no frena la innovación: evita que la primera evaluación seria la hagan quienes dependen del servicio."
      ]),
    a(33, "La IA pasó la prueba. Eso no significa que siga funcionando.", "Vigilar después del estreno",
      "Un informe de NIST recuerda que el uso real cambia las preguntas y los riesgos de cualquier sistema de IA.",
      "Global", "NIST, 2026",
      "https://www.nist.gov/news-events/news/2026/03/new-report-challenges-monitoring-deployed-ai-systems",
      [
          "El asistente se estrenó con respuestas revisadas. Semanas después aparecen consultas que nadie imaginó, cambian los documentos de referencia y los usuarios empiezan a usarlo para decisiones más delicadas. El sistema es el mismo. El contexto ya no.",
          "En marzo de 2026, NIST publicó un informe sobre las dificultades de monitorear IA después de su despliegue. La organización distinguió seis frentes: funcionamiento, operación, interacción humana, seguridad, cumplimiento e impactos amplios. También señaló barreras como la degradación del desempeño y los registros fragmentados.",
          "El informe pregunta «who, what, when, why, and how» monitorear; es decir, quién mira, qué mira, cuándo, por qué y cómo. Traducir esas preguntas a responsables concretos es más difícil que decir «vamos a monitorear». ",
          "N33 trata la supervisión como parte permanente del servicio. Hay que observar errores reales, quejas, cambios en los datos, diferencias entre grupos y decisiones humanas que corrigen a la IA. Una métrica agregada puede esconder que un tipo de persona recibió sistemáticamente peor ayuda.",
          "La organización necesita umbrales para corregir, limitar o retirar funciones. También un canal para que usuarios y trabajadores reporten fallas sin tener que demostrar primero cómo funciona el modelo por dentro. Una revisión anual puede llegar demasiado tarde para un daño diario.",
          "El lanzamiento no cierra la evaluación; la abre. Si nadie tiene autoridad y tiempo para cambiar el sistema ante nueva evidencia, la supervisión es un título en el organigrama, no una protección."
      ], quote_note="Cita breve traducida del informe; fotografía conceptual."),
    a(34, "El seguimiento casi se duplicó. ¿Fue por conectar los datos?", "Volver al problema original",
      "En India, un identificador clínico permitió medir el cambio más allá de la conexión entre sistemas.",
      "Global", "OMS India, Chhattisgarh 2025",
      "https://www.who.int/india/news-room/feature-stories/detail/noncommunicable-disease-management-goes-digital-in-chhattisgarh",
      [
          "Una persona con hipertensión no necesita que dos bases de datos se saluden. Necesita que el centro de salud sepa que debe verla otra vez, qué tratamiento recibió y si su presión mejoró. Una integración solo cobra sentido cuando acompaña ese recorrido.",
          "En el distrito de Durg, estado de Chhattisgarh, se vincularon 12.627 identificadores de salud con registros de hipertensión y diabetes entre enero de 2024 y febrero de 2025. La OMS informó que las visitas de seguimiento llegaron al 68% entre pacientes vinculados, frente al 37% entre no vinculados; el control de la enfermedad fue 49% contra 29%. La comparación muestra una asociación, no prueba por sí sola que el identificador haya causado toda la diferencia.",
          "La enfermera Jhaneshwary Sahu contó que al escanear el código redujo «entradas duplicadas y mejoró los seguimientos». Esa frase acerca la infraestructura a una tarea concreta: encontrar a la persona correcta y volver a contactarla.",
          "N34 pide recomponer el hilo entero: problema inicial, decisión tomada, evidencia, implementación y resultado. Si medimos solo identificadores creados, podemos declarar éxito aunque el control clínico no cambie. Si miramos el seguimiento, aparecen personas, capacitación, conexión y protocolos.",
          "También hay que observar a quienes quedaron fuera. El portal sin conexión no admitía esa integración en algunos centros, de modo que se trabajó para pasar al modo en línea. Esa frontera importa tanto como el promedio final.",
          "La pregunta que cierra el recorrido no es «¿se conectó?». Es «¿quién recibió mejor atención, quién todavía no y qué decisión cambiaremos con lo aprendido?»."
      ], quote_note="Cita traducida y abreviada del inglés; fotografía conceptual."),
    a(35, "Una credencial nueva. ¿Quién sabe qué puede hacer con ella?", "Explicar para que otros actúen",
      "México avanza en un servicio de salud más integrado y enfrenta un desafío menos vistoso: comunicar cada paso con claridad.",
      "América Latina", "Gobierno de México, 2026",
      "https://www.gob.mx/presidencia/prensa/presidenta-anuncia-decreto-para-crear-el-servicio-universal-de-salud-del-13-al-30-de-abril-inicia-credencializacion-de-personas-de-85-anos?idiom=es",
      [
          "Una mujer de 86 años escucha que tendrá una credencial para usar servicios de salud. Su pregunta no es cómo se llama la política. Quiere saber dónde se registra, qué documentos lleva, qué atención puede recibir hoy y qué cosas todavía no están disponibles.",
          "En abril de 2026, México anunció el decreto para crear el Servicio Universal de Salud y el inicio del registro de personas de 85 años o más. La comunicación oficial separó etapas: credencialización primero; algunas funciones digitales durante 2026 y otras —como gestión de citas e historial clínico— previstas para 2027. Son planes, no resultados ya comprobados.",
          "Claudia Sheinbaum lo llamó «un paso histórico». Para que ese paso exista en la vida cotidiana, la explicación pública debe resistir la pregunta de la persona frente al mostrador.",
          "N35 trabaja esa transferencia. Una decisión profesional no se comunica solo con un documento final: requiere explicar a quién afecta, qué cambia, qué no cambia todavía, quién hace cada tarea, cómo se reconoce un error y dónde se pide ayuda. La claridad es parte del funcionamiento.",
          "Los públicos necesitan versiones distintas de la misma verdad. Una persona usuaria requiere instrucciones concretas; una trabajadora del módulo, criterios para resolver excepciones; una autoridad, evidencia de alcance y límites. Si esas versiones se contradicen, el servicio se fragmenta antes de empezar.",
          "Explicar bien no embellece la implementación. Permite que otros la discutan, la ejecuten y la corrijan. Lo que nadie puede entender tampoco puede sostenerse."
      ]),
    a(36, "La IA ya estaba en clase. El programa llegó después.", "Aprender de lo que ya pasó",
      "En Uruguay, una encuesta docente cambió la pregunta: no si usar IA, sino cómo acompañar un uso que ya existía.",
      "América Latina", "ANEP y Ceibal, 2026",
      "https://www.anep.edu.uy/futuro-ya-llego-anep-ceibal-presentaron-herramientas-inteligencia-artificial-para-docentes",
      [
          "A veces el proyecto llega tarde a la realidad. Las herramientas ya están en uso, los docentes probaron caminos propios y los alumnos aprendieron reglas no escritas. La primera tarea no es anunciar una novedad: es descubrir qué está pasando.",
          "En junio de 2026, ANEP y Ceibal presentaron herramientas institucionales de IA para docentes uruguayos. La decisión siguió a estudios nacionales: el 75% de la comunidad docente ya usaba IA en su trabajo, pero solo el 37% sentía dominarla conceptualmente. La cifra no demuestra calidad educativa; sí muestra una brecha que era imposible ignorar.",
          "La presidenta de Ceibal, Fiorella Haim, describió el método: «estudiar lo que está sucediendo, escuchar mucho a la comunidad docente». Luego evaluar y decidir cómo acompañar. La secuencia empieza por la práctica real, no por el catálogo de herramientas.",
          "N36 vuelve sobre todo el recorrido. Pregunta qué supuestos quedaron en pie, cuáles cambiaron, a quién ayudó una intervención y qué trabajo nuevo apareció. También obliga a mirar lo que hicimos bien: un éxito no debe convertirse en receta para contextos que tienen otras personas, reglas y recursos.",
          "Ceibal viene de una trayectoria mucho más larga que este lanzamiento. Su reporte de 2025 incluye millones de dispositivos distribuidos desde el inicio, expansión de programas y una política de reparación que recupera componentes. Cada etapa dejó evidencia para cambiar la siguiente; ninguna foto de entrega resume por sí sola lo aprendido.",
          "Una buena memoria de proyecto no dice simplemente «funcionó». Deja la decisión, la evidencia de entonces, lo que pasó después y las preguntas abiertas. Así el siguiente equipo no empieza de cero ni repite nuestros errores con otro nombre."
      ], extra_sources=[("Ceibal 2025", "https://www.gub.uy/ministerio-educacion-cultura/comunicacion/noticias/segundo-reporte-sostenibilidad-ceibal-presenta-principales-hitos-del-2025")]),
]
