#!/usr/bin/env python3
"""Build canonical METSI Block E content packages, N21 through N25."""

from __future__ import annotations

import json

import build_block_d_content as base


def u(title, definition, distinction, mechanism, evidence, example, boundary):
    return [title, definition, distinction, mechanism, evidence, example, boundary]


def doc(*, slug, title, question, opening_title, opening, hotel, advance, defer,
        units, instrument_title, instrument_fields, transfer_title, transfer,
        counter_title, counter, errors, referents, references):
    result = base.compact_doc(
        slug=slug, title=title, question=question, opening_title=opening_title,
        opening=opening, hotel=hotel, advance=advance, defer=defer, units=units,
        instrument_title=instrument_title, instrument_fields=instrument_fields,
        transfer_title=transfer_title, transfer=transfer, counter_title=counter_title,
        counter=counter, errors=errors, referents=referents, references=references,
    )
    result["consequences"] = advance + " El avance profesional consiste en gobernar una capacidad y sus consecuencias, no en defender el nombre de una práctica ni la cantidad de entregables producidos."
    result["limits"] = "Ninguna categoría elimina el juicio situado. Los indicadores simplifican, los contratos distribuyen poder, la urgencia altera prioridades y la evidencia llega con demora. Por eso el expediente conserva supuestos, poblaciones afectadas, autoridad, excepciones y una fecha de revisión. La disciplina no promete neutralidad: vuelve discutible qué se privilegia y qué se deja de hacer."
    return result


DOCS = {
21: doc(
 slug="proyecto_producto_servicio_y_plataforma",
 title="Proyecto, producto, servicio y plataforma",
 question="¿Qué cambia cuando una iniciativa deja de administrarse como entrega temporal y empieza a gobernarse como capacidad que alguien usa, opera y comparte?",
 opening_title="El proyecto terminó, pero el hotel siguió esperando",
 opening=[
  "Hotel Horizonte cierra la implementación del nuevo circuito de ingreso. El alcance fue entregado, el presupuesto quedó dentro del umbral y el acta de aceptación enumera interfaces, capacitación y migración. Dos semanas después, Recepción acumula excepciones, Housekeeping crea una planilla auxiliar y Comercial pide una regla que el contrato no contemplaba.",
  "La dirección pregunta por qué el proyecto no resolvió el problema. Tecnología responde que el producto funciona; el proveedor sostiene que el servicio se presta según el acuerdo; Operaciones señala que la plataforma común todavía obliga a coordinar a mano con cerraduras, pagos y canales externos. Las cuatro afirmaciones pueden ser ciertas y, sin embargo, describir objetos distintos.",
  "Proyecto nombra una organización temporal para producir cambio. Producto nombra una propuesta de valor que evoluciona. Servicio nombra una promesa sostenida en uso. Plataforma nombra una base compartida que habilita interacciones y capacidades de otros. Si se confunden, el cierre administrativo puede parecer resultado, una interfaz puede reemplazar a la experiencia y una infraestructura común puede gobernarse como si tuviera un único cliente.",
  "El equipo vuelve a HH-20 y separa temporalidad, ownership, outcome, operación y ecosistema. Conserva el proyecto como vehículo de transición, asigna un responsable de producto para la capacidad de ingreso, explicita el servicio prometido al huésped y trata las integraciones como decisiones de plataforma con reglas de acceso, evolución y salida.",
  "La distinción no busca elegir una palabra moderna. Cambia presupuesto, métricas, horizonte, autoridad y evidencia. También muestra que un mismo sistema puede contener los cuatro objetos sin que uno absorba a los demás.",
  "N21 abre el Bloque E. Recibe una estrategia situada y pregunta qué objeto se está gobernando. La respuesta prepara una gestión orientada a capacidades, aprendizaje y operación antes de discutir hipótesis, cortes y flujo."
 ],
 hotel="HH-20 dejó una estrategia con puertas, evidencia y condiciones de salida. HH-21 la reorganiza en cuatro capas: un proyecto temporal para la transición, un producto que aprende sobre el problema de ingreso, un servicio que sostiene la promesa durante cada turno y una plataforma que permite a canales, cerraduras, pagos y analítica participar sin perder contratos ni autoridad.",
 advance="N21 distingue proyecto, producto, servicio y plataforma por su propósito, horizonte, unidad de valor, ownership, evidencia y condición de cierre, y muestra cómo pueden coexistir alrededor de una capacidad.",
 defer="N22 recibirá esta arquitectura y convertirá sus iniciativas en hipótesis refutables. N21 no decide todavía qué apuesta merece inversión ni cómo probarla.",
 units=[
  u("Proyecto", "Un proyecto es una organización temporal creada para producir un cambio definido bajo restricciones explícitas.", "No es el sistema permanente, el equipo estable ni el valor producido después del cierre.", "Coordina trabajo, dependencias y compromisos hasta transferir resultados y responsabilidades.", "Se sostiene con entregables aceptados, riesgos tratados, decisiones registradas y capacidad de transferencia.", "La migración del circuito de ingreso tiene comienzo, presupuesto, hitos y cierre.", "Puede terminar con éxito aunque el outcome no se sostenga; por eso no reemplaza la gestión posterior."),
  u("Producto", "Un producto es una propuesta de valor que evoluciona mediante decisiones continuas sobre problemas, resultados y capacidades.", "No se reduce a software, interfaz, backlog ni conjunto de funcionalidades.", "Integra descubrimiento, construcción, medición y aprendizaje bajo ownership persistente.", "Se prueba con cambios observables en uso, outcome, viabilidad y capacidad de adaptación.", "El circuito de ingreso es producto cuando aprende a reducir espera sin trasladar daño.", "Puede no ser el objeto adecuado para obligaciones estables o infraestructura compartida."),
  u("Servicio", "Un servicio es una promesa de resultado que una organización sostiene junto con quienes lo usan y operan.", "No equivale al canal digital ni al acuerdo de niveles de servicio aislado.", "Combina personas, tecnología, reglas, evidencia y reparación durante la experiencia real.", "Se observa en continuidad, calidad, accesibilidad, recuperación y percepción de quienes reciben la prestación.", "Entregar una habitación asignable y accesible es servicio aunque intervengan varios productos.", "Una prestación puede cumplir métricas técnicas y quebrar la promesa para una población."),
  u("Plataforma", "Una plataforma es una base gobernada de capacidades compartidas que permite a múltiples participantes crear y coordinar valor.", "No es sólo infraestructura, portal, arquitectura ni producto grande.", "Ofrece servicios comunes, interfaces, estándares y reglas que reducen coordinación sin borrar autonomía.", "Se evalúa por adopción útil, confiabilidad, reutilización, costos de integración y salud del ecosistema.", "Identidad, pagos y estados hoteleros habilitan canales internos y externos.", "Centralizar sin gobernanza puede crear dependencia, cuello de botella y poder sin rendición de cuentas."),
  u("Horizonte temporal", "El horizonte temporal expresa cuánto dura el objeto y cuándo cambia su forma de gobierno.", "No es la fecha del roadmap ni la duración estimada de una tarea.", "Los proyectos terminan; productos, servicios y plataformas persisten mientras sostengan una capacidad relevante.", "La evidencia incluye continuidad de ownership, presupuesto, obligaciones y decisiones posteriores al lanzamiento.", "El proyecto cierra, pero las excepciones del ingreso siguen necesitando gobierno.", "Declarar permanente un objeto sin criterio de retiro inmoviliza recursos y legado."),
  u("Unidad de valor", "La unidad de valor define qué cambio significativo justifica inversión y aprendizaje.", "No coincide necesariamente con feature, entrega, transacción ni utilización.", "Conecta una necesidad con una capacidad y una consecuencia observable para actores concretos.", "Se fortalece cuando el outcome puede distinguirse de actividad, volumen y efecto ajeno.", "Menor espera con igual protección accesible vale más que más check-ins procesados.", "Una única unidad puede ocultar impactos distributivos o costos de operación."),
  u("Ownership persistente", "Ownership persistente es autoridad y responsabilidad continuas sobre decisiones, evidencia y consecuencias.", "No es un nombre en un organigrama ni la función temporal de un jefe de proyecto.", "Mantiene memoria, priorización, aprendizaje y reparación más allá de cada entrega.", "Se verifica cuando existe capacidad real para cambiar, detener, financiar y responder por el resultado.", "Una responsable de producto puede revisar la regla después del cierre contractual.", "Responsabilidad sin presupuesto, información o poder de decisión es sólo imputación."),
  u("Operación como diseño", "Operación como diseño trata uso, soporte, excepción y recuperación como parte del objeto gestionado.", "No es una etapa posterior ni un costo inevitable que se delega al área operativa.", "La capacidad se completa cuando funciona en turnos, picos, ausencias y fallas.", "Incidentes, retrabajo, demanda de falla y tiempo de reparación revelan la calidad real.", "El turno nocturno debe resolver una habitación bloqueada sin llamar al equipo del proyecto.", "Diseñar sólo para el camino feliz produce valor aparente y deuda operativa."),
  u("Ecosistema", "Un ecosistema reúne actores interdependientes que crean, capturan y condicionan valor mediante reglas e interfaces.", "No es una lista de stakeholders ni una cadena lineal de proveedores.", "Cambios locales alteran incentivos, datos, riesgos y posibilidades de otros participantes.", "Se observa en dependencias, efectos de red, costos de cambio, disputas y mecanismos de coordinación.", "Un canal puede vender antes y trasladar excepciones a Recepción.", "La expansión del ecosistema puede aumentar valor y también concentración o exclusión."),
  u("Financiación por capacidad", "Financiar por capacidad asigna recursos a un outcome y a la posibilidad de sostenerlo, aprender y repararlo.", "No significa presupuesto ilimitado ni ausencia de control por iniciativa.", "Reduce reinicios y handoffs al sostener equipos y decisiones alrededor del problema.", "Se evalúa por outcomes, opciones preservadas, costo total y decisiones de continuidad.", "Ingreso recibe una capacidad estable con fondos para operación y aprendizaje.", "Sin límites y revisión, la financiación persistente puede proteger productos sin valor."),
  u("Gobernanza del portafolio", "La gobernanza del portafolio compara inversiones por contribución, dependencia, riesgo y aprendizaje.", "No es ordenar proyectos por retorno estimado ni sumar roadmaps independientes.", "Hace visibles capacidades compartidas, conflictos de recursos y compromisos que compiten.", "Escenarios, outcomes y costos de demora permiten discutir qué iniciar, sostener o retirar.", "La plataforma de identidad puede habilitar varias iniciativas y requerir prioridad distinta.", "La comparación numérica no elimina elecciones políticas ni derechos no negociables."),
  u("Cierre y retiro", "Cierre y retiro son decisiones diferentes: una termina el vehículo temporal y la otra deja de sostener una capacidad.", "No deben confundirse con lanzamiento, aceptación ni apagado técnico.", "El cierre transfiere; el retiro comunica, migra, preserva evidencia y repara dependencias.", "Se prueba con roles operativos, inventario, datos, contratos, contingencia y usuarios afectados.", "El proyecto cierra mientras el producto sigue; una integración se retira con ruta alternativa.", "Cerrar sin transferencia crea abandono y retirar sin ecosistema produce daño lateral."),
 ],
 instrument_title="Instrumento HH-21: mapa de objetos y responsabilidades",
 instrument_fields=["Problema y outcome","Objeto principal","Objetos coexistentes","Horizonte","Unidad de valor","Usuarios y operadores","Ownership","Financiación","Interfaces","Métricas","Cierre o retiro","Riesgo y revisión"],
 transfer_title="Caso de transferencia: inscripción universitaria",
 transfer=["Una universidad moderniza la inscripción. El proyecto implementa cambios; el producto organiza decisiones sobre la experiencia; el servicio garantiza acceso y respuesta; la plataforma ofrece identidad, pagos y datos a varias facultades.","Si todo se llama sistema de inscripciones, nadie distingue quién puede cerrar el proyecto, quién aprende sobre el producto, quién sostiene el servicio durante picos y quién gobierna la base común.","HH-21 permite separar objetos sin fragmentar la responsabilidad por el outcome."],
 counter_title="Contraejemplo: llamar producto a cualquier aplicación",
 counter=["Una organización renombra todas sus aplicaciones como productos y asigna product owners.","Los equipos siguen financiados por proyecto, sin autoridad sobre operación ni evidencia de outcome. El vocabulario cambia y el mecanismo permanece.","La distinción vale sólo si transforma horizonte, decisión, medida y responsabilidad."],
 errors=["Llamar producto a todo","Cerrar el proyecto y abandonar la capacidad","Confundir servicio con canal","Tratar plataforma como infraestructura neutral","Medir valor por funcionalidades","Asignar ownership sin autoridad","Financiar equipos sin criterio de revisión","Olvidar operadores","Ignorar efectos de ecosistema","Retirar sin transición"],
 referents=[["Project Management Institute","Distingue proyectos y dominios de desempeño orientados a valor."],["Marty Cagan","Desarrolló una práctica de producto centrada en problemas, resultados y equipos empoderados."],["ITIL","Formula la gestión de servicios como cocreación de valor."],["Geoffrey Parker, Marshall Van Alstyne y Sangeet Choudary","Analizaron plataformas, efectos de red y gobierno de ecosistemas."],["Mik Kersten","Vinculó flujo de valor, producto y financiación organizacional."],["Team Topologies","Relaciona equipos, plataformas internas y flujo de cambio."]],
 references=["Project Management Institute (2021). A Guide to the Project Management Body of Knowledge, Seventh Edition. PMI.","Project Management Institute (2024). The Standard for Program Management, Fifth Edition. PMI.","Cagan, M. (2018). Inspired. Wiley.","Cagan, M. y Jones, C. (2021). Empowered. Wiley.","AXELOS (2019). ITIL Foundation: ITIL 4 Edition. TSO.","ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html","Parker, G. G., Van Alstyne, M. W. y Choudary, S. P. (2016). Platform Revolution. Norton.","Tiwana, A. (2014). Platform Ecosystems. Morgan Kaufmann.","Kersten, M. (2018). Project to Product. IT Revolution.","Skelton, M. y Pais, M. (2019). Team Topologies. IT Revolution.","Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.","Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops"]
),
22: doc(
 slug="iniciativas_como_hipotesis_que_pueden_refutarse",
 title="Iniciativas como hipótesis que pueden refutarse",
 question="¿Cómo dejar de defender una iniciativa por su promesa y empezar a exigirle evidencia capaz de cambiar la decisión?",
 opening_title="La iniciativa que siempre encontraba una métrica a favor",
 opening=["Hotel Horizonte propone automatizar la asignación de habitaciones. La presentación promete menos espera, mejor ocupación y una experiencia consistente. Cada área aporta una razón distinta y todas quedan condensadas en una iniciativa llamada asignación inteligente.","El piloto mejora el tiempo promedio, pero aumenta cambios tardíos en habitaciones accesibles. Comercial celebra ocupación; Recepción registra reclamos; Tecnología muestra disponibilidad; Housekeeping observa más interrupciones. La iniciativa sobrevive porque cualquier resultado puede interpretarse como aprendizaje o éxito.","Una hipótesis útil corre otro riesgo: podría resultar falsa. Define población, intervención, mecanismo, resultado, horizonte, salvaguardas y evidencia que obligaría a detener o reformular. También distingue lo que se espera observar de lo que sólo se desea.","El equipo separa tres hipótesis. Una sobre información disponible al asignar, otra sobre reglas de prioridad y otra sobre comunicación. Diseña pruebas diferentes y limita exposición. La automatización deja de ser la solución a validar y pasa a ser una opción entre varias.","Refutar no significa fracasar. Significa evitar inversión, daño o dependencia cuando el mecanismo no se sostiene. La organización aprende algo decisivo sólo si estaba dispuesta a cambiar de curso.","N22 recibe de HH-21 objetos y responsabilidades. Su avance consiste en convertir iniciativas en afirmaciones discutibles y decisiones con umbrales previos."],
 hotel="HH-22 toma la capacidad de ingreso y formula hipótesis separadas para información, reglas y coordinación. Cada ficha declara outcome, población, mecanismo, baseline, señal adversa, costo de exposición, autoridad y próxima decisión. La iniciativa ya no puede apropiarse de cualquier mejora ni esconder una pérdida en el promedio.",
 advance="N22 convierte iniciativas en hipótesis refutables mediante mecanismos, baselines, resultados, salvaguardas, umbrales y decisiones predefinidas.",
 defer="N23 recibirá apuestas explícitas y decidirá cómo cortarlas en capacidades que produzcan valor y aprendizaje. N22 no diseña todavía la secuencia de entrega.",
 units=[
  u("Hipótesis de iniciativa","Una hipótesis de iniciativa afirma que una intervención producirá un outcome mediante un mecanismo bajo condiciones explícitas.","No es objetivo, deseo, pronóstico ni justificación retrospectiva.","Vincula acción, población, causalidad esperada y decisión futura.","Se fortalece con observaciones que discriminan entre mecanismos rivales.","Usar estado de cerradura reducirá reasignaciones sólo si el dato llega a tiempo.","Debe poder resultar falsa sin que el equipo cambie su significado."),
  u("Outcome","Un outcome es un cambio significativo en conducta, capacidad o condición de actores concretos.","No equivale a output, actividad, adopción ni satisfacción aislada.","Aparece cuando una capacidad cambia lo que alguien puede lograr y sus consecuencias.","Necesita baseline, ventana temporal, población y señales de distribución.","Reducir espera sin aumentar exclusión es outcome; desplegar el motor no lo es.","Puede mejorar por factores ajenos y requiere prudencia causal."),
  u("Mecanismo","Un mecanismo explica cómo la intervención podría producir el outcome esperado.","No es una correlación ni una historia plausible agregada después.","Identifica condiciones intermedias, decisiones y respuestas que deben ocurrir.","Se prueba mediante señales tempranas y casos donde el eslabón falla.","Más información sólo ayuda si cambia una decisión a tiempo.","Un mecanismo verdadero en promedio puede fallar en excepciones críticas."),
  u("Refutabilidad práctica","Refutabilidad práctica es la posibilidad real de observar evidencia que obligue a revisar o abandonar la apuesta.","No exige un experimento perfecto ni convierte toda gestión en ciencia de laboratorio.","Define por anticipado qué resultado contradice la explicación y quién puede actuar.","Un registro de umbrales, anomalías y decisiones impide mover el arco después.","Si suben reasignaciones accesibles, el piloto se detiene aunque baje el promedio.","Obligaciones y daños irreversibles pueden impedir experimentar."),
  u("Baseline","Una baseline describe el estado de comparación antes de intervenir, con sus variaciones y limitaciones.","No es un único promedio histórico ni una meta.","Permite atribuir cambio, reconocer estacionalidad y detectar regresiones.","Se construye con episodios comparables, calidad de datos y segmentación.","El ingreso se mide por turno, canal y necesidad accesible antes del piloto.","Una baseline inestable necesita diseño adicional, no falsa precisión."),
  u("Hipótesis rival","Una hipótesis rival ofrece otra explicación capaz de producir las mismas señales observadas.","No es objeción genérica ni postura política sin mecanismo.","Fuerza pruebas discriminantes y reduce confirmación selectiva.","Gana fuerza cuando predice casos que la explicación principal no anticipa.","La demora puede provenir de autoridad y no de falta de información.","No todas las alternativas merecen igual esfuerzo; se priorizan por plausibilidad y consecuencia."),
  u("Resultado y métrica","Una métrica operacionaliza una parte del resultado para observar cambio y decisión.","No es el outcome mismo ni una verdad neutral.","Selecciona población, unidad, ventana y agregación, y por eso crea visibilidad y ceguera.","Se audita con validez, sensibilidad, latencia y posibilidad de manipulación.","Tiempo promedio se acompaña con percentiles, excepciones y reparación.","Optimizar la cifra puede deteriorar aquello que pretendía representar."),
  u("Umbral de decisión","Un umbral define qué evidencia habilita continuar, adaptar, ampliar o detener.","No es una meta aspiracional ni un semáforo sin autoridad.","Reduce negociación retrospectiva y conecta medida con compromiso.","Debe fijarse antes, incluir incertidumbre y admitir señales de seguridad dominantes.","La ampliación exige reducción sostenida y cero pérdida crítica accesible.","Un umbral arbitrario puede producir falsa certeza."),
  u("Salvaguarda","Una salvaguarda limita exposición y preserva reparación durante el aprendizaje.","No reemplaza consentimiento, obligación ni diseño responsable.","Define población, duración, fallback, monitoreo y escalamiento.","Se prueba mediante escenarios adversos y tiempo real de recuperación.","Recepción puede anular la asignación y volver al circuito anterior.","Si la reparación llega después del daño irreversible, no es suficiente."),
  u("Experimento natural y piloto","Un piloto es una intervención limitada para aprender sobre operación y resultado en condiciones reales.","No es lanzamiento pequeño ni demostración comercial.","Combina hipótesis, selección, comparación y protección sin exigir control total.","La evidencia incluye fidelidad de ejecución, contexto y efectos laterales.","Dos turnos comparables prueban reglas con supervisión disponible.","La selección puede sesgar resultados y limitar generalización."),
  u("Aprendizaje decisional","Aprendizaje decisional es información que cambia una elección, un límite o un compromiso.","No es acumular datos, opiniones o retrospectivas.","Se produce cuando una observación actualiza una hipótesis y altera la siguiente acción.","Se documenta con decisión anterior, evidencia nueva y diferencia concreta.","El hotel abandona automatización total y conserva apoyo a la decisión.","Una sorpresa sin consecuencia puede ser interesante y no útil."),
  u("Retiro de una apuesta","Retirar una apuesta significa detener inversión y exposición preservando conocimiento, obligaciones y salida.","No es ocultar un fracaso ni borrar el producto.","Cierra contratos, comunica, migra y conserva evidencia para futuras decisiones.","Se verifica con dependencias resueltas, personas protegidas y costo residual conocido.","El piloto se retira y las reglas validadas quedan disponibles para operación manual.","El costo hundido y la identidad del equipo pueden bloquear la decisión."),
 ],
 instrument_title="Instrumento HH-22: ficha de hipótesis y decisión",
 instrument_fields=["Iniciativa","Población","Outcome","Intervención","Mecanismo","Baseline","Hipótesis rival","Métricas","Umbrales","Salvaguardas","Autoridad","Decisión y fecha"],
 transfer_title="Caso de transferencia: alerta temprana de abandono",
 transfer=["Una facultad propone un modelo para anticipar abandono. La hipótesis no puede ser mejorar retención mediante inteligencia artificial. Debe explicar qué información llega a quién, qué apoyo se activa y por qué cambiaría la trayectoria.","La prueba distingue capacidad predictiva de capacidad institucional para intervenir y protege a estudiantes de etiquetado o trato desigual.","HH-22 vuelve visible que una buena predicción puede no producir el outcome y puede crear un daño nuevo."],
 counter_title="Contraejemplo: una hipótesis que no puede perder",
 counter=["Una iniciativa declara que cualquier aumento confirma valor y cualquier caída demuestra necesidad de más adopción.","No existe evidencia capaz de cambiarla. El lenguaje de hipótesis sólo protege una decisión tomada.","Una apuesta refutable incluye una salida incómoda pero practicable."],
 errors=["Confundir hipótesis con deseo","Elegir métricas después del resultado","Usar un promedio sin población","Omitir mecanismo","No formular rival","Llamar piloto a un lanzamiento","Aprender sin cambiar decisión","Mover umbrales","Experimentar con obligaciones","No preparar retiro"],
 referents=[["Karl Popper","Formuló la refutación como criterio de crítica del conocimiento."],["Donald Campbell","Estudió inferencia, validez y diseño cuasiexperimental."],["Eric Ries","Popularizó ciclos de construir, medir y aprender para reducir incertidumbre."],["Teresa Torres","Integra descubrimiento continuo, outcomes y oportunidades."],["Ron Kohavi","Desarrolló prácticas rigurosas de experimentación en productos digitales."],["NIST","Exige gobierno, medición y manejo de riesgos para sistemas de inteligencia artificial."]],
 references=["Popper, K. (1959). The Logic of Scientific Discovery. Hutchinson.","Campbell, D. T. y Stanley, J. C. (1963). Experimental and Quasi-Experimental Designs for Research. Houghton Mifflin.","Ries, E. (2011). The Lean Startup. Crown Business.","Torres, T. (2021). Continuous Discovery Habits. Product Talk.","Kohavi, R., Tang, D. y Xu, Y. (2020). Trustworthy Online Controlled Experiments. Cambridge University Press.","Shadish, W. R., Cook, T. D. y Campbell, D. T. (2002). Experimental and Quasi-Experimental Designs for Generalized Causal Inference. Houghton Mifflin.","OECD (2023). Recommendation on Improving Data Access and Sharing. https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0463","NIST (2023). Artificial Intelligence Risk Management Framework 1.0. https://doi.org/10.6028/NIST.AI.100-1","NIST (2024). Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile. https://doi.org/10.6028/NIST.AI.600-1","European Union (2024). Artificial Intelligence Act. https://eur-lex.europa.eu/eli/reg/2024/1689/oj","Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops","W3C (2023). Ethical Web Principles. https://www.w3.org/TR/ethical-web-principles/"]
),
23: doc(
 slug="capacidad_y_aprendizaje_cortar_entregas_por_outcome",
 title="Capacidad y aprendizaje: cortar entregas por outcome",
 question="¿Cómo dividir una iniciativa sin producir partes técnicas que sólo adquieren sentido cuando todo está terminado?",
 opening_title="Cinco componentes terminados y ninguna llegada posible",
 opening=["Hotel Horizonte divide la mejora del ingreso en interfaz, API, reglas, analítica y capacitación. Cada equipo entrega su componente según plan. La demostración mensual muestra avances y el tablero acumula porcentaje completado.","Cuando se intenta operar un caso real, ningún corte permite alojar a una persona de punta a punta. La interfaz consulta un estado viejo, la regla no contempla accesibilidad, la analítica no recibe excepciones y la capacitación describe una versión que todavía no existe. Hay outputs, pero no capacidad utilizable ni aprendizaje sobre el outcome.","Cortar por capacidad significa construir una fracción del sistema que permite a actores concretos lograr algo valioso bajo condiciones reales. Cortar por aprendizaje significa elegir la porción mínima que distingue una incertidumbre relevante. Ambos criterios atraviesan componentes y obligan a integrar temprano.","El equipo selecciona un episodio: llegada anticipada con habitación accesible. Une información, regla, decisión, comunicación y reparación en una versión limitada a un turno. No cubre todo el mercado, pero funciona de punta a punta y prueba el supuesto más riesgoso.","El corte deja de ser una técnica de backlog. Se convierte en una decisión sobre valor, riesgo, integración y quién queda fuera de la primera versión.","N23 recibe hipótesis de HH-22 y las transforma en incrementos que producen evidencia y capacidad, sin esconder integración ni postergar el servicio real."],
 hotel="HH-23 organiza slices verticales por episodios: ingreso ordinario, llegada anticipada, accesibilidad y sobreventa. Cada uno reúne personas, reglas, datos, tecnología, comunicación y reparación. El primer corte no es el más fácil técnicamente, sino el que prueba una hipótesis crítica con exposición limitada.",
 advance="N23 corta entregas por capacidad y aprendizaje, conecta slices verticales con outcomes y hace explícitos integración, población, riesgo y condición de expansión.",
 defer="N24 recibirá un conjunto de capacidades posibles y decidirá cuáles no hacer, postergar o proteger. N23 no resuelve todavía la priorización entre apuestas.",
 units=[
  u("Capacidad","Una capacidad es la posibilidad sostenida de lograr un resultado bajo condiciones definidas.","No es componente, competencia individual, feature ni proceso aislado.","Integra personas, reglas, información, tecnología y autoridad en uso.","Se prueba con un episodio completo, una excepción y una reparación.","Recepción asigna, comunica y corrige una llegada anticipada.","Puede existir localmente y fallar al cambiar turno, volumen o población."),
  u("Slice vertical","Un slice vertical es un corte mínimo que atraviesa las capas necesarias para producir capacidad observable.","No es una tarea técnica pequeña ni una épica dividida por arquitectura.","Fuerza integración temprana y reduce el tiempo hasta la evidencia.","Se valida mediante uso de punta a punta y dependencias reales.","Una regla simple con datos, interfaz, operación y fallback supera a cinco módulos incompletos.","Un slice puede ser demasiado estrecho si evita la incertidumbre central."),
  u("Corte por aprendizaje","Un corte por aprendizaje maximiza información útil para una decisión con exposición limitada.","No busca producir una demo ni seleccionar lo más rápido.","Elige una prueba discriminante sobre el supuesto de mayor riesgo o valor.","Se mide por hipótesis actualizada y decisión habilitada.","Probar accesibilidad revela semántica y autoridad antes de ampliar.","Aprender sin capacidad de actuar puede postergar valor y agotar confianza."),
  u("Corte por outcome","Un corte por outcome reúne lo necesario para cambiar una condición relevante en una población definida.","No significa resolver todo el journey ni prometer impacto final con un piloto.","Conecta capacidad, uso y consecuencia sin esperar el conjunto completo.","Baseline, población y resultado permiten observar contribución.","Un turno reduce espera y conserva protección, aunque otros canales sigan fuera.","El outcome parcial no debe presentarse como resultado universal."),
  u("Integración temprana","Integración temprana confronta contratos, datos y prácticas antes de que el costo de cambio se acumule.","No es desplegar constantemente ni fusionar código sin criterio.","Expone incompatibilidades semánticas, temporales y operativas dentro de cada corte.","Pruebas end-to-end, observabilidad y operación conjunta sostienen la evidencia.","La definición de liberada falla en el primer slice y no al final.","Integrar sin protección puede llevar inestabilidad a producción."),
  u("Walking skeleton","Un walking skeleton es una trayectoria mínima ejecutable que conecta las partes esenciales del sistema.","No es arquitectura definitiva ni producto mínimo valioso por sí mismo.","Permite validar flujo técnico y operacional antes de enriquecer comportamiento.","Se prueba con trazabilidad completa, recuperación y una decisión real.","Un caso de ingreso atraviesa canal, PMS, cerradura y confirmación.","Puede crear falsa confianza si sólo recorre el camino feliz."),
  u("Producto mínimo viable","Un producto mínimo viable es un dispositivo para probar una hipótesis de valor y uso con el menor compromiso defendible.","No es una versión pobre, incompleta o de baja calidad.","Combina propuesta, población y medición para aprender antes de escalar.","Debe producir evidencia sobre conducta y outcome, no sólo aceptación verbal.","Una modalidad manual asistida prueba coordinación antes de automatizar.","En contextos críticos, mínimo no puede significar sin seguridad o accesibilidad."),
  u("Feature flag y exposición","Una feature flag separa despliegue técnico de disponibilidad para poblaciones concretas.","No reemplaza diseño experimental, autorización ni rollback operacional.","Permite graduar exposición, comparar y retirar sin nueva instalación.","Se audita con configuración, ownership, deuda y efectos entre versiones.","La regla se habilita sólo en un turno con soporte disponible.","Flags permanentes multiplican estados y complejidad."),
  u("Definición de terminado orientada a capacidad","Terminado significa que el corte puede usarse, observarse, sostenerse y repararse en su alcance.","No equivale a código completo, revisión aprobada ni demo exitosa.","Incluye operación, seguridad, accesibilidad, datos, soporte y aprendizaje.","Escenarios ordinarios y adversos verifican el conjunto.","El equipo de turno resuelve una excepción con evidencia trazable.","El criterio debe ser proporcional y no convertir toda prueba en lanzamiento total."),
  u("Deuda de integración","Deuda de integración es el trabajo y riesgo diferidos al separar componentes que deberán funcionar juntos.","No es sólo deuda técnica ni defecto de interfaz.","Crece con contratos implícitos, ambientes divergentes y validación tardía.","Se observa en retrabajo, tiempo de estabilización y fallas entre equipos.","Cinco componentes verdes producen un journey rojo.","Alguna separación es necesaria; debe registrarse y pagarse deliberadamente."),
  u("Secuencia de slices","La secuencia ordena cortes por aprendizaje, valor, dependencia y protección.","No es simplemente prioridad de backlog ni recorrido de menor esfuerzo.","Cada slice modifica lo que se sabe y habilita el siguiente compromiso.","Se justifica con riesgo, outcome, capacidad disponible y costo de demora.","Accesibilidad precede a volumen porque su daño es más difícil de reparar.","Una secuencia óptima local puede bloquear una plataforma compartida."),
  u("Expansión","Expandir es aumentar población, volumen o compromiso después de demostrar capacidad en el alcance anterior.","No es copiar el piloto ni asumir proporcionalidad.","Revalida operación, arquitectura, soporte y efectos distributivos en nueva escala.","Señales de carga, variación, incidentes y autonomía muestran si el mecanismo resiste.","El slice pasa de un turno a todos con contingencia reforzada.","Lo que funciona en baja escala puede cambiar incentivos y colas."),
 ],
 instrument_title="Instrumento HH-23: mapa de cortes por capacidad",
 instrument_fields=["Outcome","Población","Hipótesis","Capacidad mínima","Episodio end-to-end","Capas involucradas","Excepciones","Evidencia","Definición de terminado","Exposición","Dependencias","Próximo corte"],
 transfer_title="Caso de transferencia: devolución de una compra",
 transfer=["Un comercio no divide por front end, pagos y logística. El primer slice permite solicitar, autorizar, devolver y recibir reintegro para un tipo de compra.","La capacidad limitada revela excepciones, tiempos y responsabilidad antes de ampliar productos y canales.","HH-23 muestra que reducir alcance no exige romper el outcome en piezas sin uso."],
 counter_title="Contraejemplo: vertical sólo en el diagrama",
 counter=["Un equipo llama vertical a un corte que atraviesa capas de código pero omite soporte, política y reparación.","La demo funciona y el caso real vuelve al procedimiento manual sin registro.","La verticalidad se prueba en la capacidad sociotécnica, no en la arquitectura de software."],
 errors=["Cortar por componentes","Elegir lo más fácil","Llamar MVP a baja calidad","Omitir excepciones","Postergar integración","Confundir despliegue con exposición","Medir avance por tareas","Dejar operación fuera de terminado","Acumular flags","Escalar sin revalidar"],
 referents=[["Tom Gilb","Desarrolló entrega evolutiva y medición de valor."],["Jeff Patton","Popularizó story mapping y cortes orientados al recorrido."],["Mary y Tom Poppendieck","Aplicaron principios lean al desarrollo de software."],["Jez Humble","Vinculó entrega continua, riesgo e integración temprana."],["Nicole Forsgren","Aportó evidencia sobre desempeño de entrega y organización."],["Alistair Cockburn","Formuló el walking skeleton como estrategia de integración."]],
 references=["Gilb, T. (1988). Principles of Software Engineering Management. Addison-Wesley.","Patton, J. (2014). User Story Mapping. O'Reilly.","Poppendieck, M. y Poppendieck, T. (2003). Lean Software Development. Addison-Wesley.","Humble, J. y Farley, D. (2010). Continuous Delivery. Addison-Wesley.","Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.","Cockburn, A. (2004). Crystal Clear. Addison-Wesley.","Ries, E. (2011). The Lean Startup. Crown Business.","Project Management Institute (2021). A Guide to the Project Management Body of Knowledge, Seventh Edition. PMI.","Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops","Google Cloud (2025). DORA State of AI-Assisted Software Development. https://cloud.google.com/devops/state-of-devops","NIST (2022). Secure Software Development Framework 1.1. https://doi.org/10.6028/NIST.SP.800-218","W3C (2023). Web Content Accessibility Guidelines 2.2. https://www.w3.org/TR/WCAG22/"]
),
24: doc(
 slug="priorizar_es_renunciar_valor_costo_de_demora_y_limites",
 title="Priorizar es renunciar: valor, costo de demora y límites",
 question="¿Cómo decidir qué no hacer cuando todas las iniciativas pueden narrarse como valiosas y cada demora distribuye consecuencias distintas?",
 opening_title="La lista donde todo era prioridad uno",
 opening=["Hotel Horizonte reúne diecisiete pedidos para el próximo trimestre. Cada área marca el suyo como crítico: campaña, cerraduras, reportes, accesibilidad, conciliación, aplicación y automatización. La matriz asigna puntajes y termina con doce iniciativas casi empatadas.","El problema no es falta de fórmula. Nadie declaró qué resultado prevalece, qué obligación limita la comparación, quién absorbe la demora ni qué capacidad se libera al decir no. El ranking vuelve numérico un desacuerdo que sigue intacto.","Priorizar es renunciar de manera explícita y revisable. Significa asignar recursos escasos a una opción y aceptar las consecuencias de postergar, reducir o retirar otras. Valor no es una propiedad intrínseca; depende de población, momento, mecanismo, riesgo y estrategia.","El equipo separa obligaciones de apuestas, calcula costo de demora por escenario, identifica dependencias y limita trabajo en curso. Accesibilidad no compite como feature opcional. La campaña espera porque amplificaría una promesa frágil. Una mejora pequeña de conciliación avanza porque libera capacidad operativa para el resto.","La decisión se vuelve defendible cuando nombra beneficiarios, perjudicados, oportunidad perdida, incertidumbre y fecha de revisión. El backlog deja de ser depósito infinito.","N24 recibe slices de HH-23 y enseña a elegir entre ellos sin esconder renuncias detrás de urgencia, puntaje o autoridad jerárquica."],
 hotel="HH-24 clasifica opciones por obligación, protección, outcome, aprendizaje y habilitación. Para cada una registra costo de demora, capacidad consumida, dependencia, reversibilidad y población afectada. La cartera limita iniciativas activas y conserva una lista explícita de no ahora, no así y no hacer.",
 advance="N24 entiende la priorización como renuncia explícita y revisable, articulando valor situado, costo de demora, capacidad, obligaciones, dependencia y distribución de consecuencias.",
 defer="N25 recibirá una cartera limitada y estudiará cómo fluye realmente el trabajo. N24 no optimiza todavía colas, lote ni feedback en ejecución.",
 units=[
  u("Prioridad","Prioridad es una relación de precedencia entre opciones bajo recursos, objetivos y límites concretos.","No es importancia absoluta, urgencia declarada ni posición fija en una lista.","Ordena compromisos cuando hacer una opción posterga o impide otra.","Se sostiene con criterio, capacidad, consecuencia y fecha de revisión.","Accesibilidad precede a campaña aunque ambas produzcan valor.","Una prioridad sin renuncia simultánea no gobierna trabajo."),
  u("Renuncia explícita","Renunciar es decidir no hacer, no ahora o no de esa manera y asumir sus efectos.","No equivale a olvidar, rechazar para siempre ni esconder trabajo en un backlog.","Libera capacidad y vuelve visible el costo de oportunidad.","Se documenta con opción postergada, consecuencia, responsable y disparador de revisión.","La campaña se posterga hasta estabilizar la promesa.","La renuncia puede ser injusta si quienes absorben el costo no participan."),
  u("Valor situado","Valor es una mejora relevante para actores y estrategia bajo condiciones determinadas.","No es ingreso, satisfacción, utilización ni preferencia del solicitante por separado.","Combina outcome, población, horizonte, costo, riesgo y capacidades futuras.","Evidencia de uso, consecuencia y sostenibilidad fortalece la valoración.","Reducir trabajo nocturno libera capacidad y mejora experiencia.","Los valores son plurales y pueden entrar en conflicto."),
  u("Costo de oportunidad","Costo de oportunidad es el valor de la mejor alternativa a la que se renuncia al elegir.","No es sólo costo contable ni presupuesto consumido.","Hace visible que recursos dedicados a una iniciativa no están disponibles para otra.","Escenarios comparables y capacidad real permiten estimarlo.","Un equipo ocupado en personalización no corrige una falla de accesibilidad.","No todo costo puede monetizarse sin perder significado."),
  u("Costo de demora","Costo de demora expresa cómo cambia una consecuencia valiosa o dañina mientras una opción espera.","No es urgencia subjetiva ni una cifra universal por semana.","Relaciona tiempo, población, ventana, riesgo y pérdida acumulada.","Se estima con escenarios, curvas y evidencia histórica.","Demorar una protección antes de temporada alta cuesta distinto que después.","La falsa precisión puede manipular el ranking."),
  u("Clases de servicio","Una clase de servicio define políticas de selección y tratamiento para tipos de demanda.","No es una etiqueta VIP ni un atajo para saltar la cola.","Distingue obligación fija, urgencia, fecha, estándar y exploración mediante reglas explícitas.","Se audita por frecuencia, impacto en el resto y cumplimiento de condiciones.","Un incidente de seguridad desplaza trabajo con criterio de reposición.","Demasiadas excepciones destruyen la política y normalizan urgencia."),
  u("Obligación como límite","Una obligación establece una condición que no puede tratarse como preferencia intercambiable.","No significa que toda interpretación normativa sea indiscutible.","Separa el espacio de elección de aquello que debe protegerse.","Fuente, alcance, autoridad y evidencia de cumplimiento fundamentan el límite.","Accesibilidad no compite por puntos con una campaña.","Invocar obligación sin interpretación puede bloquear alternativas legítimas."),
  u("Dependencia habilitante","Una dependencia habilitante es una capacidad cuyo avance permite o reduce el costo de varias opciones posteriores.","No toda tarea técnica es habilitante ni merece prioridad automática.","Cambia la estructura de opciones y puede reducir colas futuras.","Se prueba mostrando qué decisiones o outcomes desbloquea.","Un contrato semántico común habilita canales y reportes.","Las plataformas pueden usar su centralidad para capturar capacidad sin outcome."),
  u("Capacidad disponible","Capacidad disponible es el trabajo sostenible que un sistema puede absorber sin degradar flujo y operación.","No coincide con horas contratadas ni utilización máxima.","Incluye atención, coordinación, especialidad, soporte y variabilidad.","Throughput estable, colas y carga operacional revelan el límite.","El mismo equipo atiende incidentes y cambios, por lo que no dispone del cien por ciento.","Reducir holgura puede bajar capacidad efectiva."),
  u("Límite de trabajo en curso","Un límite de trabajo en curso restringe cuántas iniciativas pueden estar activas simultáneamente.","No es austeridad ni prohibición permanente.","Concentra capacidad, acorta espera y hace visible la necesidad de terminar o detener.","Se observa en edad del trabajo, throughput y bloqueos.","El hotel activa cuatro apuestas y no diecisiete.","Un límite rígido sin clase de servicio puede impedir respuesta crítica."),
  u("Gobernanza de cartera","Gobernar cartera es revisar opciones, compromisos y renuncias como sistema interdependiente.","No es una reunión de ranking ni suma de casos de negocio.","Alinea estrategia, outcomes, capacidades y riesgo en ciclos de decisión.","Señales de avance, cambio de contexto y costo hundido permiten reasignar.","Una apuesta se detiene para proteger otra que mostró más aprendizaje.","La autoridad central puede ignorar conocimiento local."),
  u("Fecha de revisión","Una fecha de revisión evita convertir la prioridad actual en verdad permanente.","No es fecha de entrega ni recordatorio administrativo.","Obliga a contrastar supuestos, outcomes y renuncias con evidencia nueva.","El registro muestra qué cambió y por qué se sostiene o revierte el orden.","La campaña vuelve a evaluarse después del pico y la estabilización.","Revisar demasiado seguido puede producir volatilidad y costo de cambio."),
 ],
 instrument_title="Instrumento HH-24: expediente de prioridad y renuncia",
 instrument_fields=["Outcome","Población","Opción","Alternativa renunciada","Obligación","Costo de oportunidad","Costo de demora","Capacidad","Dependencias","Clase de servicio","Decisión","Revisión"],
 transfer_title="Caso de transferencia: mantenimiento hospitalario",
 transfer=["Un hospital debe elegir entre mejorar una interfaz, reemplazar equipos, reforzar ciberseguridad y reducir demoras clínicas.","Una matriz única no puede hacer competir del mismo modo obligación, seguridad, outcome y aprendizaje. HH-24 separa límites y luego compara dentro del espacio legítimo.","La renuncia queda asociada a consecuencias y autoridad, no escondida en un puntaje."],
 counter_title="Contraejemplo: WSJF como oráculo",
 counter=["Un portafolio calcula un cociente, ordena iniciativas y presenta el ranking como decisión objetiva.","Los valores mezclan escalas, las obligaciones reciben puntos y nadie puede reconstruir quién definió el costo de demora.","La fórmula puede estructurar conversación, pero no sustituye juicio, evidencia ni límites."],
 errors=["Llamar urgente a todo","Priorizar sin decir no","Comparar obligación con preferencia","Monetizar daños incomparables","Usar puntajes opacos","Ignorar capacidad operacional","Premiar utilización máxima","Aceptar expedites permanentes","Proteger costo hundido","No revisar renuncias"],
 referents=[["Don Reinertsen","Desarrolló economía del flujo y costo de demora."],["Eliyahu Goldratt","Mostró cómo las restricciones organizan desempeño sistémico."],["John Little","Formalizó la relación entre trabajo en curso, throughput y tiempo."],["David Anderson","Aplicó políticas explícitas y clases de servicio al trabajo de conocimiento."],["Mik Kersten","Conectó portafolio, producto y flujo de valor."],["Project Management Institute","Integra valor, portafolio y adaptación de decisiones."]],
 references=["Reinertsen, D. G. (2009). The Principles of Product Development Flow. Celeritas.","Goldratt, E. M. y Cox, J. (1984). The Goal. North River Press.","Little, J. D. C. (1961). ‘A Proof for the Queuing Formula L = λW’. Operations Research, 9(3), 383–387. https://doi.org/10.1287/opre.9.3.383","Anderson, D. J. (2010). Kanban. Blue Hole Press.","Kersten, M. (2018). Project to Product. IT Revolution.","Project Management Institute (2017). The Standard for Portfolio Management, Fourth Edition. PMI.","Project Management Institute (2021). A Guide to the Project Management Body of Knowledge, Seventh Edition. PMI.","Kanban Guides (2025). The Kanban Guide. https://kanbanguides.org/english/","Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops","ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html","OECD (2024). Recommendation on Human-Centred Public Administrative Services. https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0503","European Union (2024). Artificial Intelligence Act. https://eur-lex.europa.eu/eli/reg/2024/1689/oj"]
),
25: doc(
 slug="flujo_mas_alla_de_las_ceremonias_colas_lote_espera_y_feedback",
 title="Flujo más allá de las ceremonias: colas, lote, espera y feedback",
 question="¿Cómo mejorar un sistema de trabajo cuando todas las ceremonias ocurren y, sin embargo, las decisiones y el valor siguen esperando?",
 opening_title="El sprint que duraba dos semanas y el cambio que tardaba cuatro meses",
 opening=["Hotel Horizonte trabaja en sprints de dos semanas. Las reuniones comienzan a horario, el tablero se actualiza y la velocidad es estable. Una corrección sobre asignación accesible tarda ciento dieciocho días desde el primer episodio hasta su uso en todos los turnos.","La mayor parte del tiempo no contiene trabajo activo. El pedido espera validación, el análisis espera datos, el cambio espera ambiente, la prueba espera agenda y la liberación espera comité. Cada área parece ocupada; el sistema completo acumula colas.","Flujo describe el movimiento de una unidad de valor desde demanda hasta resultado y feedback. Para comprenderlo hay que observar trabajo en curso, edad, espera, lote, handoffs, bloqueos, retrabajo y capacidad de reparación. La cadencia de ceremonias puede ayudar, pero no garantiza flujo.","El equipo limita iniciativas, reduce tamaños de lote, acerca prueba y operación, define políticas de entrada y mide tiempo de punta a punta. La velocidad local baja mientras el tiempo total mejora. También aparece una verdad incómoda: algunos controles aportaban protección y no podían simplemente eliminarse.","Optimizar flujo no significa acelerar todo. Significa diseñar movimiento sostenible, hacer visibles colas y elegir dónde la espera protege, dónde destruye valor y quién soporta cada demora.","N25 cierra el Bloque E. Recibe una cartera priorizada y la convierte en un sistema de trabajo observable que entrega, aprende y repara más allá de sus ceremonias."],
 hotel="HH-25 sigue cada slice desde la demanda hasta el outcome. Distingue tiempo activo y espera, mide edad, limita trabajo en curso, reduce lote e integra feedback operacional. Las políticas reservan capacidad para incidentes y obligaciones sin permitir que toda urgencia salte la cola.",
 advance="N25 estudia flujo de punta a punta mediante colas, trabajo en curso, lote, espera, handoffs, feedback y reparación, y separa desempeño sistémico de actividad local o cumplimiento ceremonial.",
 defer="N26 abrirá el Bloque F y ampliará la arquitectura hacia un ecosistema de servicios, plataformas y terceros. N25 entrega un flujo gobernado sin diseñar todavía esa arquitectura.",
 units=[
  u("Flujo de valor","Flujo de valor es el movimiento de una necesidad hasta una capacidad usada, observada y reparable.","No es el movimiento de tickets ni la suma de actividades internas.","Conecta demanda, decisión, construcción, operación y feedback de punta a punta.","Tiempo, outcome, calidad y distribución permiten juzgarlo.","Una corrección termina cuando el turno la usa y puede resolver una excepción.","El valor puede ser plural y no siempre fluye por una única secuencia."),
  u("Trabajo en curso","Trabajo en curso reúne unidades iniciadas que todavía no producen su resultado o cierre.","No equivale a backlog, inventario de ideas ni utilización.","Cada unidad consume atención, crea coordinación y alarga las colas del sistema.","Conteo, edad y bloqueos muestran su carga real.","Diecisiete iniciativas abiertas dispersan a los mismos especialistas.","Algún trabajo paralelo protege opciones y necesita límite situado."),
  u("Cola","Una cola es demanda que espera capacidad o una decisión antes de avanzar.","No sólo existe donde hay una lista visible.","Aparece ante especialidades, aprobaciones, ambientes, información o autoridad escasas.","Longitud, edad, variabilidad y disciplina de selección la hacen observable.","Cambios esperan al único comité aunque los equipos estén activos.","Eliminar una cola puede trasladarla a personas menos visibles."),
  u("Tiempo de flujo","Tiempo de flujo es el lapso desde que una unidad entra al sistema hasta que alcanza su condición de salida.","No es esfuerzo, duración de sprint ni tiempo técnico de ciclo aislado.","Incluye espera, trabajo, retrabajo y coordinación.","Timestamps coherentes y definición estable permiten medir percentiles y dispersión.","El cambio usa ocho horas de trabajo y espera ciento diez días.","El inicio elegido modifica la cifra y debe corresponder a la pregunta."),
  u("Ley de Little","La Ley de Little relaciona trabajo en curso, throughput y tiempo medio en un sistema estable.","No es una promesa causal ni una fórmula que ignore variabilidad.","Muestra que sostener más trabajo abierto con throughput similar alarga el tiempo.","Se usa con fronteras y unidades consistentes durante un período representativo.","Reducir iniciativas activas acorta espera sin aumentar horas.","Sistemas inestables o poblaciones mezcladas requieren interpretación prudente."),
  u("Tamaño de lote","Tamaño de lote es la cantidad de cambio acumulada antes de pasar a la etapa siguiente.","No es sólo cantidad de código o frecuencia de despliegue.","Lotes pequeños acortan feedback, reducen riesgo e integración, pero aumentan algunos costos de coordinación.","Se observa tiempo, fallas, costo de transacción y capacidad de recuperación.","Una regla se prueba por episodio en vez de esperar el paquete trimestral.","Lotes demasiado pequeños pueden fragmentar outcome o saturar revisión."),
  u("Handoff","Un handoff transfiere trabajo, información o responsabilidad entre actores o contextos.","No es toda colaboración ni necesariamente un defecto.","Introduce traducción, espera y riesgo de pérdida cuando las fronteras no son explícitas.","Retrabajo, aclaraciones y decisiones devueltas revelan su costo.","Análisis entrega una especificación sin la excepción que Operaciones conocía.","Algunas separaciones protegen independencia o control y deben diseñarse."),
  u("Feedback","Feedback es información sobre el efecto de una acción que puede modificar una decisión posterior.","No es reunión, comentario, métrica ni encuesta por sí sola.","Necesita señal relevante, baja latencia, audiencia y autoridad para actuar.","Se evalúa por decisiones cambiadas y tiempo hasta la corrección.","Un incidente llega al equipo antes de ampliar la regla.","Más señal sin capacidad de respuesta crea ruido y fatiga."),
  u("Variabilidad","Variabilidad son diferencias en llegada, tamaño, dificultad o capacidad que alteran el comportamiento del flujo.","No equivale a desorden ni puede eliminarse completamente.","Aumenta espera cuando el sistema opera cerca de saturación.","Distribuciones, percentiles y escenarios distinguen patrones de promedios.","Los picos de check-in vuelven crítica una cola invisible en días normales.","La holgura necesaria puede parecer ineficiencia local."),
  u("Throughput","Throughput es la cantidad de unidades que alcanzan salida en un período.","No es productividad individual ni puntos completados.","Refleja capacidad del sistema y definición de unidad.","Se interpreta junto con calidad, demanda, trabajo en curso y outcome.","El hotel cuenta episodios resueltos, no tareas técnicas cerradas.","Aumentarlo mediante unidades triviales o defectuosas destruye sentido."),
  u("Eficiencia de flujo","Eficiencia de flujo compara tiempo activo con tiempo total para localizar espera, no para exigir actividad continua.","No es utilización de personas ni objetivo universal de cien por ciento.","Revela dónde el sistema deja inmóvil una unidad mientras protege ocupación local.","Muestreo de episodios y causas de espera orienta decisiones.","La corrección trabaja un día y espera cuatro meses.","Alguna espera agrega control, aprendizaje o seguridad."),
  u("Sistema de feedback y reparación","Un sistema de feedback y reparación detecta desvíos, decide respuesta y restaura capacidad con aprendizaje.","No es sólo observabilidad técnica ni retrospectiva.","Conecta señales de operación, usuarios, negocio y riesgo con autoridad y acción.","Tiempo de detección, recuperación y prevención muestran su funcionamiento.","Recepción reporta una excepción y la regla se corrige antes del siguiente lote.","Automatizar feedback sin juicio puede amplificar ruido o sesgo."),
 ],
 instrument_title="Instrumento HH-25: mapa de flujo real",
 instrument_fields=["Unidad de valor","Inicio y salida","Demanda","Trabajo en curso","Colas","Tiempo activo","Espera","Lote","Handoffs","Feedback","Políticas","Reparación"],
 transfer_title="Caso de transferencia: alta de proveedor",
 transfer=["Una empresa completa formularios en dos días, pero tarda noventa en habilitar un proveedor. Compras, legales, seguridad y finanzas optimizan sus tareas mientras el expediente espera.","HH-25 sigue una unidad completa, distingue controles necesarios de esperas accidentales y reduce lote sin borrar obligaciones.","La mejora sistémica puede reducir utilización local y aumentar capacidad efectiva."],
 counter_title="Contraejemplo: acelerar eliminando todos los controles",
 counter=["Un equipo elimina revisiones para reducir tiempo de ciclo y duplica despliegues.","Las fallas llegan antes a operación, crece el retrabajo y el tiempo hasta outcome empeora.","Fluir no es omitir protección. Es integrar la protección con el menor lote y feedback útil."],
 errors=["Medir velocidad como outcome","Optimizar un área","Maximizar utilización","Ignorar trabajo invisible","Confundir actividad con flujo","Reducir lote sin capacidad completa","Eliminar esperas protectoras","Aceptar urgencias sin política","Medir sólo promedios","Recibir feedback sin autoridad"],
 referents=[["John Little","Formalizó la relación entre inventario, throughput y tiempo."],["Wallace Hopp y Mark Spearman","Desarrollaron una ciencia de fábrica aplicable a variabilidad y flujo."],["Donald Reinertsen","Llevó economía de colas y lotes al desarrollo de producto."],["Taiichi Ohno","Construyó principios del sistema de producción Toyota."],["David Anderson","Aplicó gestión de flujo y políticas explícitas al trabajo de conocimiento."],["Nicole Forsgren","Aportó evidencia empírica sobre flujo, entrega y desempeño organizacional."]],
 references=["Little, J. D. C. (1961). ‘A Proof for the Queuing Formula L = λW’. Operations Research, 9(3), 383–387. https://doi.org/10.1287/opre.9.3.383","Hopp, W. J. y Spearman, M. L. (2011). Factory Physics, Third Edition. Waveland Press.","Reinertsen, D. G. (2009). The Principles of Product Development Flow. Celeritas.","Ohno, T. (1988). Toyota Production System. Productivity Press.","Anderson, D. J. (2010). Kanban. Blue Hole Press.","Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.","Kim, G. et al. (2021). The DevOps Handbook, Second Edition. IT Revolution.","Kanban Guides (2025). The Kanban Guide. https://kanbanguides.org/english/","Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops","Google Cloud (2025). DORA State of AI-Assisted Software Development. https://cloud.google.com/devops/state-of-devops","Project Management Institute (2021). A Guide to the Project Management Body of Knowledge, Seventh Edition. PMI.","ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html"]
),
}


base.REFERENCE_NOTES.update({
    "Program Management": "distingue coordinación temporal y capacidades sostenidas",
    "Inspired": "vincula producto con problemas, outcomes y aprendizaje",
    "Empowered": "relaciona ownership con autoridad y equipos responsables",
    "ITIL": "define servicio como cocreación de valor y capacidad sostenida",
    "20000-1": "establece requisitos para gobernar sistemas de gestión de servicios",
    "Platform Revolution": "explica efectos de red y decisiones de gobierno de plataformas",
    "Platform Ecosystems": "analiza arquitectura, interfaces y evolución de ecosistemas",
    "Project to Product": "conecta financiación, producto y flujo de valor",
    "Team Topologies": "relaciona formas de equipo con flujo y plataformas internas",
    "Accelerate": "aporta evidencia sobre capacidades de entrega y desempeño",
    "Logic of Scientific": "fundamenta crítica y refutación de afirmaciones",
    "Quasi-Experimental": "aporta criterios de inferencia y validez en contextos reales",
    "Lean Startup": "vincula hipótesis, exposición y aprendizaje decisional",
    "Continuous Discovery": "integra outcomes, oportunidades y aprendizaje continuo",
    "Controlled Experiments": "desarrolla prácticas para experimentos confiables",
    "Data Access": "sitúa acceso a datos dentro de gobierno y responsabilidad",
    "Ethical Web": "incorpora principios de diseño responsable y control de daño",
    "Principles of Software": "organiza entrega evolutiva y medición de valor",
    "User Story Mapping": "conecta cortes de entrega con recorridos y capacidades",
    "Lean Software": "traslada flujo, aprendizaje y reducción de desperdicio al software",
    "Continuous Delivery": "vincula integración, lotes pequeños y reducción de riesgo",
    "Crystal Clear": "aporta la noción de walking skeleton para integración temprana",
    "WCAG": "establece criterios verificables de accesibilidad digital",
    "Product Development Flow": "explica economía de colas, lotes y costo de demora",
    "The Goal": "muestra cómo una restricción gobierna el desempeño del sistema",
    "Queuing Formula": "formaliza la relación entre trabajo en curso, throughput y tiempo",
    "Kanban": "aporta límites, políticas y gestión evolutiva del flujo",
    "Portfolio Management": "ordena decisiones de cartera, valor y alineación",
    "Human-Centred": "orienta servicios públicos hacia necesidades y consecuencias humanas",
    "Factory Physics": "explica variabilidad, colas y comportamiento operacional",
    "Toyota Production": "fundamenta flujo, trabajo visible y aprendizaje en operación",
    "DevOps Handbook": "integra entrega, operación, feedback y mejora continua",
})


def main() -> None:
    original_docs = base.DOCS
    base.DOCS = DOCS
    try:
        for number, specification in DOCS.items():
            base.build(number, specification)
            package = base.ROOT / f"N{number:02d}-content-canonical"
            (package / "CHANGELOG.md").write_text(
                f"# N{number:02d} · Changelog\n\n"
                "- Creación del contenido canónico v1 para el Bloque E.\n"
                f"- Integración de HH-{number:02d}, Hotel Horizonte, instrumento, transferencia, límites y referencias ancladas.\n",
                encoding="utf-8",
            )
        print(json.dumps({f"N{number:02d}": len(base.render(specification, number).split()) for number, specification in DOCS.items()}, ensure_ascii=False))
    finally:
        base.DOCS = original_docs


if __name__ == "__main__":
    main()
