#!/usr/bin/env python3
"""Build canonical METSI Block F content packages, N26 through N30."""

from __future__ import annotations

import json

import build_block_d_content as base


def u(title, definition, distinction, mechanism, evidence, example, boundary):
    return [title, definition, distinction, mechanism, evidence, example, boundary]


def doc(*, slug, title, question, opening_title, opening, hotel, advance, defer,
        units, instrument_title, instrument_fields, transfer_title, transfer,
        counter_title, counter, errors, referents, references):
    result = base.compact_doc(
        slug=slug, title=title, question=question, opening_title=opening_title,
        opening=opening, hotel=hotel, advance=advance, defer=defer, units=units,
        instrument_title=instrument_title, instrument_fields=instrument_fields,
        transfer_title=transfer_title, transfer=transfer, counter_title=counter_title,
        counter=counter, errors=errors, referents=referents, references=references,
    )
    movement_titles = [
        "Movimiento 1 · Reconocer dependencias y promesas operativas",
        "Movimiento 2 · Construir evidencia y controles proporcionales",
        "Movimiento 3 · Gobernar cambio, degradación y aprendizaje",
    ]
    result["movements"] = [
        [movement_titles[index], units[index * 4:(index + 1) * 4]]
        for index in range(3)
    ]
    result["consequences"] = (
        advance
        + " El avance profesional consiste en sostener una promesa bajo condiciones reales, "
          "con autoridad, evidencia y reparación, no en declarar que la solución quedó disponible."
    )
    result["limits"] = (
        "Ninguna arquitectura, contrato, prueba, control ni tablero elimina el juicio situado. "
        "Las dependencias cambian, la evidencia llega con demora, la operación distribuye poder "
        "y una mejora local puede desplazar daño. El expediente debe conservar población afectada, "
        "supuestos, autoridad, degradación aceptable, reparación y fecha de revisión."
    )
    return result


DOCS = {
26: doc(
 slug="ecosistema_de_servicios_plataformas_y_terceros",
 title="Ecosistema de servicios, plataformas y terceros",
 question="¿Cómo gobernar una promesa cuando depende de servicios internos, plataformas compartidas y terceros que ninguna unidad controla por completo?",
 opening_title="La habitación estaba lista, pero el ecosistema no",
 opening=[
  "Hotel Horizonte recibe a una familia que reservó por un canal externo. La habitación está limpia, el pago figura aprobado y la cerradura responde. Sin embargo, Recepción no puede completar el ingreso porque el proveedor de identidad devuelve un estado distinto del que conserva el canal de reservas.",
  "Cada componente funciona dentro de su propio tablero. El canal confirma la venta, pagos confirma la autorización, identidad confirma la cuenta y el PMS confirma disponibilidad. La promesa falla en el vínculo entre esas certezas parciales. Nadie posee el recorrido completo ni puede reparar por sí solo todas sus dependencias.",
  "Una arquitectura de ecosistema no es un inventario ampliado. Explicita capacidades, participantes, fronteras de confianza, contratos, datos, incentivos, modos de degradación y rutas de salida. También distingue qué se comparte, qué permanece autónomo y quién responde cuando una dependencia externa altera la experiencia.",
  "El equipo reconstruye el episodio desde la reserva hasta la llave. Descubre una plataforma de identidad, cinco servicios internos, tres proveedores y dos decisiones manuales que nunca aparecieron en el diagrama técnico. El mapa incorpora responsables, criticidad, sustitución, evidencia y reparación.",
  "La intervención no busca controlar lo incontrolable. Busca diseñar opciones antes de la falla, acordar señales antes del incidente y evitar que la complejidad contractual se convierta en abandono para quien espera en el mostrador.",
  "N26 abre el Bloque F. Recibe de N25 una mirada sobre flujo y espera, y amplía la unidad de análisis hacia el conjunto de organizaciones, plataformas y servicios que sostienen la promesa en operación."
 ],
 hotel="HH-26 toma el recorrido de ingreso y construye un mapa de ecosistema. Cada dependencia queda vinculada con una capacidad, un responsable, un contrato, una frontera de confianza, una señal de salud, un modo de degradación y una alternativa de salida. El mapa muestra que el huésped experimenta una sola promesa aunque la organización distribuya su realización entre múltiples participantes.",
 advance="N26 amplía la arquitectura hacia un ecosistema de servicios, plataformas y terceros, y convierte dependencias invisibles en decisiones de ownership, confianza, resiliencia y salida.",
 defer="N27 utilizará este mapa para precisar contratos sintácticos, semánticos, temporales y operacionales. N26 no define todavía cada interfaz ni sus pruebas de conformidad.",
 units=[
  u("Ecosistema de servicio", "Un ecosistema de servicio reúne participantes autónomos que sostienen una promesa mediante capacidades, reglas e intercambios interdependientes.", "No es una lista de proveedores ni una arquitectura encerrada dentro de una organización.", "El valor emerge de coordinaciones que cruzan límites jurídicos, técnicos y operativos.", "Se observa en recorridos, dependencias, incentivos, fallas y mecanismos de reparación.", "Reserva, identidad, pago, disponibilidad y cerradura participan del mismo ingreso.", "El mapa simplifica y debe declarar qué participantes y efectos quedan fuera."),
  u("Capacidad de servicio", "Una capacidad de servicio combina personas, información, tecnología y autoridad para producir un resultado repetible.", "No equivale a una aplicación, endpoint, equipo ni función de organigrama.", "Agrupa recursos y decisiones alrededor de lo que debe poder hacerse bajo condiciones reales.", "Episodios ordinarios y adversos muestran si la capacidad existe más allá del camino feliz.", "Entregar una habitación asignable requiere más que confirmar inventario.", "Una capacidad puede depender de acuerdos que la unidad responsable no controla."),
  u("Plataforma compartida", "Una plataforma compartida ofrece capacidades gobernadas que otros equipos o actores utilizan para construir y operar servicios.", "No es infraestructura neutral ni una concentración automática de funciones.", "Reduce coordinación mediante interfaces, estándares, autoservicio y reglas de evolución.", "Adopción útil, tiempo de integración, confiabilidad y costo de salida revelan su desempeño.", "Identidad y pagos sirven a varios recorridos del hotel.", "Una plataforma puede acelerar a unos participantes y crear dependencia para otros."),
  u("Tercero crítico", "Un tercero crítico es un participante externo cuya falla o decisión puede comprometer una promesa material.", "No todo proveedor es crítico y criticidad no coincide con gasto contractual.", "La criticidad surge de concentración, sustituibilidad, tiempo de recuperación y alcance del impacto.", "Escenarios de indisponibilidad, datos incompletos y cambio unilateral permiten evaluarla.", "El canal de reservas es crítico cuando concentra demanda y excepciones.", "La clasificación cambia con el diseño y debe revisarse."),
  u("Ownership de capacidad", "Ownership de capacidad reúne autoridad persistente para priorizar, observar, coordinar y reparar una promesa.", "No es un contacto de escalamiento ni responsabilidad sin recursos.", "Conecta decisiones de producto, operación, arquitectura, seguridad y relación con terceros.", "Se verifica cuando alguien puede limitar exposición, acordar cambios y financiar recuperación.", "Ingreso conserva un owner aunque sus componentes pertenezcan a áreas distintas.", "Una sola persona no puede absorber obligaciones distribuidas ni reemplazar acuerdos formales."),
  u("Mapa de dependencias", "Un mapa de dependencias representa qué necesita cada capacidad, en qué secuencia y bajo qué supuestos.", "No es un diagrama estático de cajas y flechas.", "Vincula dependencias técnicas con datos, autoridad, contratos y trabajo humano.", "Trazas, entrevistas, incidentes y pruebas de conmutación contrastan el mapa.", "La llave depende de identidad, pago, estado de habitación y autorización local.", "La dependencia informal puede quedar oculta si sólo se inspecciona software."),
  u("Frontera de confianza", "Una frontera de confianza marca dónde cambian las garantías, la autoridad y la evidencia aceptada.", "No coincide necesariamente con red, empresa, nube ni componente.", "Obliga a declarar qué afirmaciones se reciben, cómo se verifican y qué ocurre ante contradicción.", "Controles de acceso, procedencia, reconciliación y auditoría muestran su tratamiento.", "El PMS no acepta sin verificación cualquier estado enviado por el canal.", "Demasiada desconfianza puede volver inviable el servicio; demasiada confianza concentra riesgo."),
  u("Responsabilidad compartida", "Responsabilidad compartida distribuye tareas sin diluir quién responde por la consecuencia completa.", "No significa que todos sean responsables de todo.", "Asigna obligaciones por capa y conserva una autoridad para el resultado end-to-end.", "Matrices de decisión, acuerdos, ejercicios e incidentes prueban si la distribución funciona.", "El proveedor protege la plataforma y el hotel gobierna configuración, acceso y reparación al huésped.", "Los modelos genéricos no sustituyen el reparto específico de cada servicio."),
  u("Degradación diseñada", "Degradación diseñada mantiene una parte segura y valiosa de la promesa cuando una dependencia falla.", "No es tolerar silenciosamente peor calidad ni ocultar una caída.", "Define capacidades mínimas, prioridades, comunicación y límites antes del incidente.", "Pruebas de falla y tiempos reales muestran si el modo degradado es practicable.", "Recepción entrega una llave temporal bajo control cuando identidad externa no responde.", "Algunas obligaciones no admiten degradación y requieren detener."),
  u("Riesgo de concentración", "Riesgo de concentración aparece cuando múltiples capacidades dependen de un mismo proveedor, dato o punto de control.", "No se reduce a participación de mercado ni a disponibilidad histórica.", "Una falla común propaga consecuencias que los tableros por servicio no anticipan.", "Inventarios, escenarios y análisis de dependencia revelan exposición acumulada.", "Identidad compartida puede detener reservas, ingreso y accesos internos.", "Duplicar proveedores también agrega complejidad y no garantiza independencia."),
  u("Portabilidad y salida", "Portabilidad y salida preservan la posibilidad de mover datos, procesos y responsabilidades sin quebrar la promesa.", "No es una cláusula ornamental ni una migración improvisada al final.", "Se diseña con formatos, derechos, conocimiento, pruebas, costos y continuidad.", "Ensayos de exportación, sustitución y recuperación verifican la opción.", "El hotel puede recuperar reservas y reglas si cambia de canal.", "Una salida técnicamente posible puede ser operacionalmente inviable."),
  u("Gobernanza del ecosistema", "Gobernanza del ecosistema coordina reglas comunes entre participantes que conservan autonomía.", "No equivale a centralizar toda decisión ni a confiar sólo en contratos.", "Combina foros, estándares, métricas, escalamiento, incentivos y revisión.", "Cambios de interfaz e incidentes muestran si el gobierno anticipa y aprende.", "Hotel, canal y proveedor acuerdan estados, avisos y reparación.", "El participante con más poder puede imponer costos que el mecanismo formal no corrige."),
 ],
 instrument_title="Instrumento HH-26: mapa de ecosistema y dependencia",
 instrument_fields=["Promesa y población", "Capacidades", "Participantes", "Ownership end-to-end", "Dependencias críticas", "Fronteras de confianza", "Contratos y datos", "Señales de salud", "Modo degradado", "Reparación", "Portabilidad", "Fecha de revisión"],
 transfer_title="Caso de transferencia: turnos hospitalarios",
 transfer=["Un hospital coordina turnos con obras sociales, laboratorios, identidad provincial y servicios internos. Cada actor conserva autonomía, pero la persona experimenta un único recorrido.", "El mapa distingue qué puede resolver el hospital, qué debe acordar y qué necesita una vía degradada. Una autorización externa ausente no se convierte automáticamente en abandono clínico.", "HH-26 permite gobernar la promesa sin fingir control total sobre el ecosistema."],
 counter_title="Contraejemplo: el diagrama de microservicios",
 counter=["Un equipo presenta un diagrama con servicios, colas y APIs y lo llama mapa de ecosistema.", "No aparecen operadores, proveedores, contratos, decisiones manuales, concentración ni salida. El dibujo explica conectividad y oculta la promesa.", "La arquitectura se vuelve útil cuando relaciona dependencias con autoridad, consecuencias y reparación."],
 errors=["Confundir ecosistema con inventario", "Dibujar sólo tecnología", "Asignar ownership sin autoridad", "Tratar al tercero como caja negra", "Ignorar concentración", "Confiar sin verificar", "Degradar sin límite", "Prometer sustitución instantánea", "Olvidar trabajo manual", "Gobernar sólo por contrato"],
 referents=[["ITIL", "Sitúa servicios y cocreación de valor dentro de relaciones organizacionales."], ["Parker, Van Alstyne y Choudary", "Analizaron plataformas, reglas y efectos de red."], ["Team Topologies", "Relaciona plataformas internas, interacción de equipos y flujo."], ["NIST", "Integra riesgo de cadena de suministro durante el ciclo de vida."], ["CISA", "Desplaza seguridad hacia decisiones de diseño y proveedor."], ["ISO/IEC", "Define requisitos para sistemas de gestión de servicios."]],
 references=["AXELOS (2019). ITIL Foundation: ITIL 4 Edition. TSO.", "Parker, G. G., Van Alstyne, M. W. y Choudary, S. P. (2016). Platform Revolution. Norton.", "Tiwana, A. (2014). Platform Ecosystems. Morgan Kaufmann.", "Skelton, M. y Pais, M. (2019). Team Topologies. IT Revolution.", "ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html", "NIST (2024). Cybersecurity Supply Chain Risk Management Practices for Systems and Organizations, SP 800-161r1-upd1. https://doi.org/10.6028/NIST.SP.800-161r1-upd1", "NIST (2020). Zero Trust Architecture, SP 800-207. https://doi.org/10.6028/NIST.SP.800-207", "CISA (2023). Shifting the Balance of Cybersecurity Risk: Principles and Approaches for Security-by-Design and Default. https://www.cisa.gov/resources-tools/resources/secure-by-design", "European Union (2023). Regulation (EU) 2023/2854, Data Act. https://eur-lex.europa.eu/eli/reg/2023/2854/oj", "Ross, J. W., Weill, P. y Robertson, D. C. (2006). Enterprise Architecture as Strategy. Harvard Business School Press.", "Hohpe, G. y Woolf, B. (2003). Enterprise Integration Patterns. Addison-Wesley.", "FinOps Foundation (2026). FinOps Framework. https://www.finops.org/framework/"]
),
27: doc(
 slug="contratos_sintacticos_semanticos_temporales_y_operacionales",
 title="Contratos sintácticos, semánticos, temporales y operacionales",
 question="¿Qué debe acordarse para que dos partes no sólo intercambien datos válidos, sino que produzcan la misma consecuencia bajo tiempos y fallas reales?",
 opening_title="El mensaje era válido y la habitación seguía bloqueada",
 opening=[
  "El canal externo envía al Hotel Horizonte un mensaje válido: la reserva quedó confirmada. El PMS acepta el esquema, registra el identificador y responde con éxito. Minutos después, Recepción descubre que la habitación accesible fue reasignada porque ambos sistemas interpretaban confirmada de manera distinta.",
  "La sintaxis coincidía. La semántica no. Además, el canal esperaba respuesta en cinco segundos, el PMS conciliaba cada diez minutos y Operaciones no sabía quién debía intervenir cuando llegaban eventos fuera de orden. El contrato visible cubría campos; el contrato real incluía significado, tiempo y trabajo.",
  "Un contrato operativo expresa qué puede enviarse, qué significa, cuándo conserva validez, qué estado cambia, qué error puede ocurrir, quién repara y cómo evoluciona. No elimina desacuerdos, pero los vuelve detectables antes de trasladarlos a una persona.",
  "El equipo toma el episodio y separa cuatro capas. Define estructura y tipos, glosario de estados, ventanas temporales, precondiciones, idempotencia, errores, seguridad, versión y procedimiento de contingencia. Cada capa tiene una prueba distinta.",
  "La documentación deja de ser una promesa abstracta de integración. Se convierte en un acuerdo verificable entre productores, consumidores, operadores y responsables de la consecuencia.",
  "N27 recibe de HH-26 dependencias críticas y transforma cada vínculo en un contrato completo. El objetivo no es producir más especificaciones, sino impedir que una coincidencia técnica oculte una contradicción operativa."
 ],
 hotel="HH-27 selecciona la integración entre canal y PMS. El expediente registra estructura, vocabulario, temporalidad, precondiciones, efectos, errores, seguridad, compatibilidad y operación. Luego prueba mensajes duplicados, demorados, fuera de orden y semánticamente contradictorios. La reserva sólo cambia de estado cuando todas las capas sostienen la misma consecuencia.",
 advance="N27 diseña contratos sintácticos, semánticos, temporales y operacionales, y vincula conformidad técnica con significado compartido, comportamiento observable y capacidad de reparación.",
 defer="N28 tomará esos contratos y decidirá qué evidencia de calidad exige cada riesgo. N27 no establece todavía el conjunto completo de atributos ni la suficiencia de sus pruebas.",
 units=[
  u("Contrato sintáctico", "Un contrato sintáctico define estructura, tipos, obligatoriedad y formato de un intercambio.", "No garantiza significado, oportunidad ni efecto correcto.", "Permite validar mensajes antes de procesarlos y detectar incompatibilidades estructurales.", "Esquemas, ejemplos y pruebas de validación sostienen su conformidad.", "La reserva exige identificador, fecha, categoría y estado con tipos definidos.", "Dos mensajes válidos pueden representar decisiones opuestas."),
  u("Contrato semántico", "Un contrato semántico acuerda qué significa cada dato, estado y transición en un contexto de decisión.", "No es un glosario aislado ni una etiqueta compartida.", "Relaciona términos con reglas, autoridad, población y consecuencia.", "Ejemplos límite, episodios y tablas de decisión revelan ambigüedades.", "Confirmada significa capacidad reservada y no sólo mensaje recibido.", "El significado cambia con contexto y necesita gobierno."),
  u("Contrato temporal", "Un contrato temporal define ventanas, orden, vigencia, latencia y tratamiento de demora.", "No se reduce a un timeout técnico.", "Establece cuándo una afirmación puede usarse y qué ocurre si llega tarde o fuera de secuencia.", "Relojes, trazas y pruebas con demora permiten contrastarlo.", "Un estado de habitación pierde validez después de una reasignación.", "Los relojes no son perfectos y la operación necesita tolerancias explícitas."),
  u("Contrato operacional", "Un contrato operacional define efectos, errores, escalamiento, observación y reparación alrededor de una interfaz.", "No es sólo un SLA ni una página de soporte.", "Conecta comportamiento técnico con responsabilidades de personas y equipos.", "Ejercicios de falla e incidentes muestran si puede operarse.", "Recepción sabe cómo continuar cuando la confirmación queda indeterminada.", "Un procedimiento que depende de conocimiento privado no constituye capacidad."),
  u("Precondición y poscondición", "Precondición y poscondición declaran qué debe ser cierto antes y después de una operación.", "No son comentarios opcionales sobre el camino feliz.", "Limitan estados válidos y vuelven comprobable el efecto prometido.", "Pruebas de transición y registros de estado contrastan ambas condiciones.", "Sólo se asigna una habitación disponible y el resultado conserva trazabilidad.", "Sistemas concurrentes pueden invalidar una precondición entre lectura y escritura."),
  u("Invariante", "Una invariante es una condición que debe preservarse a través de operaciones y fallas.", "No equivale a una preferencia ni a una regla sin autoridad.", "Orienta diseño, control y reparación cuando existen múltiples caminos.", "Pruebas generativas y revisión de incidentes buscan violaciones.", "Una habitación accesible prometida no puede reasignarse sin decisión autorizada.", "Invariantes en conflicto requieren prioridad y decisión institucional."),
  u("Idempotencia", "Idempotencia permite repetir una operación sin multiplicar su efecto material.", "No significa que toda respuesta sea idéntica ni que no exista costo.", "Utiliza claves, estados y deduplicación para controlar reintentos.", "Mensajes duplicados y fallas intermedias prueban el mecanismo.", "Reenviar una confirmación no crea dos reservas.", "Operaciones irreversibles pueden requerir compensación en lugar de idempotencia."),
  u("Contrato de error", "Un contrato de error clasifica fallas, incertidumbre y respuestas que productores y consumidores pueden manejar.", "No es una lista genérica de códigos.", "Distingue rechazo, demora, duplicación, resultado indeterminado y degradación.", "Pruebas negativas y simulaciones verifican detección y acción.", "El PMS informa si la reserva fue rechazada o si el estado quedó desconocido.", "Exponer detalle excesivo puede crear riesgo de seguridad o acoplamiento."),
  u("Evolución compatible", "Evolución compatible permite cambiar un contrato sin quebrar consumidores existentes ni congelar el servicio.", "No se resuelve sólo incrementando un número de versión.", "Declara compatibilidad, deprecación, ventana de migración y criterio de retiro.", "Pruebas con consumidores reales y telemetría de uso muestran exposición.", "Un nuevo estado convive hasta que todos los canales puedan interpretarlo.", "Compatibilidad indefinida acumula complejidad y puede impedir mejora."),
  u("Contrato de datos", "Un contrato de datos acuerda significado, calidad, ownership, privacidad y cambio de un producto de datos.", "No es sólo esquema de tabla ni acuerdo entre equipos técnicos.", "Vincula productores y consumidores con reglas de uso y consecuencias.", "Controles de calidad, linaje y consultas reales verifican su cumplimiento.", "Disponibilidad de habitación conserva fuente, frescura y reglas de corrección.", "Un contrato puede formalizar una definición injusta si no revisa su efecto."),
  u("Contrato de seguridad", "Un contrato de seguridad define identidad, autorización, confidencialidad, integridad y evidencia de acceso.", "No consiste en agregar autenticación al final.", "Distribuye controles según la frontera de confianza y el daño posible.", "Pruebas de autorización, auditoría y escenarios de abuso contrastan garantías.", "El canal puede consultar una categoría sin acceder a datos innecesarios del huésped.", "Más control puede reducir accesibilidad o continuidad si no existe contingencia."),
  u("Prueba de contrato", "Una prueba de contrato verifica acuerdos relevantes desde la perspectiva de productor, consumidor y operación.", "No reemplaza pruebas end-to-end ni evidencia del outcome.", "Automatiza conformidad estable y conserva escenarios semánticos y adversos.", "Resultados reproducibles, cobertura de estados y fallas conocidas sostienen confianza.", "El consumidor publica expectativas y el productor las verifica antes de desplegar.", "Una suite verde puede omitir contratos humanos, temporales o regulatorios."),
 ],
 instrument_title="Instrumento HH-27: ficha de contrato verificable",
 instrument_fields=["Propósito y consecuencia", "Productor y consumidor", "Sintaxis", "Semántica", "Temporalidad", "Precondiciones", "Poscondiciones", "Invariantes", "Errores y reintentos", "Seguridad", "Evolución", "Operación y reparación"],
 transfer_title="Caso de transferencia: resultados de laboratorio",
 transfer=["Un laboratorio externo envía resultados a una historia clínica. El esquema es válido, pero urgente, preliminar y corregido no significan lo mismo para todos los actores.", "El contrato incorpora significado, orden, vigencia, confirmación, corrección y escalamiento clínico. Una prueba técnica no reemplaza la responsabilidad profesional sobre el resultado.", "HH-27 permite separar interoperabilidad estructural de interoperabilidad operativa."],
 counter_title="Contraejemplo: una API documentada",
 counter=["Una organización publica OpenAPI, genera clientes y declara resuelta la integración.", "Los campos validan, pero nadie acuerda significado, orden, resultado indeterminado ni reparación. La documentación describe la superficie y no el compromiso.", "El contrato se completa cuando una falla puede interpretarse y tratarse sin improvisación."],
 errors=["Confundir sintaxis con acuerdo", "Definir estados sin transición", "Ignorar tiempo y orden", "Usar timeout como decisión", "Reintentar sin idempotencia", "Devolver errores ambiguos", "Versionar sin migración", "Ocultar trabajo operacional", "Probar sólo el camino feliz", "Formalizar significado sin actores"],
 referents=[["IETF", "Define la semántica común de HTTP."], ["OpenAPI Initiative", "Estandariza descripciones de interfaces HTTP."], ["JSON Schema", "Proporciona vocabularios para validar estructura."], ["Eric Evans", "Vincula lenguaje compartido con modelos de dominio."], ["Martin Kleppmann", "Analiza datos, distribución, tiempo y fallas."], ["Gregor Hohpe y Bobby Woolf", "Sistematizaron patrones de integración empresarial."]],
 references=["IETF (2022). RFC 9110, HTTP Semantics. https://www.rfc-editor.org/rfc/rfc9110", "OpenAPI Initiative (2024). OpenAPI Specification 3.1.1. https://spec.openapis.org/oas/v3.1.1.html", "JSON Schema (2022). Draft 2020-12. https://json-schema.org/draft/2020-12", "Evans, E. (2003). Domain-Driven Design. Addison-Wesley.", "Kleppmann, M. (2017). Designing Data-Intensive Applications. O'Reilly.", "Hohpe, G. y Woolf, B. (2003). Enterprise Integration Patterns. Addison-Wesley.", "Fowler, M. (2002). Patterns of Enterprise Application Architecture. Addison-Wesley.", "AsyncAPI Initiative (2024). AsyncAPI Specification 3.0.0. https://www.asyncapi.com/docs/reference/specification/v3.0.0", "W3C (2013). PROV Overview. https://www.w3.org/TR/prov-overview/", "ISO/IEC (2023). ISO/IEC 25010:2023 Product Quality Model. https://www.iso.org/standard/78176.html", "NIST (2020). Zero Trust Architecture, SP 800-207. https://doi.org/10.6028/NIST.SP.800-207", "Pact Foundation (2026). Consumer Driven Contract Testing. https://docs.pact.io/"]
),
28: doc(
 slug="evidencia_de_calidad_segun_riesgo_y_atributos_en_tension",
 title="Evidencia de calidad según riesgo y atributos en tensión",
 question="¿Qué evidencia alcanza para sostener calidad cuando confiabilidad, seguridad, accesibilidad, desempeño y capacidad de cambio no pueden maximizarse al mismo tiempo?",
 opening_title="Todas las pruebas pasaron y la promesa falló",
 opening=[
  "Hotel Horizonte despliega una nueva regla de asignación. Las pruebas funcionales pasan, la cobertura aumenta y el tiempo promedio mejora. En el primer fin de semana completo, una huésped que usa lector de pantalla no puede confirmar la habitación y el turno nocturno tarda cuarenta minutos en reconstruir qué ocurrió.",
  "El equipo había probado funciones, no la calidad de la promesa bajo riesgo. Accesibilidad, recuperabilidad, observabilidad y operabilidad quedaron fuera porque ningún defecto aislado impedía el despliegue. La evidencia respondía preguntas distintas de las que importaban.",
  "Calidad no es perfección ni una suma de atributos. Es una afirmación situada sobre adecuación, acompañada por evidencia proporcional al daño y por decisiones explícitas cuando los atributos entran en tensión.",
  "El equipo identifica escenarios críticos y formula reclamos de calidad. Para cada uno registra población, atributo, riesgo, evidencia, umbral, incertidumbre y autoridad. Las pruebas se complementan con observación, revisión, simulación y experiencia de uso.",
  "La decisión cambia. El despliegue se limita hasta resolver accesibilidad y recuperación, mientras se conserva la mejora de desempeño en un segmento controlado. La tensión deja de resolverse por intuición o por el indicador más visible.",
  "N28 recibe contratos verificables y pregunta qué confianza permiten sostener. La respuesta no es más prueba en abstracto, sino una arquitectura de evidencia gobernada por riesgo."
 ],
 hotel="HH-28 selecciona tres promesas críticas: asignar sin discriminación, recuperar ante estados contradictorios y conservar respuesta durante picos. Cada promesa se convierte en un reclamo con escenarios, atributos, evidencia y umbrales. La calidad se defiende como argumento revisable y no como certificado acumulativo.",
 advance="N28 construye evidencia de calidad según riesgo, hace visibles atributos en tensión y vincula cada afirmación con escenarios, umbrales, incertidumbre y autoridad.",
 defer="N29 utilizará esos reclamos para gobernar integración, despliegue, infraestructura, aprobación y rollback. N28 no diseña todavía el mecanismo de liberación.",
 units=[
  u("Calidad situada", "Calidad situada es la adecuación de una capacidad para actores, propósitos y condiciones explícitas.", "No es ausencia total de defectos ni conformidad genérica con una lista.", "Relaciona propiedades del sistema con consecuencias en uso y operación.", "Escenarios representativos y adversos sostienen la afirmación.", "El ingreso puede ser rápido y aun así inaccesible o irreparable.", "Los propósitos compiten y requieren prioridades institucionales."),
  u("Atributo de calidad", "Un atributo de calidad nombra una propiedad evaluable que influye en el valor y el riesgo del sistema.", "No es una cualidad aspiracional sin medida ni contexto.", "Se operacionaliza mediante escenarios, estímulos, respuestas y umbrales.", "Medidas repetibles y evidencia de campo permiten contrastarlo.", "Recuperabilidad se observa ante un estado de reserva indeterminado.", "Una métrica aislada rara vez representa todo el atributo."),
  u("Escenario de calidad", "Un escenario de calidad describe estímulo, contexto, componente afectado, respuesta y medida esperada.", "No se reduce a caso de uso ordinario ni a requisito vago.", "Convierte una propiedad transversal en una situación discutible.", "Pruebas, simulaciones y observación reproducen sus condiciones.", "Durante un pico, identidad falla y Recepción mantiene una vía segura en cinco minutos.", "Escenarios conocidos no cubren todas las combinaciones futuras."),
  u("Riesgo de calidad", "Riesgo de calidad combina incertidumbre y consecuencia sobre una promesa relevante.", "No equivale a probabilidad técnica ni severidad abstracta.", "Prioriza evidencia y control según población, reversibilidad, exposición y daño.", "Historias de incidentes, amenazas y análisis de impacto sostienen su estimación.", "Una reasignación accesible tiene baja frecuencia y consecuencia alta.", "Las estimaciones reflejan información y poder disponibles."),
  u("Reclamo de calidad", "Un reclamo de calidad es una afirmación concreta sobre el comportamiento aceptable de una capacidad.", "No es un eslogan de excelencia ni una certificación autosuficiente.", "Vincula escenario, atributo, umbral, evidencia y responsable.", "La trazabilidad entre reclamo y evidencia permite revisión independiente.", "El servicio recupera una reserva indeterminada sin perder accesibilidad.", "Un reclamo puede quedar refutado por evidencia nueva."),
  u("Evidencia suficiente", "Evidencia suficiente es el conjunto proporcional de observaciones que permite una decisión bajo incertidumbre explícita.", "No significa cantidad máxima de pruebas ni certeza absoluta.", "Combina métodos que cubren mecanismos, contextos y fallas diferentes.", "Repetibilidad, pertinencia, independencia y límites sostienen su fuerza.", "Pruebas automáticas, ensayo operativo y evaluación accesible sustentan el despliegue.", "La suficiencia depende del riesgo y de la reversibilidad."),
  u("Oráculo de prueba", "Un oráculo de prueba establece cómo reconocer un resultado aceptable o una desviación significativa.", "No siempre coincide con una salida exacta calculada de antemano.", "Puede usar invariantes, comparación, propiedades, expertos o evidencia histórica.", "Casos límite y discrepancias muestran la calidad del oráculo.", "La asignación respeta restricciones aun cuando existan varias habitaciones válidas.", "Oráculos débiles pueden legitimar resultados incorrectos."),
  u("Confiabilidad y recuperación", "Confiabilidad y recuperación expresan continuidad, detección, restauración y aprendizaje ante fallas.", "No son sólo disponibilidad promedio ni tiempo técnico de reinicio.", "Relacionan modo de falla con impacto, degradación y reparación.", "Ejercicios, incidentes y tiempos end-to-end ofrecen evidencia.", "El hotel continúa ingreso y reconcilia después sin duplicar reservas.", "Una recuperación rápida puede perder integridad o trasladar trabajo."),
  u("Desempeño y capacidad", "Desempeño y capacidad describen respuesta y sostenimiento bajo cargas y patrones concretos.", "No se reducen a velocidad en laboratorio.", "Incluyen volumen, concurrencia, colas, variabilidad y degradación.", "Pruebas de carga y datos de producción contrastan escenarios.", "El ingreso conserva umbral durante llegadas concentradas.", "Optimizar promedio puede perjudicar colas extremas o accesibilidad."),
  u("Seguridad, privacidad y accesibilidad", "Seguridad, privacidad y accesibilidad son condiciones de calidad que protegen derechos y participación.", "No constituyen controles finales separados de la experiencia.", "Se incorporan a escenarios, arquitectura, prueba y operación.", "Revisión especializada y participación de poblaciones afectadas aportan evidencia.", "Una confirmación protege datos y funciona con tecnologías de asistencia.", "Los controles pueden entrar en tensión y necesitan alternativas seguras."),
  u("Mantenibilidad y evolutividad", "Mantenibilidad y evolutividad expresan la capacidad de comprender, cambiar y verificar sin riesgo desproporcionado.", "No equivalen a código limpio ni velocidad de entrega aislada.", "Dependencias, modularidad, pruebas y conocimiento distribuido condicionan el cambio.", "Tiempo de modificación, tasa de falla y ejercicios de sustitución muestran capacidad.", "Agregar un estado no obliga a coordinar todos los canales a la vez.", "La flexibilidad excesiva puede aumentar complejidad y ambigüedad."),
  u("Tensión entre atributos", "Una tensión entre atributos aparece cuando mejorar una propiedad altera costo, riesgo o desempeño de otra.", "No es excusa para aceptar cualquier compromiso.", "Se gobierna con escenarios, prioridades, alternativas y registro de renuncias.", "Comparaciones explícitas y resultados distribuidos vuelven discutible la decisión.", "Más verificación protege integridad pero puede aumentar espera.", "Algunos derechos y límites regulatorios no se negocian como una preferencia."),
 ],
 instrument_title="Instrumento HH-28: argumento de calidad basado en riesgo",
 instrument_fields=["Promesa", "Población", "Escenario", "Atributos", "Riesgo", "Reclamo", "Evidencia", "Oráculo", "Umbral", "Tensión", "Autoridad", "Revisión"],
 transfer_title="Caso de transferencia: priorización clínica",
 transfer=["Un sistema de priorización clínica debe responder rápido, proteger datos, ser accesible y permitir intervención profesional. Ningún atributo puede evaluarse fuera del daño posible.", "El argumento combina pruebas, simulaciones, revisión clínica, evaluación accesible y monitoreo limitado. El despliegue se acota si una población queda sin evidencia suficiente.", "HH-28 evita usar precisión promedio como sustituto de calidad integral."],
 counter_title="Contraejemplo: cobertura como calidad",
 counter=["Un equipo informa cobertura completa y cero defectos críticos antes de liberar.", "La suite no incluye fallas de terceros, tecnologías de asistencia, recuperación ni carga extrema. La medida describe el código ejercitado, no la promesa sostenida.", "La evidencia vale por la afirmación que permite defender y por los límites que conserva."],
 errors=["Tratar calidad como perfección", "Probar sin escenario", "Confundir cobertura con confianza", "Medir sólo promedios", "Excluir poblaciones críticas", "Aprobar sin umbral", "Ocultar tensiones", "Acumular evidencia irrelevante", "Separar operación de prueba", "Certificar sin revisión"],
 referents=[["ISO/IEC", "Actualiza el modelo de calidad de productos y sistemas TIC."], ["Len Bass, Paul Clements y Rick Kazman", "Relacionan atributos de calidad con escenarios y arquitectura."], ["Victor Basili", "Vincula objetivos, preguntas y métricas."], ["NIST", "Integra seguridad, gobierno y riesgo."], ["W3C", "Define criterios verificables de accesibilidad web."], ["Nicole Forsgren, Jez Humble y Gene Kim", "Relacionan desempeño de entrega con estabilidad y aprendizaje."]],
 references=["ISO/IEC (2023). ISO/IEC 25010:2023 Product Quality Model. https://www.iso.org/standard/78176.html", "ISO/IEC (2023). ISO/IEC 25019:2023 Quality-in-Use Model. https://www.iso.org/standard/78177.html", "Bass, L., Clements, P. y Kazman, R. (2021). Software Architecture in Practice, Fourth Edition. Addison-Wesley.", "Basili, V. R., Caldiera, G. y Rombach, H. D. (1994). Goal Question Metric Paradigm. Wiley.", "ISO (2018). ISO 31000:2018 Risk Management Guidelines. https://www.iso.org/standard/65694.html", "NIST (2024). The Cybersecurity Framework 2.0. https://doi.org/10.6028/NIST.CSWP.29", "NIST (2022). Secure Software Development Framework 1.1, SP 800-218. https://doi.org/10.6028/NIST.SP.800-218", "W3C (2023). Web Content Accessibility Guidelines 2.2. https://www.w3.org/TR/WCAG22/", "Google (2016). Site Reliability Engineering. O'Reilly. https://sre.google/sre-book/table-of-contents/", "Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.", "ISO/IEC/IEEE (2022). ISO/IEC/IEEE 29119-2:2021 Software Testing Processes. https://www.iso.org/standard/79428.html", "Leveson, N. (2011). Engineering a Safer World. MIT Press."]
),
29: doc(
 slug="gobierno_de_integracion_despliegue_infraestructura_aprobacion_y_rollback",
 title="Gobierno de integración, despliegue, infraestructura, aprobación y rollback",
 question="¿Cómo liberar cambios con velocidad responsable cuando código, configuración, infraestructura, datos y autoridad deben avanzar juntos y poder recuperarse?",
 opening_title="El botón de volver no devolvía el servicio",
 opening=[
  "Hotel Horizonte despliega una nueva versión del circuito de ingreso durante una tarde de baja demanda. La aplicación puede volver a la versión anterior, pero la migración ya transformó estados de reserva y el proveedor de cerraduras actualizó una regla incompatible. El botón de rollback revierte código y deja la operación partida.",
  "La aprobación había revisado alcance y pruebas funcionales. No había verificado procedencia del artefacto, compatibilidad de datos, configuración, infraestructura, terceros, observabilidad ni autoridad para interrumpir. El despliegue era técnicamente automatizado y organizacionalmente incompleto.",
  "Gobernar una liberación significa coordinar una decisión reversible o reparable a través de toda la cadena. Incluye integración continua, artefactos trazables, ambientes, infraestructura como código, pruebas, segregación, despliegue progresivo, monitoreo y planes de recuperación.",
  "El equipo reconstruye la versión liberada desde su origen. Declara qué cambia, qué evidencia habilita cada puerta, quién aprueba según riesgo, qué población se expone y cómo se recuperan código, datos, configuración y operación.",
  "La velocidad deja de medirse por frecuencia aislada. Importa cuánto compromiso puede asumirse sin perder capacidad de observar, detener, corregir y aprender.",
  "N29 recibe de HH-28 reclamos de calidad y los convierte en decisiones de liberación. El objetivo no es agregar burocracia, sino ubicar control donde reduce incertidumbre y daño."
 ],
 hotel="HH-29 organiza una liberación progresiva del circuito de ingreso. El expediente vincula cambio, artefacto, procedencia, ambientes, datos, infraestructura, pruebas, aprobación, exposición, señales y recuperación. Un ensayo descubre que volver código no restaura estados; el plan cambia antes de ampliar el despliegue.",
 advance="N29 gobierna integración, despliegue, infraestructura, aprobación y rollback como una cadena de compromiso trazable, progresiva y reparable.",
 defer="N30 observará la promesa ya operativa mediante señales técnicas, de negocio y de experiencia, y organizará incidentes y aprendizaje. N29 no diseña todavía el sistema completo de observabilidad.",
 units=[
  u("Integración continua", "Integración continua mantiene cambios pequeños combinados y verificados con frecuencia sobre una base compartida.", "No es ejecutar una herramienta ni fusionar sin disciplina.", "Reduce distancia entre versiones y detecta incompatibilidades antes de acumularlas.", "Frecuencia, tiempo de reparación y fallas de integración muestran su eficacia.", "El cambio de reserva se integra con pruebas de contrato y migración.", "Una base verde puede ocultar escenarios no automatizados."),
  u("Artefacto liberable", "Un artefacto liberable es una unidad identificada, inmutable y trazable que puede promoverse entre ambientes.", "No es cualquier compilación ni una copia reconstruida para producción.", "Conserva versión, dependencias, procedencia, firmas y evidencia asociada.", "Verificación reproducible y attestations permiten rastrear origen.", "La misma imagen probada se promueve al despliegue.", "La trazabilidad no garantiza que el contenido sea adecuado."),
  u("Ambiente y configuración", "Ambiente y configuración reúnen condiciones externas que determinan el comportamiento de una versión.", "No son detalles posteriores al código.", "Versionado, paridad relevante y gestión segura reducen diferencias invisibles.", "Inventarios, comparaciones y pruebas en condiciones reales revelan deriva.", "Reglas de cerradura y secretos se controlan junto con la aplicación.", "La producción nunca puede replicarse por completo en prueba."),
  u("Infraestructura como código", "Infraestructura como código expresa recursos y políticas mediante definiciones versionadas y revisables.", "No significa automatizar cualquier cambio sin control.", "Permite reproducibilidad, comparación, revisión y recuperación.", "Planes, estados, pruebas y reconstrucciones verifican la definición.", "Red, permisos y capacidad del ingreso quedan registrados.", "El estado externo y los cambios manuales pueden producir deriva."),
  u("Puerta de decisión", "Una puerta de decisión vincula evidencia y autoridad con el compromiso que puede asumirse.", "No es una reunión fija ni una firma ceremonial.", "Aumenta exigencia según exposición, irreversibilidad y riesgo.", "Criterios previos y decisiones registradas permiten auditarla.", "Una población limitada se habilita sólo si pasan escenarios críticos.", "Demasiadas puertas pueden dispersar responsabilidad y demorar reparación."),
  u("Aprobación basada en riesgo", "Aprobación basada en riesgo ajusta controles y autoridad al daño y a la reversibilidad del cambio.", "No equivale a aprobar todo automáticamente ni a exigir comité para cada versión.", "Clasifica cambios por alcance, evidencia, dependencia y recuperación.", "Historial de fallas y calidad de controles recalibran la clasificación.", "Un texto puede fluir con control automático; una migración requiere revisión adicional.", "Una taxonomía rígida puede ser manipulada o quedar obsoleta."),
  u("Segregación de funciones", "Segregación de funciones distribuye capacidades sensibles para reducir abuso y error no detectado.", "No exige que cada acción pase por muchas personas.", "Combina permisos, revisión, trazabilidad y controles compensatorios.", "Registros de acceso y ejercicios muestran si la separación es efectiva.", "Quien desarrolla no puede borrar sin rastro la evidencia de producción.", "Equipos pequeños necesitan diseños proporcionales que no bloqueen respuesta."),
  u("Despliegue progresivo", "Despliegue progresivo amplía exposición por etapas mientras observa evidencia y conserva salida.", "No es liberar lentamente sin criterio.", "Utiliza cohortes, feature flags, canarios y umbrales previos.", "Comparación de señales y detención automática limitan impacto.", "El nuevo ingreso comienza en un turno y una categoría controlados.", "Una muestra pequeña puede no representar picos ni poblaciones críticas."),
  u("Rollback", "Rollback restaura una versión o estado anterior cuando la reversión es segura y completa.", "No es un botón universal ni sinónimo de recuperación.", "Debe abarcar código, configuración, datos, infraestructura y contratos relevantes.", "Ensayos y tiempos medidos prueban la capacidad real.", "La versión anterior vuelve junto con reglas compatibles.", "Migraciones destructivas y efectos externos pueden impedirlo."),
  u("Rollforward y reparación", "Rollforward y reparación corrigen hacia adelante cuando volver no restaura la promesa.", "No es improvisar bajo presión ni negar la necesidad de contingencia.", "Prepara cambios compensatorios, reconciliación y comunicación.", "Ejercicios y runbooks contrastados reducen dependencia de héroes.", "El hotel repara estados migrados y mantiene una vía manual segura.", "Corregir hacia adelante puede aumentar exposición si el diagnóstico es incierto."),
  u("Procedencia y cadena de suministro", "Procedencia y cadena de suministro permiten conocer origen, transformación y controles de componentes y artefactos.", "No se resuelven con un inventario estático de paquetes.", "Firmas, SBOM, attestations y políticas conectan fuente, build y despliegue.", "Verificación independiente y monitoreo de vulnerabilidades sostienen confianza.", "El artefacto del PMS puede rastrearse hasta fuente y plataforma de build.", "Procedencia válida no demuestra ausencia de vulnerabilidades."),
  u("Cierre de liberación", "Cierre de liberación confirma que el cambio quedó operable, observado, documentado y transferido.", "No coincide con terminar el pipeline ni alcanzar cien por ciento de tráfico.", "Revisa resultados, excepciones, ownership, deuda y próximos umbrales.", "Evidencia de producción y aceptación operativa permiten cerrar.", "Recepción confirma capacidad y conoce contingencia antes de retirar soporte reforzado.", "Cerrar demasiado pronto borra señales; sostener modo especial indefinido crea dependencia."),
 ],
 instrument_title="Instrumento HH-29: expediente de liberación y recuperación",
 instrument_fields=["Cambio y alcance", "Artefacto y procedencia", "Ambientes", "Configuración", "Datos", "Infraestructura", "Contratos", "Evidencia", "Aprobación", "Exposición", "Rollback o reparación", "Cierre"],
 transfer_title="Caso de transferencia: liquidación bancaria",
 transfer=["Un banco cambia una regla de liquidación que combina aplicación, datos, mensajería y proveedor externo. Volver una versión no revierte transferencias ya emitidas.", "La liberación usa exposición progresiva, reconciliación, autorización proporcional y rollforward preparado. El plan distingue restaurar software de reparar consecuencias.", "HH-29 convierte el despliegue en una decisión sobre compromiso y no en un evento técnico."],
 counter_title="Contraejemplo: pipeline verde",
 counter=["Una organización automatiza build, pruebas y despliegue y considera gobernada la entrega.", "El pipeline no conoce cambios manuales, datos irreversibles, autoridad ni capacidad del turno. La velocidad aumenta y la reparación depende de improvisación.", "La automatización es control sólo cuando representa la promesa y sus riesgos."],
 errors=["Confundir despliegue con liberación", "Reconstruir artefactos", "Ignorar configuración", "Aprobar por calendario", "Automatizar sin autoridad", "Desplegar a todos de una vez", "Prometer rollback incompleto", "Olvidar datos y terceros", "Confiar sólo en el pipeline", "Cerrar sin operación"],
 referents=[["Jez Humble y David Farley", "Sistematizaron entrega continua y artefactos liberables."], ["Nicole Forsgren, Jez Humble y Gene Kim", "Relacionan desempeño de entrega, estabilidad y prácticas organizacionales."], ["NIST", "Integra desarrollo seguro y cadena de suministro."], ["SLSA", "Define niveles y attestations de procedencia de software."], ["CISA", "Promueve seguridad incorporada al diseño y al proveedor."], ["ISO/IEC", "Vincula seguridad y gestión del servicio con control operativo."]],
 references=["Humble, J. y Farley, D. (2010). Continuous Delivery. Addison-Wesley.", "Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.", "Google Cloud (2024). Accelerate State of DevOps Report. https://cloud.google.com/devops/state-of-devops", "NIST (2022). Secure Software Development Framework 1.1, SP 800-218. https://doi.org/10.6028/NIST.SP.800-218", "NIST (2024). Cybersecurity Supply Chain Risk Management Practices, SP 800-161r1-upd1. https://doi.org/10.6028/NIST.SP.800-161r1-upd1", "NIST (2024). Strategies for the Integration of Software Supply Chain Security in DevSecOps CI/CD Pipelines, SP 800-204D. https://doi.org/10.6028/NIST.SP.800-204D", "SLSA (2026). SLSA Specification 1.2. https://slsa.dev/spec/v1.2/", "CISA (2023). Secure by Design. https://www.cisa.gov/resources-tools/resources/secure-by-design", "ISO/IEC (2022). ISO/IEC 27001:2022 Information Security Management Systems. https://www.iso.org/standard/27001", "ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html", "OpenGitOps (2021). GitOps Principles 1.0. https://opengitops.dev/", "Kim, G., Humble, J., Debois, P. y Willis, J. (2021). The DevOps Handbook, Second Edition. IT Revolution."]
),
30: doc(
 slug="observabilidad_senales_sli_slo_incidentes_y_aprendizaje",
 title="Observabilidad técnica, señales de negocio, SLI, SLO, incidentes y aprendizaje",
 question="¿Cómo saber si una promesa sigue en pie, detectar una degradación antes de que se vuelva normal y convertir incidentes en capacidad colectiva?",
 opening_title="Los tableros estaban verdes y el huésped esperaba",
 opening=[
  "Hotel Horizonte completa el despliegue del circuito de ingreso. CPU, memoria, disponibilidad y errores permanecen dentro de rango. Esa noche, varias reservas externas quedan en un estado intermedio y Recepción crea una cola manual. Los tableros están verdes mientras el servicio se degrada.",
  "La infraestructura emitía datos, pero nadie había conectado señales técnicas con la promesa. Tampoco existía un indicador de recorrido, un objetivo explícito ni un aviso que pudiera accionar el turno. La organización observaba componentes y no podía explicar el comportamiento del sistema completo.",
  "Observabilidad es capacidad para formular y responder preguntas sobre estados internos a partir de señales externas. Necesita telemetría coherente, contexto, indicadores de nivel de servicio, objetivos, señales de negocio, experiencia, alertas accionables y conocimiento operativo.",
  "El equipo define el ingreso logrado como evento de negocio y lo relaciona con trazas, métricas y logs. Separa disponibilidad técnica de capacidad efectiva, fija un SLO por recorrido, acuerda presupuesto de error y prepara respuesta ante estados indeterminados.",
  "Cuando ocurre el siguiente incidente, el turno detecta la degradación, limita exposición y conserva evidencia. La revisión posterior reconstruye condiciones y decisiones sin buscar una causa humana única. El aprendizaje modifica arquitectura, contrato, guardia y umbral.",
  "N30 cierra el Bloque F. Recibe una liberación gobernada y completa el circuito con señales, respuesta y aprendizaje. La promesa operativa deja de depender de que alguien note tarde que el sistema ya cambió."
 ],
 hotel="HH-30 construye un mapa de observabilidad para el ingreso. Vincula promesa, recorrido, SLI, SLO, presupuesto de error, señales técnicas, de negocio y de experiencia, alertas, ownership, respuesta y aprendizaje. El tablero deja de informar sólo salud de componentes y permite decidir si ampliar, limitar, reparar o revisar.",
 advance="N30 conecta observabilidad técnica, señales de negocio, SLI, SLO, incidentes y aprendizaje para gobernar la promesa en operación y retroalimentar decisiones anteriores.",
 defer="N31 abrirá el Bloque G y distinguirá reglas, predicción, generación y agencia para decidir si la inteligencia artificial resulta pertinente. N30 no automatiza todavía el juicio ni selecciona modelos.",
 units=[
  u("Observabilidad", "Observabilidad es la capacidad de comprender estados y comportamientos internos mediante señales externas suficientes y contextualizadas.", "No es sinónimo de monitoreo, acumulación de logs ni compra de una plataforma.", "Integra instrumentación, contexto y preguntas nuevas sobre el sistema.", "La posibilidad de explicar episodios no previstos muestra su calidad.", "Una traza conecta la reserva externa con el estado intermedio y la cola manual.", "No todo estado puede inferirse y la instrumentación también falla."),
  u("Monitoreo", "Monitoreo compara señales conocidas con condiciones y umbrales previamente definidos.", "No responde por sí solo preguntas nuevas ni explica causalidad.", "Detecta desviaciones esperadas y activa decisiones operativas.", "Cobertura, precisión y accionabilidad de alertas permiten evaluarlo.", "Una caída de ingresos logrados por minuto dispara revisión.", "Umbrales estáticos pueden ignorar contexto o producir ruido."),
  u("Telemetría", "Telemetría reúne trazas, métricas, logs y contexto emitidos por componentes y recorridos.", "No es evidencia útil sólo por existir en gran volumen.", "Correlación, semántica y procedencia permiten reconstruir actividad distribuida.", "Muestreo, completitud y capacidad de enlazar señales determinan utilidad.", "El identificador del episodio atraviesa canal, PMS y cerradura.", "Más telemetría aumenta costo, exposición de datos y carga cognitiva."),
  u("Señal de negocio", "Una señal de negocio representa una consecuencia operativa o de valor producida por el sistema.", "No se reduce a transacciones técnicas ni a un indicador financiero tardío.", "Vincula eventos del recorrido con poblaciones, decisiones y resultados.", "Reconciliación con evidencia operativa verifica su significado.", "Ingreso logrado sin reasignación mide mejor la promesa que respuesta HTTP exitosa.", "La métrica puede incentivar atajos si se separa de salvaguardas."),
  u("Indicador de nivel de servicio", "Un SLI cuantifica una dimensión observable de la experiencia o capacidad que importa a quienes dependen del servicio.", "No es cualquier métrica disponible ni una cifra elegida por facilidad.", "Define eventos válidos, población, ventana y método de cálculo.", "Comparación con episodios reales prueba su representatividad.", "Proporción de ingresos completados dentro del umbral acordado.", "Un indicador agregado puede ocultar grupos o momentos críticos."),
  u("Objetivo de nivel de servicio", "Un SLO establece el nivel esperado de un SLI durante una ventana y orienta decisiones.", "No es una promesa de perfección ni un SLA contractual automático.", "Crea un límite común para equilibrar confiabilidad, cambio y costo.", "Resultados por ventana y decisiones tomadas muestran si gobierna.", "El recorrido sostiene el umbral para la población definida.", "Un objetivo arbitrario puede normalizar mala experiencia o costo excesivo."),
  u("Presupuesto de error", "El presupuesto de error expresa la tolerancia restante entre desempeño observado y objetivo acordado.", "No autoriza daño ni convierte toda falla en aceptable.", "Vincula confiabilidad con ritmo de cambio y medidas de protección.", "Consumo, tendencia y acciones asociadas demuestran su uso.", "Si el presupuesto se agota, se limita exposición y se prioriza recuperación.", "Derechos y obligaciones críticas pueden exigir tolerancia nula."),
  u("Alerta accionable", "Una alerta accionable comunica una condición relevante a alguien capaz de intervenir con contexto suficiente.", "No es cada anomalía ni un mensaje sin prioridad.", "Relaciona señal, impacto, urgencia, owner y primera acción segura.", "Tiempo de reconocimiento, utilidad y falsos positivos permiten mejorarla.", "Recepción recibe una alerta sobre estados indeterminados y activa contingencia.", "Automatizar avisos sin autoridad produce fatiga y abandono."),
  u("Incidente", "Un incidente es una alteración no deseada de la capacidad o promesa que requiere coordinación y aprendizaje.", "No se define sólo por caída técnica ni por severidad declarada al final.", "Organiza detección, contención, comunicación, reparación y recuperación.", "Línea temporal, decisiones y consecuencias sostienen su reconstrucción.", "Reservas válidas no pueden transformarse en ingresos durante un turno.", "La clasificación inicial cambia con evidencia y no debe impedir respuesta."),
  u("Respuesta coordinada", "Respuesta coordinada distribuye autoridad y comunicación para limitar daño bajo presión.", "No depende de una persona heroica ni de un runbook inflexible.", "Define roles, canales, prioridades, escalamiento y vínculo con poblaciones afectadas.", "Ejercicios y episodios reales muestran si la capacidad existe.", "Tecnología repara estados mientras Operaciones sostiene la atención y comunica.", "La coordinación puede fallar si las responsabilidades cotidianas contradicen el plan."),
  u("Revisión posterior", "Una revisión posterior reconstruye condiciones, decisiones y mecanismos para aprender sin reducir el incidente a culpa individual.", "No es una cronología ornamental ni una búsqueda de causa única.", "Conecta evidencia con cambios verificables en sistema y organización.", "Seguimiento de acciones y recurrencia muestran aprendizaje real.", "La revisión modifica contrato temporal, alerta y modo degradado.", "Ausencia de castigo no significa ausencia de responsabilidad o reparación."),
  u("Bucle de aprendizaje operativo", "Un bucle de aprendizaje operativo devuelve evidencia de uso e incidentes a arquitectura, contratos, calidad y gobierno de liberación.", "No es una retrospectiva aislada ni una lista infinita de acciones.", "Prioriza cambios por mecanismo, riesgo y capacidad de prevenir o contener.", "Decisiones cerradas, hipótesis revisadas y reducción de recurrencia sostienen el bucle.", "HH-30 actualiza HH-26 a HH-29 con evidencia del turno.", "Aprender localmente no corrige incentivos o dependencias estructurales sin autoridad."),
 ],
 instrument_title="Instrumento HH-30: mapa de observabilidad y aprendizaje",
 instrument_fields=["Promesa y recorrido", "Población", "SLI", "SLO", "Presupuesto de error", "Señales técnicas", "Señales de negocio", "Señales de experiencia", "Alerta y owner", "Respuesta", "Reparación", "Aprendizaje"],
 transfer_title="Caso de transferencia: prestación social digital",
 transfer=["Una plataforma pública mantiene infraestructura disponible, pero una validación externa deja solicitudes en espera sin explicación. El tablero técnico no refleja la pérdida de capacidad ciudadana.", "El mapa incorpora recorrido, señal de negocio, población, SLO, comunicación y contingencia. La revisión posterior modifica el acuerdo con el tercero y la vía presencial.", "HH-30 permite observar la prestación y no sólo la plataforma."],
 counter_title="Contraejemplo: más dashboards",
 counter=["Una organización agrega paneles para cada componente y declara resuelta la observabilidad.", "Las señales no comparten contexto, no representan la promesa y ninguna alerta indica una acción. El volumen crece y la incertidumbre permanece.", "Observar significa poder formular una pregunta relevante y convertir la respuesta en decisión."],
 errors=["Confundir observabilidad con tableros", "Medir sólo componentes", "Elegir SLI por disponibilidad", "Fijar SLO sin consecuencia", "Usar presupuesto para tolerar daño", "Alertar sin owner", "Depender de héroes", "Buscar una causa única", "Cerrar acciones sin verificar", "Aprender sin devolver evidencia"],
 referents=[["Google SRE", "Formaliza SLI, SLO, presupuestos de error y prácticas de confiabilidad."], ["OpenTelemetry", "Estandariza señales y contexto de telemetría."], ["NIST", "Integra respuesta a incidentes con gobierno de riesgo."], ["Nicole Forsgren, Jez Humble y Gene Kim", "Relacionan estabilidad, flujo y desempeño organizacional."], ["Erik Hollnagel", "Desarrolla aprendizaje desde el trabajo que sale bien y mal."], ["Nancy Leveson", "Analiza accidentes como resultado de controles y condiciones sistémicas."]],
 references=["Beyer, B., Jones, C., Petoff, J. y Murphy, N. R. (2016). Site Reliability Engineering. O'Reilly. https://sre.google/sre-book/table-of-contents/", "Beyer, B., Murphy, N. R., Rensin, D. K., Kawahara, K. y Thorne, S. (2018). The Site Reliability Workbook. O'Reilly. https://sre.google/workbook/table-of-contents/", "OpenTelemetry (2026). OpenTelemetry Specification 1.60.0. https://opentelemetry.io/docs/specs/otel/", "OpenTelemetry (2026). Signals. https://opentelemetry.io/docs/concepts/signals/", "NIST (2025). Incident Response Recommendations and Considerations for Cybersecurity Risk Management, SP 800-61r3. https://doi.org/10.6028/NIST.SP.800-61r3", "NIST (2024). The Cybersecurity Framework 2.0. https://doi.org/10.6028/NIST.CSWP.29", "Forsgren, N., Humble, J. y Kim, G. (2018). Accelerate. IT Revolution.", "Allspaw, J. (2016). Trade-Offs Under Pressure. Adaptive Capacity Labs.", "Hollnagel, E. (2014). Safety-I and Safety-II. Ashgate.", "Woods, D. D. (2015). Four Concepts for Resilience and the Implications for the Future of Resilience Engineering. Reliability Engineering and System Safety, 141, 5-9.", "Leveson, N. (2011). Engineering a Safer World. MIT Press.", "ISO/IEC (2018). ISO/IEC 20000-1:2018 Service Management System Requirements. https://www.iso.org/standard/70636.html"]
),
}


base.REFERENCE_NOTES.update({
    "Platform Revolution": "analiza plataformas, reglas y efectos de red en ecosistemas",
    "Platform Ecosystems": "vincula arquitectura, gobierno y evolución de plataformas",
    "Team Topologies": "relaciona plataformas internas con interacción de equipos y flujo",
    "20000-1:2018": "establece requisitos de gestión para sostener servicios",
    "800-161": "integra riesgo de cadena de suministro durante el ciclo de vida",
    "Zero Trust": "sitúa verificación y acceso en fronteras de confianza explícitas",
    "Secure-by-Design": "desplaza seguridad hacia decisiones de producto y proveedor",
    "Secure by Design": "desplaza seguridad hacia decisiones de producto y proveedor",
    "Data Act": "incorpora portabilidad, acceso y condiciones de cambio de proveedor",
    "Enterprise Architecture as Strategy": "conecta arquitectura con capacidades y modelo operativo",
    "Enterprise Integration Patterns": "aporta patrones para intercambios, mensajería y fallas",
    "FinOps Framework": "hace visible costo tecnológico como responsabilidad compartida",
    "RFC 9110": "define semántica, mensajes y comportamiento de HTTP",
    "OpenAPI Specification": "estandariza descripciones legibles por personas y máquinas",
    "Draft 2020-12": "define vocabularios para describir y validar estructuras JSON",
    "Domain-Driven Design": "vincula lenguaje compartido con modelos y fronteras de dominio",
    "Data-Intensive": "analiza tiempo, distribución, consistencia y fallas en sistemas de datos",
    "AsyncAPI": "extiende contratos a interacciones asincrónicas y orientadas a eventos",
    "Consumer Driven": "prueba expectativas de consumidores contra productores",
    "25010:2023": "actualiza el modelo de calidad de productos y sistemas TIC",
    "25019:2023": "define calidad en uso desde resultados y contexto",
    "Software Architecture in Practice": "relaciona atributos de calidad con escenarios y decisiones arquitectónicas",
    "Goal Question Metric": "vincula objetivos, preguntas y medidas",
    "31000:2018": "organiza principios y proceso de gestión de riesgo",
    "Cybersecurity Framework 2.0": "incorpora gobierno al manejo de riesgo de ciberseguridad",
    "Development Framework 1.1": "integra prácticas de desarrollo seguro al ciclo de vida",
    "Accessibility Guidelines 2.2": "define criterios verificables de accesibilidad",
    "Site Reliability Engineering": "conecta confiabilidad, objetivos y operación",
    "29119-2": "define procesos de prueba a lo largo del ciclo de vida",
    "Engineering a Safer World": "analiza seguridad mediante controles y condiciones sistémicas",
    "Continuous Delivery": "organiza artefactos liberables, automatización y recuperación",
    "Accelerate": "relaciona desempeño de entrega con estabilidad y aprendizaje",
    "State of DevOps": "aporta evidencia empírica sobre capacidades de entrega y operación",
    "800-204D": "integra seguridad de cadena de suministro en pipelines",
    "SLSA Specification": "define niveles y attestations de procedencia de software",
    "27001:2022": "estructura un sistema de gestión de seguridad de la información",
    "GitOps Principles": "formula operación declarativa, versionada y reconciliada",
    "DevOps Handbook": "integra flujo, retroalimentación y aprendizaje organizacional",
    "Site Reliability Workbook": "traduce confiabilidad en prácticas e instrumentos operativos",
    "OpenTelemetry Specification": "estandariza señales, contexto y procesamiento de telemetría",
    "Signals": "distingue trazas, métricas, logs y contexto para observar sistemas",
    "800-61r3": "integra respuesta a incidentes con gobierno de riesgo",
    "Trade-Offs Under Pressure": "examina decisiones y adaptación bajo presión operativa",
    "Safety-I and Safety-II": "amplía el aprendizaje desde fallas hacia variabilidad cotidiana",
    "Four Concepts for Resilience": "define capacidades para responder a sorpresa y cambio",
})


def main() -> None:
    base.DOCS = DOCS
    built = {}
    for number, spec in DOCS.items():
        base.build(number, spec)
        built[f"N{number:02d}"] = spec["title"]
    print(json.dumps({"built": built}, ensure_ascii=False))


if __name__ == "__main__":
    main()
