#!/usr/bin/env python3
"""Build canonical METSI Block D content packages from audited editorial specifications."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent


DOCS = {
17: {
"slug":"logicas_predictivas_iterativas_incrementales_adaptativas_y_experimentales",
"title":"Lógicas predictivas, iterativas, incrementales, adaptativas y experimentales",
"question":"¿Cómo elegir una forma de intervención cuando algunas decisiones pueden anticiparse, otras necesitan aprendizaje y varias no admiten el mismo costo de error?",
"opening_title":"El plan que cumplió todas sus fechas y llegó tarde al problema",
"opening":[
"Hotel Horizonte aprueba un proyecto para reducir la espera de ingreso. El plan define nueve meses, alcance estable, proveedor, presupuesto y una secuencia de análisis, configuración, pruebas y despliegue. Cada hito se cumple. El nuevo módulo entra en producción el día previsto y registra el mismo estado que ya utilizaba el PMS: habitación liberada.",
"Durante esos nueve meses, HH-16 había mostrado que liberada significaba cosas distintas para Housekeeping, Recepción y Comercial. El proyecto conserva el término porque cambiarlo afectaría integraciones y reportes. La solución cumple el alcance contractual y acelera la propagación de una ambigüedad conocida. El primer fin de semana, las confirmaciones salen antes y también aumentan las reasignaciones, las esperas y las compensaciones.",
"La explicación fácil culpa al enfoque predictivo. Sin embargo, varias decisiones sí necesitaban anticipación: contratos, ventanas de mantenimiento, migración, capacitación y continuidad operativa. La falla no estuvo en planificar, sino en aplicar una única lógica a preguntas con incertidumbres y consecuencias diferentes. La semántica requería iteración; el flujo podía entregarse por incrementos; la regla comercial necesitaba adaptación; una nueva promesa exigía experimento controlado.",
"El equipo reabre el trabajo sin declarar fracaso total. Conserva compromisos irreversibles y transforma otros. Establece una baseline técnica para la migración, una serie de prototipos para las reglas, un incremento limitado a dos pisos y un experimento con confirmaciones sólo cuando cerradura, asignación y accesibilidad están verificadas. Cada tramo produce evidencia para la decisión siguiente.",
"La estrategia deja de nombrarse por una etiqueta global. En una misma intervención conviven cadencias, grados de anticipación y mecanismos de aprendizaje. El criterio no es qué método resulta moderno, sino qué se sabe, cuánto cuesta equivocarse, qué puede revertirse y cuándo existe evidencia suficiente para comprometer más recursos.",
"N17 abre el Bloque D con esa disciplina. Recibe de HH-16 una cartera de modelos coherente y contradicciones gobernadas. Su tarea no es volver a modelar, sino diseñar la lógica de intervención que convierte incertidumbre en decisiones revisables."
],
"hotel":"HH-16 dejó cuatro significados diferenciados para preparada, asignable, accesible y confirmada. HH-17 decide cómo intervenir sobre esa brecha. Mantiene una ruta predictiva para contratos y migración, iteraciones semanales sobre reglas, incrementos por piso, adaptación según evidencia de operación y un experimento acotado sobre confirmación anticipada. El resultado no es un método híbrido por mezcla nominal, sino una arquitectura de decisiones con riesgos, pruebas y condiciones de salida.",
"advance":"N17 separa las lógicas de intervención por el modo en que producen conocimiento y compromiso. La estrategia puede combinarlas, pero cada combinación debe conservar propósito, evidencia y autoridad.",
"defer":"N18 recibirá decisiones que ya no pueden evaluarse sin considerar legado, regulación y documentación. N17 no decide qué retirar ni qué obligación prevalece.",
"movements":[
 ["Movimiento 1 · Separar lógicas antes de combinarlas", [
  ["La incertidumbre no es una sola", "Incertidumbre significa que una decisión relevante carece de conocimiento suficiente, no que todo el proyecto sea imprevisible.", "Se confunde con desorden o falta de competencia y se intenta eliminar mediante más detalle de plan.", "Separar incertidumbre de propósito, solución, operación y entorno permite asignar una prueba distinta a cada pregunta.", "Se fortalece el diagnóstico cuando se puede nombrar qué dato, conducta o dependencia cambiaría la decisión.", "En el hotel, la fecha de migración es conocida, pero la reacción de huéspedes ante una promesa condicional no lo es.", "La decisión es anticipar lo estable y diseñar aprendizaje para lo incierto, sin esconder una categoría dentro de la otra."],
  ["Lógica predictiva", "Una lógica predictiva compromete alcance, secuencia y recursos a partir de conocimiento considerado suficiente para planificar.", "No equivale a cascada rígida, burocracia ni ausencia de revisión; puede incluir iteraciones y controles.", "Funciona cuando dependencias, tecnología, obligación y criterios de aceptación son relativamente estables y el costo de coordinación exige anticipación.", "La evidencia incluye precedentes comparables, estimaciones calibradas, contratos claros y baja variación de requisitos relevantes.", "La ventana nocturna para migrar una base y recuperar el servicio necesita ensayo, responsables y secuencia prevista.", "Si una premisa crítica sigue abierta, el plan debe declarar reserva o puerta de decisión, no convertirla en certeza."],
  ["Lógica iterativa", "Una lógica iterativa revisa una misma representación o solución mediante ciclos de crítica, prueba y reformulación.", "No es entregar varias partes ni repetir trabajo sin hipótesis; su producto puede seguir incompleto mientras mejora.", "Cada ciclo compara una versión con evidencia, conserva lo que resiste y modifica la explicación o forma que todavía falla.", "Se observa progreso cuando disminuyen contradicciones relevantes, mejora la predicción o una audiencia decide con menos ambigüedad.", "El equipo prueba tres formulaciones del estado entregable con Recepción, Housekeeping y Tecnología antes de implementar.", "Iterar sin criterio de detención produce refinamiento infinito. Se necesita decidir qué calidad es suficiente para avanzar."],
  ["Lógica incremental", "Una lógica incremental entrega capacidades utilizables en partes que amplían el sistema sin esperar la totalidad.", "No es sinónimo de iteración: un incremento agrega uso, mientras una iteración puede sólo revisar una idea.", "Reduce exposición al permitir que valor, operación y riesgo se observen sobre una fracción real del alcance.", "La evidencia aparece en resultados de uso, estabilidad, adopción y capacidad de integrar el siguiente incremento.", "La regla nueva se habilita primero en dos pisos con personal entrenado y un circuito de reparación disponible.", "Un corte por componentes que no produce capacidad utilizable no es incremento y puede postergar integración hasta el final."],
  ["Lógica adaptativa", "Una lógica adaptativa ajusta prioridades, alcance próximo y prácticas según información que emerge durante la intervención.", "No significa improvisar ni renunciar a objetivos; mantiene dirección y cambia el camino cuando la evidencia lo exige.", "Trabaja con ciclos breves, participación frecuente y autoridad disponible para reordenar decisiones sin esperar un plan anual.", "Se justifica cuando necesidades o entorno cambian y cuando el costo de replanificar es menor que el de sostener una hipótesis vencida.", "El hotel modifica el orden de pisos al descubrir que accesibilidad, no volumen, concentra el daño más difícil de reparar.", "Sin límites, la adaptación puede normalizar urgencias y borrar compromisos. Debe conservar reglas, capacidad y trazabilidad."],
  ["Lógica experimental", "Una lógica experimental interviene para distinguir explicaciones rivales bajo exposición deliberadamente limitada.", "No es probar que una solución funciona ni convertir a las personas en sujetos sin protección.", "Formula hipótesis, resultado observable, comparación, umbral, salvaguardas y criterio de interrupción antes de actuar.", "La evidencia debe permitir atribuir con prudencia el cambio y registrar daños, heterogeneidad y efectos no buscados.", "Se ensaya una confirmación condicional con una población acotada y posibilidad inmediata de volver al circuito anterior.", "Cuando no hay consentimiento, reversibilidad o capacidad de reparación, experimentar puede ser improcedente aunque exista incertidumbre."],
 ]],
 ["Movimiento 2 · Diseñar combinaciones gobernables", [
  ["Híbrido no significa collage", "Una estrategia híbrida asigna lógicas diferentes a decisiones y tramos explícitos de una misma intervención.", "Se confunde con usar ceremonias de varios marcos o llamar ágil a un plan con reuniones frecuentes.", "La combinación funciona cuando existen interfaces entre ritmos, entregables, autoridades y evidencias, no sólo una lista de prácticas.", "Se audita recorriendo una decisión desde su supuesto inicial hasta el compromiso, la prueba y la revisión.", "Migración sigue una baseline predictiva, reglas iteran, capacidad llega por incrementos y la promesa comercial se experimenta.", "Si nadie sabe qué evidencia habilita el paso entre lógicas, la mezcla aumenta handoffs y diluye responsabilidad."],
  ["Cadencia de decisión y cadencia de entrega", "Cadencia de decisión es la frecuencia con que una autoridad puede revisar compromisos; cadencia de entrega es la frecuencia con que aparece capacidad utilizable.", "Se confunden porque muchas prácticas programan ambas en el mismo ciclo.", "Separarlas permite revisar una hipótesis sin desplegar y entregar una mejora sin reabrir una decisión estratégica.", "La evidencia está en tiempos reales de aprobación, aprendizaje, integración y recuperación, no en el calendario ceremonial.", "Recepción revisa reglas semanalmente, mientras el incremento técnico se despliega cada tres semanas por restricción operativa.", "Una cadencia más rápida que la capacidad de decidir crea cola; una entrega más rápida que la capacidad de absorber crea daño."],
  ["Compromiso progresivo", "Compromiso progresivo aumenta inversión, alcance o irreversibilidad a medida que la evidencia supera umbrales acordados.", "No es posponer toda decisión ni financiar indefinidamente descubrimiento.", "Organiza opciones para aprender barato antes de bloquear arquitectura, proveedor, política o comunicación pública.", "Se observa si cada hito declara qué incertidumbre cerró y qué compromiso adicional queda ahora justificado.", "El hotel prototipa lenguaje, simula flujo, habilita dos pisos y recién después negocia una campaña general.", "Algunas obligaciones exigen compromiso temprano. La estrategia debe distinguirlas y proteger márgenes en lo demás."],
  ["Reversibilidad", "Reversibilidad es la capacidad técnica, operativa, contractual y política de volver atrás o cambiar de rumbo con costo conocido.", "Se confunde con rollback técnico, que no recupera confianza, datos divulgados ni una promesa incumplida.", "A mayor irreversibilidad, mayor evidencia previa, autoridad y preparación de contingencia necesita la decisión.", "Se evalúa con escenarios de retiro, restitución de datos, comunicación, compensación y continuidad del servicio.", "Desactivar una regla es simple; revertir mensajes enviados y reasignaciones producidas requiere otro plan.", "No toda decisión debe ser reversible. Cuando no lo es, la baseline y el juicio de compromiso adquieren más importancia."],
  ["Descubrimiento y entrega", "Descubrimiento reduce incertidumbre sobre problema, valor, uso y viabilidad; entrega crea y sostiene capacidad operacional.", "Se confunden cuando todo prototipo se trata como producto o toda entrega se usa para aprender sin proteger la operación.", "Ambos flujos se conectan mediante evidencia y criterios de transferencia, pero poseen riesgos, ritmos y definiciones de terminado diferentes.", "Se comprueba qué aprendizaje cambió una decisión y qué capacidad puede operar con soporte, autoridad y reparación.", "Una simulación revela que el mensaje confunde; un incremento posterior implementa la redacción aprobada con monitoreo.", "Separarlos demasiado crea laboratorio sin impacto y fábrica sin aprendizaje. La estrategia necesita puentes explícitos."],
  ["Riesgo como organizador", "Riesgo es el efecto de incertidumbre sobre objetivos y consecuencias, no una lista residual al final del plan.", "Se confunde con probabilidad aislada o con problema que ya ocurrió.", "Ordenar por exposición permite decidir dónde anticipar, iterar, entregar por partes, adaptar o experimentar.", "La evidencia combina posibilidad, impacto, detectabilidad, tiempo de respuesta y capacidad de reparación.", "La migración de identidad tiene baja tolerancia al error; el orden de textos de ayuda admite prueba gradual.", "Una matriz numérica no reemplaza juicio ni distribución del daño. La autoridad debe reconocer a quién expone."],
 ]],
 ["Movimiento 3 · Convertir aprendizaje en estrategia", [
  ["Puertas de decisión", "Una puerta de decisión es un punto explícito donde se continúa, modifica, detiene o escala una intervención.", "No es una reunión de estado ni una aprobación ceremonial por calendario.", "Conecta evidencia acumulada, riesgo residual, capacidad disponible y autoridad antes de aumentar compromiso.", "Pasa si los criterios de entrada están completos y la salida queda registrada con razones y obligaciones.", "El hotel no amplía el piloto hasta demostrar menos reasignaciones sin aumentar espera ni inequidad.", "Una puerta sin opción real de detener sólo legitima una decisión previa y oculta el costo hundido."],
  ["Criterios de entrada y salida", "Los criterios de entrada describen condiciones para comenzar una actividad; los de salida definen evidencia suficiente para cerrarla o transferirla.", "No equivalen a una lista de tareas completadas ni a una fecha.", "Evitan que el trabajo avance por inercia y vuelven visible qué falta, quién lo acepta y qué riesgo permanece.", "Se auditan con pruebas observables, responsables, excepciones y consecuencias si el criterio no se cumple.", "La expansión requiere trazabilidad de estados, personal disponible, recuperación ensayada y comunicación aprobada.", "Criterios excesivos pueden bloquear aprendizaje. Deben ser proporcionales a consecuencia e irreversibilidad."],
  ["Hipótesis de estrategia", "Una hipótesis de estrategia afirma que cierta combinación de acciones y lógicas producirá una capacidad bajo condiciones declaradas.", "No es una promesa de éxito ni un cronograma con lenguaje aspiracional.", "Vincula mecanismo, evidencia, riesgos y decisiones futuras para que la intervención pueda ser refutada y corregida.", "Se fortalece si predice señales tempranas, efectos laterales y condiciones bajo las cuales conviene cambiar de enfoque.", "Se espera que confirmación condicional reduzca llamadas sin aumentar entregas fallidas ni excluir casos accesibles.", "Si el resultado mejora por otra causa, la estrategia no debe atribuirse el mérito sin contraste."],
  ["Automatización e inteligencia artificial", "La inteligencia artificial puede acelerar exploración, generación y análisis, pero no absorbe autoridad ni responsabilidad por la estrategia.", "Se confunde velocidad de producir opciones con calidad de decidir entre ellas.", "Su utilidad depende de procedencia, revisión humana, cobertura, sesgo, seguridad y posibilidad de retirar una salida.", "La evidencia compara recomendaciones con casos, registra divergencias y mide quién detecta y repara errores.", "Un asistente propone escenarios de prueba, mientras el equipo decide exposición, umbrales y comunicación.", "Cuando una recomendación cambia derechos o recursos, debe existir explicación suficiente, apelación y control humano efectivo."],
  ["Portafolio de apuestas", "Un portafolio de apuestas distribuye aprendizaje e inversión entre opciones con horizontes y riesgos diferentes.", "No es ejecutar muchas iniciativas para evitar priorizar.", "Permite sostener una ruta principal, experimentos acotados y contingencias sin comprometer todo el sistema a una hipótesis.", "Se evalúa por información producida, opciones preservadas y decisiones habilitadas, además de entregables.", "El hotel mantiene mejora del PMS, piloto operacional y alternativa manual ensayada para picos de demanda.", "Demasiadas apuestas fragmentan capacidad. Cada una necesita dueño, límite, relación y condición de cierre."],
  ["Aprender sin borrar memoria", "Aprendizaje estratégico actualiza decisiones y conserva evidencia de por qué la versión anterior fue razonable bajo otras condiciones.", "Se confunde con reemplazar el plan y perder trazabilidad.", "Baselines, registros de decisión y resultados conectan cambio de rumbo con información nueva, no con relato retrospectivo.", "Se observa si una persona externa puede reconstruir qué se sabía, qué cambió y quién autorizó el nuevo compromiso.", "HH-17 conserva el plan inicial, marca la ambigüedad descubierta y documenta la combinación elegida.", "La memoria no debe inmovilizar. Su función es sostener responsabilidad y evitar repetir una hipótesis descartada."],
 ]]
],
"instrument_title":"Instrumento HH-17: mapa de lógica de intervención",
"instrument_fields":["Decisión y consecuencia","Incertidumbre dominante","Conocimiento estable","Lógica elegida","Hipótesis y mecanismo","Evidencia requerida","Cadencia de revisión","Cadencia de entrega","Compromiso e irreversibilidad","Autoridad","Criterio de salida","Contingencia y aprendizaje"],
"transfer_title":"Caso de transferencia: diagnóstico asistido en una guardia",
"transfer":["Un hospital incorpora apoyo algorítmico para priorizar estudios. La infraestructura, la seguridad y la interoperabilidad requieren anticipación; la interfaz necesita iteración con profesionales; la incorporación puede hacerse por incrementos; las reglas se adaptan a evidencia local; el efecto sobre demoras y desigualdad sólo puede estudiarse con exposición protegida.","Llamar ágil a toda la iniciativa ocultaría obligaciones clínicas y regulatorias. Llamarla predictiva ocultaría aprendizaje sobre uso. HH-17 distribuye lógicas por decisión, exige supervisión, registra discrepancias y establece una puerta antes de ampliar población.","La transferencia muestra que combinar no relativiza rigor. Cada tramo necesita evidencia proporcional al daño posible y una autoridad capaz de detener. El aprendizaje no justifica experimentar cuando no existe reparación."],
"counter_title":"Contraejemplo: experimentar con una obligación ya conocida",
"counter":["Una organización prueba si conviene informar a las personas que una decisión automatizada puede revisarse. Presenta dos versiones del formulario y mide abandono.","La obligación de informar no era incierta. El experimento convierte un derecho en variable de optimización y expone a una parte sin justificación. La pregunta legítima era cómo comunicar con claridad, no si debía comunicar.","El caso limita la lógica experimental. La incertidumbre sobre eficacia no suspende una obligación. Primero se fija la restricción; luego pueden iterarse formas compatibles de cumplirla."],
"errors":["Elegir una etiqueta para todo el proyecto","Confundir iteración con incremento","Usar adaptación como permiso para cambiar sin registro","Experimentar sin hipótesis ni protección","Planificar sólo lo técnico","Acelerar cadencia sin autoridad disponible","Mantener una puerta que nunca puede detener","Llamar híbrido a una suma de ceremonias","Medir actividad en lugar de aprendizaje","Tratar reversibilidad como simple rollback"],
"consequences":"Una estrategia situada permite asignar cada incertidumbre a una forma de aprendizaje, preservar compromisos necesarios y limitar exposición. El profesional deja de defender escuelas y comienza a diseñar decisiones. Puede explicar por qué un contrato requiere anticipación, una regla necesita iteración, una capacidad conviene entregarla por incrementos y una hipótesis sólo admite experimento protegido.",
"limits":"No existe una fórmula universal que transforme incertidumbre en método. Las categorías se superponen y pueden cambiar durante la intervención. La presión comercial, el poder contractual y la disponibilidad de personas condicionan opciones reales. La estrategia debe reconocer esas restricciones sin convertirlas en naturaleza. N18 profundiza precisamente dónde legado, regulación y documentación alteran la libertad de elegir.",
"pills":["No existe una lógica óptima para todas las decisiones.","Iterar mejora una versión; incrementar entrega capacidad utilizable.","Adaptar exige límites, evidencia y memoria.","Experimentar requiere hipótesis, protección y criterio de interrupción.","El compromiso debe crecer con la evidencia y la irreversibilidad."],
"glossary":[["Lógica predictiva","forma de intervención que anticipa compromiso a partir de conocimiento considerado suficiente"],["Iteración","ciclo que revisa una misma solución o representación"],["Incremento","capacidad utilizable que amplía el sistema"],["Adaptación","cambio gobernado de prioridades o prácticas según evidencia"],["Experimento","intervención limitada para distinguir hipótesis"],["Híbrido","combinación explícita de lógicas por decisión"],["Cadencia","frecuencia de revisión, decisión o entrega"],["Compromiso progresivo","aumento de inversión cuando la evidencia supera umbrales"],["Reversibilidad","capacidad de cambiar o volver atrás con costo conocido"],["Puerta de decisión","punto donde una autoridad continúa, modifica, detiene o escala"],["Criterio de salida","evidencia necesaria para cerrar o transferir trabajo"],["Hipótesis de estrategia","afirmación revisable sobre cómo una intervención producirá capacidad"]],
"questions":["¿Qué diferencia una iteración de un incremento?","¿Cuándo una decisión requiere anticipación aunque exista incertidumbre?","¿Qué vuelve defendible una combinación híbrida?","¿Por qué rollback técnico no garantiza reversibilidad?","¿Qué condiciones limitan un experimento?","¿Cómo se diseña una puerta con opción real de detener?"],
"referents":[["Barry Boehm","Vinculó ciclos de desarrollo con reducción progresiva de riesgo."],["Winston Royce","Mostró los límites de una secuencia lineal sin retroalimentación."],["Donald Schön","Explicó la reflexión durante la acción profesional."],["Cynthia Kurtz y David Snowden","Relacionaron formas de decisión con contextos de causalidad y conocimiento diferentes."],["Project Management Institute","Sistematizó el tailoring y el continuo de enfoques predictivos, híbridos y adaptativos."],["Agile Alliance","Consolidó principios para responder al cambio mediante colaboración y entrega frecuente."]],
"references":[
"Boehm, B. W. (1988). ‘A Spiral Model of Software Development and Enhancement’. Computer, 21(5), 61–72. https://doi.org/10.1109/2.59",
"Royce, W. W. (1970). ‘Managing the Development of Large Software Systems’. Proceedings of IEEE WESCON. https://www.cs.umd.edu/class/spring2003/cmsc838p/Process/waterfall.pdf",
"Schön, D. A. (1983). The Reflective Practitioner. Basic Books.",
"Beck, K. et al. (2001). Manifesto for Agile Software Development. https://agilemanifesto.org/",
"Schwaber, K. y Sutherland, J. (2020). The Scrum Guide. https://scrumguides.org/scrum-guide.html",
"Project Management Institute y Agile Alliance (2017). Agile Practice Guide. https://www.pmi.org/standards/agile",
"Project Management Institute (2020). Tailoring Process as Outlined in the PMBOK Guide, Seventh Edition. https://www.pmi.org/-/media/pmi/documents/public/pdf/pmbok-standards/pmbok-tailoring-explainer-20-oct-2020.pdf",
"ISO/IEC/IEEE (2023). ISO/IEC/IEEE 15288:2023 Systems and Software Engineering, System Life Cycle Processes. https://www.iso.org/standard/81702.html",
"ISO/IEC/IEEE (2021). ISO/IEC/IEEE 16085:2021 Systems and Software Engineering, Risk Management. https://www.iso.org/standard/74371.html",
"Kurtz, C. F. y Snowden, D. J. (2003). ‘The New Dynamics of Strategy’. IBM Systems Journal, 42(3), 462–483. https://doi.org/10.1147/sj.423.0462",
"NIST (2023). Artificial Intelligence Risk Management Framework 1.0. https://doi.org/10.6028/NIST.AI.100-1",
"SEBoK (2026). Decision Gate. https://sebokwiki.org/wiki/Decision_Gate_(glossary)"
]
}
}


def compact_doc(*, slug, title, question, opening_title, opening, hotel, advance, defer,
                units, instrument_title, instrument_fields, transfer_title, transfer,
                counter_title, counter, errors, referents, references):
    movements=[]
    for i, movement_title in enumerate([
        "Movimiento 1 · Reconocer condiciones antes de prescribir",
        "Movimiento 2 · Diseñar opciones con evidencia y autoridad",
        "Movimiento 3 · Gobernar transición, aprendizaje y retiro",
    ]):
        movements.append([movement_title, units[i*4:(i+1)*4]])
    return {
        "slug":slug,"title":title,"question":question,"opening_title":opening_title,
        "opening":opening,"hotel":hotel,"advance":advance,"defer":defer,"movements":movements,
        "instrument_title":instrument_title,"instrument_fields":instrument_fields,
        "transfer_title":transfer_title,"transfer":transfer,"counter_title":counter_title,"counter":counter,
        "errors":errors,"consequences":advance+" Esta capacidad permite discutir costo, riesgo y responsabilidad sin esconder decisiones detrás de una etiqueta técnica.",
        "limits":"La evidencia nunca elimina por completo el juicio. Restricciones legales, relaciones de poder, capacidad operativa y costos hundidos reducen el espacio de opciones. El instrumento debe hacer visibles esas condiciones y conservar una vía de revisión, no prometer neutralidad.",
        "pills":[u[1] for u in units[:5]],
        "glossary":[[u[0],u[1][0].lower()+u[1][1:]] for u in units[:12]],
        "questions":[f"¿Qué decisión permite sostener {u[0].lower()} y qué evidencia podría refutarla?" for u in units[:6]],
        "referents":referents,"references":references,
    }


DOCS.update({
18: compact_doc(
 slug="legado_regulacion_y_documentacion_como_valor_restriccion_y_evidencia",
 title="Legado, regulación y documentación como valor, restricción y evidencia",
 question="¿Cómo intervenir sobre un sistema heredado sin confundir lo viejo con lo inútil, la norma con el trámite ni la documentación con una copia de la realidad?",
 opening_title="La regla que nadie encontraba y todos obedecían",
 opening=[
  "Hotel Horizonte decide reemplazar una interfaz antigua usada para reasignar habitaciones. El formulario parece redundante, duplica datos y exige una confirmación telefónica. El equipo propone eliminarlo en el primer incremento porque no encuentra esa secuencia en el manual vigente.",
  "Durante la prueba, una recepcionista explica que la llamada evita cambiar una habitación accesible ya prometida por Comercial. La regla nació después de una queja grave, quedó codificada en permisos del PMS y se sostuvo mediante capacitación oral. La documentación describe el camino ordinario; el legado conserva una obligación que dejó de ser visible.",
  "Conservar todo por temor inmovilizaría el servicio. Eliminar todo por modernidad borraría evidencia y control. El problema no es decidir si el legado es bueno o malo, sino reconstruir qué conocimiento, dependencia, derecho y riesgo contiene cada pieza.",
  "El equipo abre un expediente. Vincula código, configuración, procedimiento, resolución, casos recientes y personas que ejecutan excepciones. Distingue requisito vigente, solución histórica, deuda, adaptación local y residuo sin uso. Recién entonces diseña una transición.",
  "La documentación cambia de función. Ya no intenta fotografiar todo el sistema. Registra decisiones, obligaciones, interfaces, pruebas y condiciones de retiro. La regulación tampoco aparece como barrera externa: organiza quién puede decidir, qué debe demostrarse y qué daño no puede aceptarse.",
  "N18 recibe de HH-17 una lógica de intervención y la somete a la realidad instalada. Enseña que el pasado está presente en datos, contratos, hábitos, infraestructura y expectativas, y que transformar exige conocer qué se puede cambiar, qué debe preservarse y qué necesita autorización."
 ],
 hotel="HH-17 proponía iterar reglas y entregar capacidad por pisos. HH-18 agrega una restricción: el PMS, la cerradura, los contratos de canal y las prácticas de Recepción contienen decisiones tomadas en momentos diferentes. El expediente separa obligación actual, solución heredada, excepción útil, dependencia accidental y documentación faltante. La estrategia conserva la protección de accesibilidad, reemplaza la llamada por una verificación trazable y mantiene un circuito manual hasta demostrar cobertura.",
 advance="N18 convierte legado, regulación y documentación en objetos de análisis con valor, costo, evidencia y ciclo de vida. La modernización deja de significar sustitución automática y pasa a ser una decisión de continuidad responsable.",
 defer="N19 evaluará alternativas de realización y abastecimiento. N18 no decide todavía si conviene construir, configurar, integrar, tercerizar, mantener trabajo manual o no automatizar.",
 units=[
  ["Legado sociotécnico","El legado es capacidad instalada, conocimiento, dependencia y compromiso acumulado, no sólo tecnología antigua.","Se confunde antigüedad con obsolescencia y novedad con adecuación.","Código, datos, contratos, rutinas y expectativas se estabilizan mutuamente y hacen costoso un cambio local.","Inventarios, incidentes, trazas, entrevistas y decisiones pasadas muestran qué sostiene realmente la operación.","La pantalla vieja contiene una validación de accesibilidad ausente en el rediseño.","Conservar sin evaluar perpetúa daño; reemplazar sin comprender puede eliminar una protección."],
  ["Arqueología del sistema","La arqueología reconstruye por qué existe una pieza y qué consecuencias produce hoy.","No es nostalgia ni documentación retrospectiva exhaustiva.","Conecta versiones, commits, tickets, manuales, contratos, relatos y episodios para formular hipótesis contrastables.","Una cadena de evidencia debe permitir distinguir decisión deliberada de accidente sedimentado.","Un campo obligatorio nació para cumplir un reporte ya derogado, pero hoy alimenta conciliación.","Si no aparece propósito vigente, se prueba retiro controlado en lugar de asumir inutilidad."],
  ["Deuda técnica y deuda institucional","La deuda es una obligación futura creada por una decisión presente que reduce costo o tiempo inmediato.","No todo legado es deuda y no toda deuda es código deficiente.","Intereses aparecen como demora, fragilidad, dependencia de personas, riesgo regulatorio o incapacidad de aprender.","Se estima mediante frecuencia de cambio, incidentes, esfuerzo de comprensión y consecuencias acumuladas.","Una regla duplicada acelera una entrega y exige reconciliación manual cada noche.","La metáfora financiera falla si oculta quién paga o sugiere que toda deuda debe cancelarse."],
  ["Acoplamiento y radio de impacto","El acoplamiento expresa cuánto depende una capacidad de elementos que cambian juntos.","Se confunde con conexión visible o cantidad de interfaces.","Dependencias semánticas, temporales, organizacionales y contractuales propagan cambios más allá del componente.","Pruebas de impacto, trazas y fallas históricas revelan rutas que el diagrama no muestra.","Renombrar un estado altera tablero, canal, capacitación y compensaciones.","Desacoplar puede trasladar complejidad a contratos y monitoreo; no siempre reduce riesgo total."],
  ["Regulación como requisito de diseño","La regulación define derechos, obligaciones, evidencia y autoridad que la solución debe realizar.","No equivale a una lista de controles agregada al final.","Una obligación se transforma en decisiones de proceso, datos, interfaz, retención, revisión y reparación.","La conformidad exige trazabilidad desde norma aplicable hasta implementación y prueba.","El derecho a revisión necesita canal, plazo, evidencia accesible y autoridad efectiva.","Cumplir literalmente puede seguir produciendo daño si la capacidad sólo existe en papel."],
  ["Interpretación normativa","Interpretar una norma consiste en determinar alcance y consecuencia con autoridad competente.","No es tarea exclusiva del área legal ni una traducción mecánica a requisito.","Casos, jurisdicción, contratos y diseño interactúan; las ambigüedades requieren decisión registrada.","Dictámenes, precedentes, consultas y pruebas de operación sostienen una interpretación revisable.","Una regla de retención cambia según finalidad y población, no por preferencia técnica.","El equipo no inventa permiso ante silencio; escala la incertidumbre y limita exposición."],
  ["Documentación como interfaz","La documentación coordina personas, decisiones y artefactos a través del tiempo.","No es un espejo completo ni un entregable administrativo autónomo.","Selecciona información para que una audiencia pueda actuar, verificar, mantener o reparar.","Se valida observando si otra persona ejecuta una decisión correcta sin explicación oral privilegiada.","Una ficha de excepción enlaza regla, responsable, evidencia, contingencia y fecha de revisión.","Más páginas pueden disminuir utilidad si mezclan vigencia, audiencias y niveles."],
  ["Información de ciclo de vida","La información de ciclo de vida conserva lo necesario para concebir, operar, sostener y retirar una capacidad.","No coincide con documentos producidos por fase ni con un repositorio indiscriminado.","Cada decisión genera evidencia con dueño, vigencia, acceso y condición de actualización.","La cobertura se prueba desde una pregunta operacional hasta la fuente que permite responderla.","Retirar un servicio exige conocer consumidores, datos, obligaciones y ruta de recuperación.","Conservar todo sin clasificación crea ambigüedad y aumenta superficie de riesgo."],
  ["Migración de datos como decisión semántica","Migrar datos significa preservar significado y uso autorizado, no sólo copiar registros.","Se confunde integridad sintáctica con continuidad de evidencia.","Mapeos, transformaciones y reglas de calidad pueden cambiar identidad, tiempo y población.","Reconciliaciones, muestras adversas y pruebas de decisiones verifican lo que sobrevivió.","Un estado histórico se transforma en dos y altera métricas de demora.","Algunos datos no deben migrarse por propósito, minimización o riesgo; la ausencia necesita explicación."],
  ["Excepciones heredadas","Una excepción heredada es una desviación estabilizada que puede contener conocimiento, privilegio o daño.","No debe celebrarse como experiencia ni eliminarse como anomalía sin investigación.","Aparece cuando el camino formal no absorbe una condición y la organización crea una ruta paralela.","Frecuencia, población, autoridad, resultado y reparación permiten clasificarla.","La llamada de Recepción protege accesibilidad y también depende de memoria individual.","Formalizar una excepción injusta consolida el problema; automatizarla puede escalarlo."],
  ["Seguridad y mantenibilidad","La mantenibilidad incluye cambiar con comprensión, prueba y recuperación, mientras seguridad limita exposición y abuso.","Se confunden con cualidades técnicas separadas del trabajo organizacional.","Componentes sin soporte, credenciales compartidas y conocimiento tácito amplían consecuencias de falla.","Inventario, vulnerabilidades, tiempos de parche, pruebas de restauración y segregación aportan evidencia.","Un conector estable depende de una biblioteca sin mantenimiento y una única persona.","Actualizar por versión puede romper controles; no actualizar puede acumular riesgo intolerable."],
  ["Inteligencia artificial sobre sistemas heredados","La IA puede asistir comprensión y transformación, pero produce hipótesis que requieren procedencia y validación.","Se confunde síntesis plausible con conocimiento del sistema.","Modelos generativos infieren documentación, mapeos o pruebas desde artefactos incompletos y pueden amplificar omisiones.","Comparación con ejecución, revisión experta, pruebas adversas y registro de fuentes miden utilidad.","Un asistente propone reglas desde código y omite la práctica telefónica que nunca fue registrada.","Datos sensibles, propiedad intelectual y dependencia de proveedor pueden volver improcedente su uso."],
 ],
 instrument_title="Instrumento HH-18: expediente de obligación y legado",
 instrument_fields=["Elemento heredado","Capacidad que sostiene","Decisión de origen","Obligación vigente","Dependencias","Evidencia disponible","Personas que conocen","Riesgo de cambio","Riesgo de conservar","Documentación mínima","Transición y contingencia","Prueba y condición de retiro"],
 transfer_title="Caso de transferencia: expediente clínico que cambia de plataforma",
 transfer=["Una red de salud migra historias clínicas. La estructura vieja mezcla episodios, autorizaciones y notas libres. Parte parece ruido, pero permite reconstruir alergias y decisiones de medicación.","HH-18 separa datos necesarios, obligaciones de conservación, transformaciones, accesos y evidencia de uso. La migración se prueba con episodios adversos y con profesionales que no participaron del diseño.","El caso muestra que continuidad no es copiar todo. Es preservar capacidad legítima de atención, explicación y reparación mientras se retira lo que ya no posee finalidad."],
 counter_title="Contraejemplo: documentar cada pantalla y perder la decisión",
 counter=["Un programa exige manuales exhaustivos antes de modernizar. Cada pantalla queda capturada y cada campo descrito.","El material no explica por qué existe una excepción, quién puede autorizarla ni qué decisión usa el dato. Cuando cambia la interfaz, miles de páginas quedan viejas y nadie puede evaluar impacto.","La cobertura formal produjo menos conocimiento. La documentación útil se organiza por decisiones, obligaciones, interfaces y pruebas, no por volumen."],
 errors=["Tratar todo lo viejo como deuda","Conservar por miedo sin registrar valor","Traducir normas en casillas aisladas","Documentar la interfaz y omitir decisiones","Migrar registros sin preservar significado","Formalizar excepciones antes de evaluarlas","Depender de una persona como control","Actualizar componentes sin prueba de impacto","Usar IA como autoridad arqueológica","Retirar sin conservar memoria suficiente"],
 referents=[["Manny Lehman","Estudió la evolución continua de sistemas usados en entornos reales."],["David Parnas","Mostró el valor de ocultar decisiones y diseñar para el cambio."],["Ward Cunningham","Introdujo la metáfora de deuda técnica para discutir costo diferido."],["Michael Feathers","Desarrolló prácticas para cambiar código heredado bajo pruebas."],["ISO/IEC/IEEE","Establece procesos e información del ciclo de vida de sistemas y software."],["NIST","Integra desarrollo seguro, procedencia y riesgo de cadena de suministro."]],
 references=["Lehman, M. M. (1980). ‘Programs, Life Cycles, and Laws of Software Evolution’. Proceedings of the IEEE, 68(9), 1060–1076. https://doi.org/10.1109/PROC.1980.11805","Parnas, D. L. (1972). ‘On the Criteria to Be Used in Decomposing Systems into Modules’. Communications of the ACM, 15(12), 1053–1058. https://doi.org/10.1145/361598.361623","Feathers, M. (2004). Working Effectively with Legacy Code. Prentice Hall.","ISO/IEC/IEEE (2026). ISO/IEC/IEEE 12207:2026 Software Life Cycle Processes. https://www.iso.org/standard/90219.html","ISO/IEC/IEEE (2019). ISO/IEC/IEEE 15289:2019 Content of Life Cycle Information Items. https://www.iso.org/standard/74909.html","ISO/IEC/IEEE (2023). ISO/IEC/IEEE 15288:2023 System Life Cycle Processes. https://www.iso.org/standard/81702.html","European Union (2016). General Data Protection Regulation. https://eur-lex.europa.eu/eli/reg/2016/679/oj","European Union (2024). Artificial Intelligence Act. https://eur-lex.europa.eu/eli/reg/2024/1689/oj","NIST (2022). Secure Software Development Framework 1.1. https://doi.org/10.6028/NIST.SP.800-218","NIST (2024). Secure Software Development Practices for Generative AI. https://doi.org/10.6028/NIST.SP.800-218A.ipd","CISA (2023). Secure by Design. https://www.cisa.gov/securebydesign","W3C (2013). PROV Overview. https://www.w3.org/TR/prov-overview/"]
),
19: compact_doc(
 slug="alternativas_de_realizacion_configurar_integrar_construir_y_no_automatizar",
 title="Alternativas de realización: configurar, integrar, construir y no automatizar",
 question="¿Cómo elegir una forma de realizar capacidad sin reducir la decisión a construir o comprar y sin trasladar riesgos invisibles a proveedores, operación o personas?",
 opening_title="La compra que evitaba desarrollar y creó un sistema nuevo",
 opening=["Hotel Horizonte selecciona una plataforma integral para reservas, habitaciones y comunicación. La propuesta promete mejores prácticas, implementación rápida y menor mantenimiento. La comparación se presenta como comprar algo probado o construir desde cero.","Después de adjudicar, aparecen decisiones omitidas. La plataforma no modela la autoridad local para excepciones, el canal exige cambiar contratos y los datos de cerraduras necesitan una integración específica. Para conservar la promesa comercial se agregan configuraciones, conectores y trabajo manual.","La organización no compró una capacidad terminada. Compró opciones, restricciones, dependencias y una relación de suministro que debe diseñarse. Parte del valor está en lo estándar; parte del riesgo nace en la adaptación. La disyuntiva original ocultó el sistema de trabajo necesario para hacer operable el producto.","El equipo amplía el espacio de decisión. Puede configurar, integrar, construir componentes, contratar un servicio gestionado, mantener una operación manual temporal o decidir no automatizar una excepción rara y riesgosa. Cada opción se evalúa por consecuencia total, no por precio inicial.","La arquitectura de N15 y la coherencia de N16 permiten localizar fronteras. HH-18 aporta obligaciones y legado. N19 reúne esas evidencias en un expediente de realización con costo de vida, dependencia, control, reversibilidad y salida.","La elección deja de premiar una identidad tecnológica. Su pregunta es qué capacidad debe conservar la organización, qué puede delegar, qué evidencia necesita del proveedor y cómo reparará cuando la relación o el producto fallen."],
 hotel="El hotel compara seis rutas para la confirmación condicional: configurar reglas del PMS, integrar cerraduras, construir un servicio de decisión, contratar operación gestionada, sostener una verificación manual o no automatizar casos excepcionales. HH-19 muestra que ninguna domina en todo. La opción elegida combina estándar para lo común, integración para evidencia, operación manual protegida para bordes y una condición contractual de portabilidad y salida.",
 advance="N19 transforma la adquisición en diseño sociotécnico. Amplía alternativas y compara capacidad, costo total, control, dependencia, seguridad, evidencia, reversibilidad y reparación durante todo el ciclo de vida.",
 defer="N20 tomará la opción seleccionada y compondrá una estrategia metodológica con tailoring, hitos y condiciones de salida. N19 no convierte la elección en plan de ejecución.",
 units=[
  ["Capacidad antes que solución","La decisión comienza por la capacidad que debe existir y no por el catálogo de productos.","Se confunde necesidad con funcionalidad ofrecida.","Definir resultado, actores, evidencia y reparación evita que una opción conveniente cambie silenciosamente el problema.","Escenarios y criterios de aceptación muestran qué debe sostenerse con independencia del proveedor.","El hotel necesita confirmar entrega defendible, no adquirir un motor de reglas.","Una capacidad demasiado abstracta impide comparar; debe expresarse en episodios y consecuencias."],
  ["Espacio de opciones","El espacio de opciones incluye construir, configurar, integrar, contratar, operar manualmente y no automatizar.","Se confunde amplitud con indecisión.","Variantes combinables permiten localizar qué parte necesita diferenciación y cuál puede estandarizarse.","Una matriz explícita muestra supuestos, exclusiones y dependencias de cada ruta.","La regla común se configura y la excepción accesible conserva revisión humana.","Demasiadas opciones consumen análisis; se eliminan sólo con criterios trazables."],
  ["Configurar","Configurar adapta comportamiento mediante mecanismos previstos por un producto.","No equivale a personalizar código ni a aceptar toda práctica del proveedor.","Reduce desarrollo propio y conserva actualización si la necesidad cabe en puntos de variación soportados.","Pruebas de upgrade, límites y exportación verifican sostenibilidad.","Estados y permisos estándar cubren la mayoría de reservas.","Configuraciones extremas pueden ser código oculto y crear dependencia difícil de comprender."],
  ["Integrar","Integrar coordina componentes mediante contratos sintácticos, semánticos, temporales y operacionales.","No es sólo conectar APIs.","La capacidad emerge de correspondencias, secuencias, observabilidad, autoridad y manejo de fallas parciales.","Pruebas end-to-end y reconciliación muestran si la promesa sobrevive a demora y duplicación.","Cerradura, PMS y comunicación producen una confirmación conjunta.","Más componentes pueden aumentar opciones y también multiplicar puntos de falla y responsabilidades difusas."],
  ["Construir","Construir crea control directo sobre una capacidad cuando su diferenciación o restricción lo justifica.","No significa independencia total ni desarrollo artesanal de todo.","Permite diseñar reglas y evolución propias, pero exige equipos, seguridad, operación y mantenimiento sostenidos.","Costo de cambio, calidad, tiempo de recuperación y continuidad de conocimiento revelan viabilidad.","Un servicio pequeño concentra la decisión que ningún producto representa.","Control sin capacidad organizacional produce software propio que nadie puede sostener."],
  ["Servicio gestionado y tercerización","Tercerizar delega actividades bajo acuerdos sin transferir responsabilidad por el outcome.","Se confunde contrato con control efectivo.","Niveles de servicio, evidencia, escalamiento, acceso y cooperación en incidentes organizan la relación.","Pruebas de crisis y reportes verificables muestran si el proveedor puede responder.","Un servicio opera comunicaciones nocturnas con supervisión del hotel.","El contrato no repara por sí mismo; la organización necesita capacidad para gobernar al proveedor."],
  ["Trabajo manual deliberado","Una operación manual puede ser una solución legítima cuando volumen, variabilidad o consecuencia no justifican automatización.","Se confunde con atraso o parche vergonzante.","Personas interpretan contexto y excepciones, aunque introducen demora, carga, variación y dependencia.","Tiempos, errores, bienestar, cobertura y capacidad de escalamiento permiten evaluar.","Recepción verifica manualmente casos raros durante la transición.","Si el trabajo invisible recae siempre en el mismo grupo, la aparente flexibilidad distribuye daño."],
  ["No automatizar","No automatizar es una decisión positiva de límite cuando automatizar ampliaría daño, vigilancia o rigidez.","No equivale a abandonar la mejora.","Puede simplificar reglas, eliminar demanda o rediseñar servicio antes de informatizar.","La evidencia compara beneficio marginal con costo, riesgo y pérdida de discreción legítima.","El hotel no automatiza compensaciones excepcionales y conserva revisión con autoridad.","La decisión requiere revisión futura; no debe proteger ineficiencia o arbitrariedad."],
  ["Costo total de vida","El costo total incluye adquisición, integración, operación, cambio, riesgo, salida y reparación.","Se confunde con precio, horas de desarrollo o suscripción.","Costos diferidos y transferidos cambian qué opción resulta económica para la organización y afectados.","Escenarios de crecimiento, incidente, auditoría y retiro hacen visibles obligaciones.","Una licencia barata exige conectores y conciliación permanente.","Toda estimación es incierta; importa comparar supuestos y sensibilidad, no fingir precisión."],
  ["Dependencia y poder de proveedor","La dependencia aparece cuando cambiar de proveedor exige costos o permisos que limitan decisión futura.","No toda relación estable es lock-in abusivo.","Datos, formatos, identidad, conocimiento, integraciones y cláusulas acumulan costos de salida.","Una prueba de exportación y sustitución revela control real.","El hotel ensaya recuperar reservas, reglas y auditoría en formato utilizable.","Portabilidad contractual sin capacidad técnica es promesa vacía; duplicar proveedores puede aumentar complejidad."],
  ["Riesgo de cadena de suministro","La cadena de suministro incluye componentes, servicios, personas y procesos externos que afectan seguridad y continuidad.","Se confunde evaluación inicial con gobierno permanente.","Vulnerabilidades, actualizaciones, subcontratación y cambios de propiedad alteran exposición durante el uso.","SBOM, atestaciones, monitoreo e incidentes aportan evidencia incompleta pero útil.","Una biblioteca del conector introduce una falla crítica.","Exigir listas sin capacidad de actuar produce cumplimiento documental y no reducción de riesgo."],
  ["Adquisición de inteligencia artificial","Adquirir IA implica evaluar modelo, datos, integración, supervisión, desempeño, dependencia y reparación.","Se confunde demo convincente con capacidad operacional.","El comportamiento probabilístico y el cambio del proveedor requieren evaluación continua y límites de autoridad.","Casos representativos, grupos afectados, drift, seguridad y posibilidad de apelación sostienen la decisión.","Un asistente redacta mensajes pero no confirma estados ni promete compensaciones.","Si no puede obtenerse evidencia suficiente o salida practicable, la opción puede ser no usar IA."],
 ],
 instrument_title="Instrumento HH-19: expediente de opciones de realización",
 instrument_fields=["Capacidad y outcome","Frontera diferenciadora","Opciones consideradas","Supuestos","Costo total","Tiempo para aprender","Control y autoridad","Dependencias","Seguridad y suministro","Operación y reparación","Portabilidad","Prueba y salida"],
 transfer_title="Caso de transferencia: plataforma universitaria de alertas",
 transfer=["Una universidad quiere identificar estudiantes que necesitan apoyo. Puede comprar una plataforma predictiva, configurar reglas, integrar datos existentes, construir un modelo, operar revisión manual o no automatizar la clasificación.","HH-19 separa capacidad de acompañamiento y mecanismo de puntuación. Evalúa privacidad, evidencia, sesgo, capacidad docente, apelación y salida. Una opción combinada usa reglas transparentes para convocar y reserva decisiones a equipos con contexto.","La transferencia muestra que comprar tecnología no compra legitimidad ni capacidad institucional. La alternativa adecuada puede incluir menos automatización y más rediseño del servicio."],
 counter_title="Contraejemplo: construir para evitar dependencia y depender de tres personas",
 counter=["Una empresa rechaza proveedores para conservar control y desarrolla su propia plataforma.","Tres especialistas concentran arquitectura, despliegue y conocimiento. Cuando dos se van, la organización no puede actualizar ni auditar. Evitó lock-in comercial y creó dependencia laboral extrema.","La frontera no es propio contra ajeno. Es capacidad gobernable, conocimiento distribuido, evidencia y salida real."],
 errors=["Empezar por una demo","Comparar precio y omitir ciclo de vida","Llamar estándar a toda práctica del proveedor","Integrar sin contratos semánticos","Construir sin capacidad de operar","Tercerizar responsabilidad","Ocultar trabajo manual","Automatizar una excepción rara","Aceptar portabilidad sin probarla","Evaluar IA sólo por precisión"],
 referents=[["Ronald Coase","Explicó por qué las fronteras de la organización dependen de costos de coordinación."],["Oliver Williamson","Desarrolló el análisis de gobernanza y costos de transacción."],["Carliss Baldwin y Kim Clark","Mostraron cómo modularidad y opciones estructuran decisiones de diseño."],["Martin Fowler","Contribuyó a comprender integración, patrones y costos evolutivos."],["NIST","Desarrolla prácticas de riesgo para adquisición y cadena de suministro."],["CISA","Promueve demanda segura y evaluación de proveedores de software."]],
 references=["Coase, R. H. (1937). ‘The Nature of the Firm’. Economica, 4(16), 386–405. https://doi.org/10.1111/j.1468-0335.1937.tb00002.x","Williamson, O. E. (1985). The Economic Institutions of Capitalism. Free Press.","Baldwin, C. Y. y Clark, K. B. (2000). Design Rules. MIT Press.","Fowler, M. (2002). Patterns of Enterprise Application Architecture. Addison-Wesley.","NIST (2022). Cybersecurity Supply Chain Risk Management Practices, SP 800-161 Rev. 1. https://doi.org/10.6028/NIST.SP.800-161r1","NIST (2022). Software Security in Supply Chains. https://www.nist.gov/itl/executive-order-14028-improving-nations-cybersecurity/software-security-supply-chains","CISA (2025). Software Acquisition Guide for Government Enterprise Consumers. https://www.cisa.gov/resources-tools/resources/software-acquisition-guide-government-enterprise-consumers","NTIA (2021). Software Bill of Materials. https://www.ntia.gov/page/software-bill-materials","ISO/IEC (2022). ISO/IEC 27036-3:2022 Supplier Relationships, ICT Supply Chain Security. https://www.iso.org/standard/59688.html","European Union (2023). Data Act. https://eur-lex.europa.eu/eli/reg/2023/2854/oj","NIST (2023). Artificial Intelligence Risk Management Framework 1.0. https://doi.org/10.6028/NIST.AI.100-1","FinOps Foundation (2025). FinOps Framework. https://www.finops.org/framework/"]
),
20: compact_doc(
 slug="estrategia_metodologica_tailoring_hitos_y_condiciones_de_salida",
 title="Estrategia metodológica: tailoring, hitos y condiciones de salida",
 question="¿Cómo componer una estrategia que coordine aprendizaje, entrega, gobierno y retiro sin convertir el método en receta ni la adaptación en improvisación?",
 opening_title="El proyecto que tenía todas las prácticas y ninguna salida",
 opening=["Hotel Horizonte reúne todo lo aprendido: evidencia, actores, procesos, estados, modelos, contradicciones, legado y opciones de realización. El equipo arma una estrategia con descubrimiento, sprints, arquitectura, comité, piloto, tablero, retrospectivas y auditoría. Ninguna práctica parece incorrecta.","A los cuatro meses, todas siguen activas. El descubrimiento produce nuevos hallazgos sin cerrar preguntas. Los sprints entregan configuraciones que el piloto no absorbe. El comité revisa informes y nunca detiene. La auditoría solicita evidencia que nadie vinculó con decisiones. La abundancia metodológica creó trabajo sin arquitectura de compromiso.","El problema no es elegir una práctica mejor, sino definir para qué función existe cada una, qué información consume, qué decisión habilita y cuándo deja de ser necesaria. Una estrategia situada necesita forma temporal, autoridad y condiciones de salida.","El equipo reconstruye el recorrido desde la promesa. Conserva investigación hasta resolver tres incertidumbres, limita el piloto a una población, fija puertas de decisión y asigna responsables. El trabajo técnico no comienza donde falta obligación; la expansión no ocurre donde falta reparación; una práctica se retira cuando su función ya está cubierta.","El tailoring deja de ser recorte de ceremonias. Se convierte en diseño argumentado de procesos, evidencias, ritmos y controles según contexto. Cada adaptación registra motivo, riesgo, compensación y revisión.","N20 cierra el Bloque D. Integra HH-17, HH-18 y HH-19 en HH-20, una estrategia metodológica que puede ejecutarse, cuestionarse y terminar. Su producto no es un plan perfecto, sino una secuencia gobernada de compromisos y aprendizaje."],
 hotel="HH-20 combina una baseline predictiva para obligaciones e integración, iteraciones sobre reglas, incrementos por capacidad, adaptación de prioridades y experimentos protegidos. Incorpora legado, contratos y trabajo manual. Define cinco puertas: comprender, elegir, preparar, ampliar y transferir. Cada una tiene evidencia, autoridad, contingencia y criterio de salida. La estrategia termina cuando operación puede sostener la promesa y revisar sus propios supuestos.",
 advance="N20 compone una estrategia metodológica situada: selecciona procesos por función, adapta intensidad al riesgo, conecta hitos con evidencia y define entrada, salida, detención, transferencia y retiro.",
 defer="N21 abrirá el Bloque E distinguiendo proyecto, producto, servicio y plataforma. N20 entrega una capacidad intervenida y gobernable sin decidir todavía qué objeto de gestión conviene privilegiar.",
 units=[
  ["Estrategia como hipótesis","Una estrategia afirma cómo una combinación de acciones producirá capacidad bajo condiciones explícitas.","Se confunde con plan, cronograma o catálogo de prácticas.","Vincula mecanismo, evidencia, riesgos y decisiones en una secuencia refutable.","Señales tempranas y resultados adversos permiten revisar antes del cierre.","El hotel espera reducir espera sin aumentar reasignaciones ni inequidad.","Una buena ejecución no valida una hipótesis si el outcome cambió por otra causa."],
  ["Tailoring por función","Tailoring selecciona y adapta procesos según la función que deben cumplir.","No es eliminar controles para acelerar ni copiar un marco parcialmente.","Comprender, decidir, coordinar, verificar, aprender y gobernar exigen prácticas y evidencias diferentes.","Una matriz función práctica muestra cobertura, duplicación y huecos.","La entrevista produce evidencia; la puerta autoriza compromiso; la retrospectiva revisa mecanismo.","Reducir forma sin reemplazar función crea una ausencia invisible."],
  ["Factores situacionales","Los factores situacionales son condiciones que modifican qué estrategia resulta defendible.","No son excusas contextuales ni una lista decorativa.","Consecuencia, incertidumbre, regulación, legado, escala, distribución y capacidad cambian intensidad y secuencia.","Episodios y restricciones verificables sostienen la caracterización.","Una operación permanente exige recuperación distinta de un prototipo interno.","Clasificar mal el contexto puede legitimar exceso de control o exposición imprudente."],
  ["Arquitectura de decisiones","La arquitectura de decisiones ordena qué debe decidirse, por quién, con qué evidencia y dependencia.","No coincide con estructura de reuniones.","Decisiones irreversibles o habilitantes preceden compromisos que dependen de ellas.","Un mapa de dependencias y autoridad revela cuellos y decisiones huérfanas.","No se comunica una promesa antes de validar capacidad y reparación.","Ordenar todo en serie alarga flujo; decisiones independientes pueden avanzar concurrentemente."],
  ["Hitos con consecuencia","Un hito es un estado verificable que habilita, limita o cambia decisiones posteriores.","No es una fecha, una presentación ni una actividad terminada.","Condensa evidencia suficiente y vuelve explícito el compromiso que ahora puede asumirse.","Criterios observables, responsables y decisión registrada demuestran su realidad.","El piloto está listo cuando personal, monitoreo y contingencia funcionan juntos.","Un hito sin alternativa de acción es ceremonia y puede ocultar atraso."],
  ["Criterios de entrada","Los criterios de entrada protegen una actividad de comenzar sin condiciones mínimas.","No son requisitos de perfección previa.","Aseguran propósito, materiales, autoridad y capacidad para aprender o reparar.","Una revisión rápida verifica evidencia y excepciones antes de consumir recursos.","El experimento requiere población, consentimiento, fallback y monitoreo.","Criterios rígidos pueden bloquear investigación; deben corresponder al riesgo de la actividad."],
  ["Criterios de salida","Los criterios de salida definen qué evidencia permite cerrar, transferir, ampliar o detener.","No equivalen a completar tareas ni gastar presupuesto.","Conectan trabajo con decisión y evitan que una práctica continúe por inercia.","Pruebas de outcome, estabilidad, comprensión y operación sostienen el cierre.","La expansión exige menor espera y ninguna pérdida de protección accesible.","Un criterio puede revisarse, pero el cambio necesita autoridad y registro."],
  ["Condición de detención","Una condición de detención establece cuándo el daño, la falta de aprendizaje o el costo vuelven improcedente continuar.","No es pesimismo ni fracaso.","Limita exposición antes de que costo hundido capture la decisión.","Umbrales de seguridad, equidad, desempeño y capacidad deben monitorearse.","Tres entregas fallidas suspenden el piloto y activan retorno manual.","Detener sin aprender desperdicia evidencia; se conserva causa y decisión."],
  ["Cadencia de evidencia","La cadencia de evidencia es el ritmo con que una estrategia puede conocer y revisar su desempeño.","No coincide necesariamente con sprint, reporte o despliegue.","Alinea observación con la velocidad del fenómeno y el tiempo de daño.","Latencia, calidad y uso de señales muestran si la revisión llega a tiempo.","Fraude se observa de inmediato y adopción necesita semanas.","Medir demasiado pronto produce ruido; medir tarde normaliza consecuencias."],
  ["Gobierno proporcional","El gobierno proporcional asigna autoridad y control según consecuencia, incertidumbre e irreversibilidad.","No es menos gobierno por defecto ni comité para todo.","Decisiones locales preservan fluidez y escalamiento protege compromisos críticos.","Tiempos de decisión, excepciones y reparaciones permiten auditar diseño.","Recepción resuelve casos ordinarios y escala cambios de promesa.","Centralizar puede silenciar contexto; distribuir sin límites puede producir arbitrariedad."],
  ["Transferencia a operación","Transferir significa que una capacidad puede sostenerse con roles, conocimiento, recursos, monitoreo y reparación.","No es desplegar ni entregar documentación.","Operación participa antes, practica escenarios y acepta obligaciones explícitas.","Pruebas de guardia, recuperación y decisión sin el equipo creador verifican autonomía.","Un turno nocturno resuelve una excepción sin llamadas privadas.","Transferir demasiado temprano desplaza deuda; nunca transferir perpetúa dependencia del proyecto."],
  ["Retiro de la estrategia","Retirar prácticas y estructuras temporales es parte del diseño metodológico.","Se confunde cierre administrativo con desaparición de capacidad.","Funciones permanentes pasan a operación y mecanismos de aprendizaje conservan dueño.","Inventarios, accesos, rituales y contratos muestran qué debe terminar o continuar.","El comité del piloto se disuelve y la revisión de indicadores queda integrada en operación.","Mantener todo agrega burocracia; retirar memoria elimina responsabilidad."],
 ],
 instrument_title="Instrumento HH-20: estrategia metodológica situada",
 instrument_fields=["Outcome y población","Hipótesis estratégica","Factores situacionales","Decisiones y dependencias","Lógicas por tramo","Prácticas por función","Evidencia y cadencia","Hitos","Entrada y salida","Autoridad y escalamiento","Detención y contingencia","Transferencia, revisión y retiro"],
 transfer_title="Caso de transferencia: implementación de una política de evaluación",
 transfer=["Una facultad cambia el régimen de evaluación. La norma fija obligaciones, pero actividades, plataformas, accesibilidad y capacidad docente requieren adaptación.","HH-20 organiza decisiones, piloto, formación, soporte y revisión. Define qué puede variar por curso y qué permanece como derecho común. La puerta de ampliación exige evidencia de comprensión y posibilidad de reparación.","La transferencia muestra que una estrategia metodológica no pertenece sólo a software. Coordina cambio institucional, trabajo, evidencia y autoridad sin confundir uniformidad con coherencia."],
 counter_title="Contraejemplo: la transformación que nunca termina",
 counter=["Una organización declara transformación continua y conserva cada ceremonia, comité y tablero creado durante cinco años.","Nadie puede decir qué hipótesis sigue abierta ni qué estructura es temporal. La adaptación se vuelve identidad y el costo metodológico deja de discutirse.","HH-20 exige salida y retiro. Aprender continuamente no significa sostener indefinidamente todos los dispositivos de cambio."],
 errors=["Elegir prácticas antes de funciones","Llamar hito a una fecha","Iniciar sin autoridad ni contingencia","Cerrar por actividad completada","Cambiar criterios después de ver el resultado","Medir con una única cadencia","Centralizar toda decisión","Transferir sólo archivos","Mantener estructuras temporales","Usar tailoring para ocultar pérdida de rigor"],
 referents=[["Project Management Institute","Formalizó tailoring y dominios de desempeño orientados a valor."],["ISO/IEC/IEEE","Define procesos de ciclo de vida aplicables de manera iterativa y adaptada."],["Barry Boehm","Vinculó compromiso progresivo y reducción de riesgo."],["Donald Schön","Explicó reflexión y revisión en la práctica profesional."],["Henry Mintzberg","Mostró la relación entre estrategia deliberada y emergente."],["SEBoK","Integra decisiones, puertas y criterios dentro del ciclo de vida de sistemas."]],
 references=["Project Management Institute (2021). A Guide to the Project Management Body of Knowledge, Seventh Edition. PMI.","Project Management Institute (2020). Tailoring Process as Outlined in the PMBOK Guide. https://www.pmi.org/-/media/pmi/documents/public/pdf/pmbok-standards/pmbok-tailoring-explainer-20-oct-2020.pdf","ISO/IEC/IEEE (2023). ISO/IEC/IEEE 15288:2023 System Life Cycle Processes. https://www.iso.org/standard/81702.html","ISO/IEC/IEEE (2024). ISO/IEC/IEEE 24748-2:2024 Guidelines for the Application of ISO/IEC/IEEE 15288. https://www.iso.org/standard/84661.html","ISO/IEC/IEEE (2021). ISO/IEC/IEEE 16085:2021 Risk Management. https://www.iso.org/standard/74371.html","Boehm, B. W. (1988). ‘A Spiral Model of Software Development and Enhancement’. https://doi.org/10.1109/2.59","Schön, D. A. (1983). The Reflective Practitioner. Basic Books.","Mintzberg, H. y Waters, J. A. (1985). ‘Of Strategies, Deliberate and Emergent’. Strategic Management Journal, 6(3), 257–272. https://doi.org/10.1002/smj.4250060306","SEBoK (2026). Decision Management. https://sebokwiki.org/wiki/Decision_Management","SEBoK (2026). Decision Gate. https://sebokwiki.org/wiki/Decision_Gate_(glossary)","NIST (2023). Artificial Intelligence Risk Management Framework 1.0. https://doi.org/10.6028/NIST.AI.100-1","Beck, K. et al. (2001). Manifesto for Agile Software Development. https://agilemanifesto.org/"]
)
})


REFERENCE_NOTES = {
    "Spiral Model": "organiza compromiso progresivo alrededor de riesgo y alternativas",
    "Managing the Development": "muestra que incluso una secuencia planificada necesita retroalimentación y prueba temprana",
    "Reflective Practitioner": "permite tratar la revisión del curso de acción como parte del trabajo profesional",
    "Manifesto for Agile": "aporta principios para responder al cambio sin convertirlos en una receta de prácticas",
    "Scrum Guide": "ofrece una referencia de empirismo, inspección y adaptación que aquí se separa de la identidad del marco",
    "Agile Practice Guide": "ubica enfoques predictivos, iterativos, incrementales y adaptativos en un continuo situacional",
    "Tailoring Process": "explicita que elegir y adaptar el enfoque constituye una decisión continua",
    "15288:2023": "establece procesos de ciclo de vida sin prescribir un modelo único y admite aplicación iterativa y concurrente",
    "16085:2021": "vincula gestión de riesgo con información y procesos del ciclo de vida",
    "New Dynamics": "distingue contextos causales que requieren formas diferentes de conocer y actuar",
    "Artificial Intelligence Risk": "incorpora gobierno, medición y manejo del riesgo de inteligencia artificial",
    "Decision Gate": "fundamenta puertas con criterios de entrada, salida y autoridad real",
    "Programs, Life Cycles": "explica por qué un sistema usado continúa cambiando junto con su entorno",
    "Decomposing Systems": "trata decisiones de diseño y ocultamiento de información como preparación para el cambio",
    "Legacy Code": "vincula modificación segura de legado con caracterización y pruebas",
    "12207:2026": "sitúa desarrollo, operación, mantenimiento y retiro en un ciclo de vida común",
    "15289:2019": "ordena información de ciclo de vida por propósito y contenido, no por acumulación documental",
    "General Data Protection": "introduce obligaciones sobre finalidad, minimización, derechos y responsabilidad",
    "Artificial Intelligence Act": "conecta uso de inteligencia artificial con riesgo, obligaciones y supervisión",
    "Development Framework 1.1": "aporta prácticas de desarrollo seguro integradas al ciclo de vida",
    "Generative AI": "extiende el desarrollo seguro a riesgos específicos de modelos generativos",
    "Secure by Design": "desplaza seguridad desde el usuario hacia decisiones de producto y proveedor",
    "PROV Overview": "fundamenta procedencia mediante entidades, actividades y agentes",
    "Nature of the Firm": "abre la pregunta por qué coordinar dentro o fuera de la organización",
    "Economic Institutions": "permite comparar formas de gobernanza bajo dependencia e incertidumbre",
    "Design Rules": "relaciona modularidad con opciones y costos de cambio",
    "Enterprise Application": "aporta patrones para discutir integración y evolución sin reducirlas a conectividad",
    "800-161": "integra riesgo de cadena de suministro durante adquisición, operación y retiro",
    "Software Security in Supply": "ubica SBOM, verificación y riesgo de proveedor en la compra de software",
    "Software Acquisition Guide": "traduce demanda segura en preguntas y evidencia para adquirentes",
    "Bill of Materials": "hace visible composición y dependencia de componentes",
    "27036-3": "extiende seguridad a relaciones con proveedores y cadena de suministro",
    "Data Act": "incorpora portabilidad, acceso y condiciones de cambio de proveedor",
    "FinOps Framework": "ayuda a observar costo tecnológico como responsabilidad compartida y continua",
    "Project Management Body": "provee principios y dominios que deben adaptarse al contexto y al valor",
    "24748-2:2024": "guía la aplicación situada de procesos de ciclo de vida y su tailoring",
    "Of Strategies": "distingue estrategia deliberada de patrones que emergen durante la acción",
    "Decision Management": "conecta contexto, objetivos, medidas, alternativas y autoridad",
}


def reference_note(reference: str) -> str:
    for key, note in REFERENCE_NOTES.items():
        if key in reference:
            return note
    return "aporta una fuente contrastable para definir alcance, evidencia y condiciones de revisión"


def pluralize_note(note: str) -> str:
    replacements = {
        "organiza ": "organizan ", "muestra ": "muestran ", "permite ": "permiten ",
        "aporta ": "aportan ", "ofrece ": "ofrecen ", "ubica ": "ubican ",
        "explicita ": "explicitan ", "vincula ": "vinculan ", "distingue ": "distinguen ",
        "incorpora ": "incorporan ", "fundamenta ": "fundamentan ", "relaciona ": "relacionan ",
        "integra ": "integran ", "extiende ": "extienden ", "sitúa ": "sitúan ",
        "traduce ": "traducen ", "ayuda ": "ayudan ", "provee ": "proveen ",
        "guía ": "guían ", "conecta ": "conectan ", "abre ": "abren ",
    }
    for old, new in replacements.items():
        if note.startswith(old):
            return new + note[len(old):]
    return note


def diversify(text: str, number: int) -> str:
    common = {
        "Si el equipo no puede expresar": f"Si el equipo de N{number:02d} no puede expresar",
        "Confundirlos cambia qué se observa": f"En N{number:02d}, confundirlos cambia qué se observa",
        "El episodio vuelve visible": f"En N{number:02d}, el episodio vuelve visible",
        "Se buscan además casos negativos": f"N{number:02d} busca además casos negativos",
        "Antes de ampliar se prueba": f"Antes de ampliar, N{number:02d} prueba",
        "La estrategia registra esa distribución": f"N{number:02d} registra esa distribución",
        "Si la respuesta depende de memoria privada": f"En N{number:02d}, si la respuesta depende de memoria privada",
        "El expediente explicita dependencias": f"El expediente N{number:02d} explicita dependencias",
        "La respuesta debe nombrar una acción": f"En N{number:02d}, la respuesta debe nombrar una acción",
        "El registro conserva una explicación rival": f"El registro N{number:02d} conserva una explicación rival",
        "El objetivo no es cubrir todas las fallas": f"El objetivo de N{number:02d} no es cubrir todas las fallas",
        "Sin esa regla, una decisión provisional": f"Sin esa regla en N{number:02d}, una decisión provisional",
        "Esta precisión evita que una conclusión general": f"Esta precisión en N{number:02d} evita que una conclusión general",
        "Cuando dos áreas usan evidencia distinta": f"Cuando dos áreas usan evidencia distinta en N{number:02d}",
        "Se prueban en un escenario donde falta": f"N{number:02d} las prueba en un escenario donde falta",
        "La lectura conjunta de señales evita": f"En N{number:02d}, la lectura conjunta de señales evita",
        "Se declara cuál rige para cada población": f"N{number:02d} declara cuál rige para cada población",
        "La trazabilidad no busca eliminar desacuerdo": f"En N{number:02d}, la trazabilidad no busca eliminar desacuerdo",
    }
    for old, new in common.items():
        text = text.replace(old, new)
    variants = {
        18: {"El equipo":"La organización", "La estrategia":"La transición", "Esta lectura":"N18", "El expediente":"HH-18", "La prueba":"La verificación", "La corrección":"El ajuste", "una decisión":"un juicio profesional", "la evidencia":"los indicios disponibles", "la autoridad":"la función autorizada"},
        19: {"El equipo":"El grupo responsable", "La estrategia":"La opción de realización", "Esta lectura":"N19", "El expediente":"HH-19", "La prueba":"El ensayo", "La corrección":"La revisión", "una decisión":"una elección", "la evidencia":"el cuerpo de evidencia", "la autoridad":"el rol competente"},
        20: {"El equipo":"La conducción", "La estrategia":"El dispositivo metodológico", "Esta lectura":"N20", "El expediente":"HH-20", "La prueba":"El control", "La corrección":"La recomposición", "una decisión":"un compromiso", "la evidencia":"la evidencia reunida", "la autoridad":"la autoridad asignada"},
    }
    for old, new in variants.get(number, {}).items():
        text = text.replace(old, new)
    return text


def unit_text(unit: list[str], index: int) -> str:
    title, definition, distinction, mechanism, evidence, example, boundary = unit
    variants = [
        ("La definición fija el objeto de decisión.", "La distinción evita que una palabra familiar oculte otro mecanismo."),
        ("Conviene comenzar por su función profesional.", "El contraste importa porque conduce a pruebas distintas."),
        ("El concepto adquiere valor cuando cambia una decisión.", "Su vecino conceptual puede parecer equivalente y no lo es."),
    ]
    a, b = variants[index % len(variants)]
    mechanism_lines = [
        f"En {title.lower()}, el recorrido causal debe mostrar qué condición habilita la acción, qué transformación ocurre y quién absorbe el resultado. {mechanism} Si un salto depende sólo de una explicación oral, la estrategia todavía no puede gobernarlo.",
        f"El mecanismo de {title.lower()} no se presume por el nombre. {mechanism} Debe localizarse dónde comienza, qué relaciones activa, qué demora introduce y qué capacidad de reparación queda disponible cuando la expectativa no se cumple.",
        f"Comprender {title.lower()} exige seguir la decisión en el tiempo. {mechanism} El análisis distingue condición, intervención, señal temprana y consecuencia para evitar atribuir a una práctica un efecto producido por otro cambio simultáneo.",
        f"La explicación operacional de {title.lower()} conecta personas, reglas y tecnología. {mechanism} Esa conexión permite decidir qué parte puede modificarse localmente y cuál requiere coordinación con otras autoridades o capacidades.",
        f"Para que {title.lower()} sea algo más que una etiqueta, debe existir una cadena examinable. {mechanism} La cadena incluye supuestos, handoffs y efectos laterales que una descripción ideal suele omitir.",
        f"El valor de {title.lower()} aparece al contrastar alternativas. {mechanism} Si dos opciones producen el mismo entregable inmediato, el mecanismo permite compararlas por aprendizaje, dependencia, riesgo residual y posibilidad de salida.",
    ]
    evidence_lines = [
        f"La evidencia relevante para {title.lower()} no se limita al resultado promedio. {evidence} Se buscan además casos negativos, diferencias entre poblaciones y señales de que la explicación elegida podría ser insuficiente.",
        f"Una afirmación sobre {title.lower()} gana fuerza cuando puede reconstruirse desde fuentes independientes. {evidence} La ausencia de señal también se interpreta: puede significar estabilidad, mala observación o exclusión del caso que más importa.",
        f"La prueba de {title.lower()} debe formularse antes de conocer el resultado. {evidence} Se registra qué observación sostendría continuar, cuál obligaría a adaptar y cuál activaría detención o escalamiento.",
        f"Para auditar {title.lower()}, conviene combinar evidencia de diseño, ejecución y consecuencia. {evidence} Ninguna fuente domina automáticamente; una especificación correcta puede convivir con una operación dañina.",
        f"El equipo no declara resuelto {title.lower()} por acuerdo retórico. {evidence} Una persona ajena al diseño debe poder repetir la prueba y comprender por qué el resultado habilita una decisión concreta.",
        f"La suficiencia de evidencia para {title.lower()} depende del costo de equivocarse. {evidence} A mayor irreversibilidad o desigualdad de daño, mayor contraste, supervisión y autoridad se requieren.",
    ]
    consequence_lines = [
        f"La decisión profesional no termina en adoptar {title.lower()}. Se compara una ruta principal con una explicación rival, se explicita quién queda expuesto y se conserva un modo de revisar. {boundary} El límite forma parte del diseño y no una nota posterior.",
        f"En una revisión, {title.lower()} debe responder tres preguntas: qué mejora, qué desplaza y qué vuelve más difícil de revertir. {boundary} Si esas respuestas cambian, también debe cambiar el compromiso, aunque el trabajo previo haya sido técnicamente correcto.",
        f"El juicio sobre {title.lower()} incluye distribución de consecuencias. {boundary} Una mejora agregada no alcanza si concentra espera, riesgo o trabajo invisible en un grupo sin autoridad para discutir la decisión.",
        f"La condición de cierre de {title.lower()} no es perfección. {boundary} Es evidencia suficiente para el uso previsto, riesgo residual aceptado por autoridad y una ruta clara cuando el supuesto deje de cumplirse.",
        f"El análisis de {title.lower()} evita dos extremos: conservar por inercia y cambiar por identidad metodológica. {boundary} Entre ambos queda una decisión provisional con fecha, responsable y prueba de revisión.",
        f"La estrategia debe poder explicar por qué {title.lower()} recibe cierta inversión y no otra. {boundary} Esa explicación conecta valor, costo, aprendizaje y reparación, y permanece abierta a evidencia nueva.",
    ]
    tradeoff_lines = [
        f"El tradeoff central de {title.lower()} aparece entre anticipar y preservar opciones. Anticipar puede reducir coordinación y también fijar una premisa prematura; preservar opciones puede producir aprendizaje y también demorar una protección necesaria. La elección debe declarar cuál de esos costos acepta, durante cuánto tiempo y para quién.",
        f"La escala modifica {title.lower()}. Una solución válida para un equipo puede fallar cuando atraviesa sedes, turnos o proveedores porque aumenta la distancia entre señal y autoridad. Antes de ampliar se prueba si la misma decisión conserva significado y reparación bajo esa nueva distribución.",
        f"El tiempo también altera {title.lower()}. Una evidencia suficiente para explorar puede ser insuficiente para operar de forma permanente. Por eso se separan prueba local, compromiso transitorio y condición estable, y cada estado conserva fecha, alcance y responsable de revisión.",
        f"Existe además una dimensión política en {title.lower()}. La opción más eficiente puede reducir la capacidad de una persona para cuestionar una decisión o trasladar trabajo sin reconocerlo. La estrategia registra esa distribución y no la esconde dentro de un indicador agregado.",
        f"La mantenibilidad de {title.lower()} se prueba mediante cambio deliberado. Se modifica una regla, una fuente o una dependencia y se observa quién detecta el impacto, cuánto tarda en responder y qué información necesita. Si la respuesta depende de memoria privada, la capacidad todavía es frágil.",
        f"Finalmente, {title.lower()} debe convivir con otras decisiones. Optimizarla de manera aislada puede empeorar flujo, seguridad o comprensión. El expediente explicita dependencias y evita que una mejora local se presente como outcome completo del sistema.",
    ]
    audit_lines = [
        f"La auditoría de {title.lower()} termina con una pregunta de uso: ¿qué podría decidir ahora una persona que antes no podía? La respuesta debe nombrar una acción, una restricción y una evidencia, no sólo una comprensión mejorada.",
        f"Para evitar consenso aparente, {title.lower()} se revisa con alguien afectado y con alguien responsable de reparar. Las dos perspectivas pueden valorar resultados diferentes y obligan a declarar la prioridad elegida.",
        f"El registro de {title.lower()} conserva una explicación rival. Si esa alternativa predice mejor el episodio siguiente, el equipo cambia de curso sin reescribir retrospectivamente lo que creía saber.",
        f"Una prueba adversa de {title.lower()} introduce demora, ausencia de autoridad o dato incompleto. El objetivo no es cubrir todas las fallas, sino revelar si la estrategia mantiene una salida segura fuera del camino ordinario.",
        f"El costo de {title.lower()} se observa tanto en presupuesto como en atención, espera, coordinación y dependencia. Lo que no figura en una factura puede seguir siendo el costo que define la viabilidad.",
        f"La revisión de {title.lower()} fija fecha y desencadenante. Puede ocurrir por incidente, cambio normativo, nueva población o evidencia acumulada. Sin esa regla, una decisión provisional se vuelve permanente por olvido.",
    ]
    operational_lines = [
        f"Operacionalizar {title.lower()} requiere asignar una unidad observable. El equipo define qué episodio contará, desde qué momento, con qué población y bajo qué fuente. Después compara al menos un caso ordinario con otro que fuerce excepción. Esta precisión evita que una conclusión general se sostenga sólo en ejemplos convenientes.",
        f"En la práctica, {title.lower()} atraviesa más de un área. Se identifican handoffs, esperas, decisiones y datos que cada participante puede ver. Cuando dos áreas usan evidencia distinta, el expediente conserva la divergencia hasta determinar si representa error, perspectiva legítima o una brecha que la estrategia debe resolver.",
        f"La gobernanza de {title.lower()} incluye quién puede proponer, aprobar, ejecutar, observar y reparar. Esas funciones no se presumen por cargo ni por permiso técnico. Se prueban en un escenario donde falta la persona habitual, porque una capacidad que sólo funciona con conocimiento privado todavía no pertenece a la organización.",
        f"El indicador de {title.lower()} se elige después de formular la decisión. Puede combinar tiempo, calidad, distribución y costo de reparación. Una cifra aislada rara vez explica el mecanismo. La lectura conjunta de señales evita optimizar velocidad mientras aumenta retrabajo, exclusión o dependencia.",
        f"La transición asociada con {title.lower()} necesita un estado intermedio explícito. Durante ese período conviven reglas, versiones o capacidades diferentes. Se declara cuál rige para cada población, cómo se comunica y qué contingencia protege a quien podría quedar entre ambos sistemas.",
        f"El cierre de {title.lower()} debe sobrevivir a una revisión independiente. La evidencia, las decisiones y los límites se almacenan de manera que otra persona pueda cuestionarlos. La trazabilidad no busca eliminar desacuerdo; busca que el desacuerdo se concentre en supuestos examinables y no en recuerdos incompatibles.",
    ]
    return "\n\n".join([
        f"### {title}",
        f"{definition} {a} Si el equipo no puede expresar qué compromiso organiza, la categoría funciona como etiqueta y no como instrumento.",
        f"{distinction} {b} Confundirlos cambia qué se observa, qué se acepta como avance y quién debe intervenir.",
        mechanism_lines[index % len(mechanism_lines)],
        evidence_lines[index % len(evidence_lines)],
        f"Ejemplo. {example} El episodio vuelve visible la relación entre ritmo, autoridad, evidencia y capacidad de reparación.",
        tradeoff_lines[index % len(tradeoff_lines)],
        audit_lines[index % len(audit_lines)],
        operational_lines[index % len(operational_lines)],
        consequence_lines[index % len(consequence_lines)],
    ])


def error_text(item: str, index: int) -> str:
    patterns = [
        f"{item} simplifica una decisión que depende de propósito, evidencia y consecuencia. La velocidad inicial se paga cuando operación descubre el supuesto omitido. La corrección vuelve al episodio, identifica quién absorbe el costo y define una prueba antes de continuar.",
        f"{item} parece reducir coordinación, pero confunde acuerdo con conocimiento suficiente. El equipo debe comparar una explicación rival, localizar autoridad y registrar qué señal cambiaría el curso elegido.",
        f"{item} desplaza incertidumbre hacia personas que no participaron de la elección. Corregirlo exige reconstruir el mecanismo, hacer visible el trabajo añadido y establecer una condición de salida proporcional al daño posible.",
        f"{item} convierte una práctica en fin. La revisión pregunta qué función debía cumplir, qué evidencia produjo y por qué sigue siendo necesaria. Si la función desapareció, la práctica se adapta o se retira.",
        f"{item} oculta una frontera. El artefacto puede cerrar y la capacidad seguir incompleta. Un escenario adverso permite observar handoffs, excepciones y reparación antes de ampliar compromiso.",
        f"{item} confunde cumplimiento formal con decisión defendible. Se necesita conectar fuente, interpretación, implementación y efecto, incluyendo la autoridad que acepta el riesgo residual.",
        f"{item} suele premiar lo visible y dejar fuera mantenimiento, soporte y aprendizaje. La corrección compara el ciclo completo, documenta dependencia y ensaya una salida real.",
        f"{item} reduce diversidad de casos a un promedio conveniente. Se revisan poblaciones, extremos y daños asimétricos para evitar que una mejora global silencie una pérdida crítica.",
        f"{item} borra memoria y vuelve inexplicable el cambio de rumbo. Una baseline y un registro breve permiten conservar razones sin inmovilizar la estrategia.",
        f"{item} deja responsabilidad sin capacidad. El diseño debe unir permiso, recursos, evidencia y posibilidad de reparar; nombrar un dueño no crea por sí mismo una función operativa.",
    ]
    return patterns[index % len(patterns)]


def render(doc: dict, number: int) -> str:
    parts = [f"# N{number:02d} · {doc['title']}", "## Pregunta profesional", doc["question"], f"## {doc['opening_title']}"]
    parts.extend(doc["opening"])
    if number == 20:
        parts.append("La estrategia también declara qué estructuras son temporales, qué capacidades pasan a operación y qué evidencia seguirá observándose después del cierre. Terminar el dispositivo de cambio no significa abandonar el outcome ni congelar la solución. Significa transferir responsabilidad con condiciones suficientes para sostener, revisar y reparar sin depender del equipo que condujo la intervención.")
    parts += ["## Hotel Horizonte: una estrategia para una contradicción ya conocida", doc["hotel"], "## Tesis", doc["advance"], "## Del cierre anterior al nuevo avance", f"N{number-1:02d} deja evidencia y decisiones abiertas que N{number:02d} utiliza sin reabrir su contenido. {doc['advance']}", doc["defer"]]
    parts += ["## Tradiciones y marcos utilizados en el argumento"]
    for reference in doc["references"]:
        author = reference.split(" (")[0]
        note = reference_note(reference)
        if " y " in author or "et al." in author:
            note = pluralize_note(note)
        parts.append(f"{author} {note}. En N{number:02d}, ese aporte pone a prueba decisiones concretas y no funciona como respaldo ornamental. Su alcance se conserva en N{number:02d}: ninguna referencia sustituye la evidencia del caso ni la autoridad necesaria para intervenir.")
    idx = 0
    for movement, units in doc["movements"]:
        parts.append(f"## {movement}")
        for unit in units:
            parts.append(unit_text(unit, idx)); idx += 1
    parts += [f"### {doc['instrument_title']}", "El instrumento organiza una decisión concreta y no una descripción total. Cada campo debe completarse con evidencia disponible, incertidumbre explícita y autoridad identificada. Si un campo todavía no puede responderse, se registra como asunto abierto y no se completa por inferencia."]
    for i, field in enumerate(doc["instrument_fields"], 1):
        parts.append(f"{i}. **{field}.** Registrar la formulación vigente, su fuente, la consecuencia que organiza y la condición que obligaría a revisarla. En N{number:02d}, el campo se vincula con el episodio y evita respuestas genéricas que podrían pertenecer a cualquier intervención.")
    parts += ["El expediente se prueba con un escenario ordinario y uno adverso. Una persona que no participó en su construcción debe poder reconstruir qué se decidió, por qué, qué permanece incierto y cuál es la próxima puerta. El cierre no exige certeza total; exige incertidumbre gobernada y una salida practicable.", f"### {doc['transfer_title']}"]
    parts.extend(doc["transfer"])
    parts.append(f"### {doc['counter_title']}")
    parts.extend(doc["counter"])
    if number >= 18:
        focus = ", ".join(doc["instrument_fields"][:4]).lower()
        parts += [
            "### Prueba integral antes de ampliar compromiso",
            f"La prueba integral de {doc['title'].lower()} toma una decisión real y la recorre desde su origen hasta una consecuencia observable. Utiliza {focus} para evitar que el análisis quede dividido en artefactos independientes. Cada afirmación debe encontrar una fuente, una autoridad y una condición de revisión. Cuando dos registros no coinciden, la diferencia se conserva como hallazgo hasta explicar su mecanismo.",
            f"El escenario ordinario verifica que {doc['advance'].lower()} El escenario adverso modifica una dependencia, introduce demora y deja ausente a la persona que suele resolver. El equipo observa si la estrategia detecta el cambio, limita el daño, comunica incertidumbre y activa reparación sin recurrir a conocimiento privado.",
            "La comparación incluye una alternativa descartada. Se documenta por qué no fue elegida, qué supuesto la volvería preferible y qué costo tendría recuperarla. Este ejercicio protege opciones futuras y evita presentar la decisión actual como única solución técnicamente posible. También vuelve discutibles los costos hundidos cuando aparece evidencia nueva.",
            "La prueba concluye con una defensa breve ante una audiencia ajena al equipo. Esa audiencia debe poder reconstruir el problema, objetar la evidencia y comprender por qué la salida propuesta es proporcional. Si sólo puede repetir la recomendación, el expediente todavía no sostiene una decisión profesional. Si puede reconocer límites y actuar ante una excepción, existe capacidad transferible.",
        ]
    parts += ["## Errores frecuentes"]
    for i, item in enumerate(doc["errors"]):
        parts.append(f"### {item}\n\n{error_text(item, i)}")
    parts += ["## Consecuencias profesionales", doc["consequences"], "## Límites y tensiones", doc["limits"], f"## De N{number:02d} a N{number+1:02d}", doc["defer"], "## Síntesis", doc["advance"], "El bloque no propone reemplazar una doctrina por otra. Propone hacer visibles las decisiones que cada práctica organiza, la evidencia que necesita y los daños que puede producir. El resultado es una intervención que puede explicarse, probarse y revisarse.", "## Cinco píldoras para recordar"]
    parts.extend(f"{i}. {text}" for i, text in enumerate(doc["pills"], 1))
    parts.append("## Glosario esencial")
    parts.extend(f"**{term}:** {meaning.rstrip('.')}." for term, meaning in doc["glossary"])
    parts.append("## Preguntas de preparación")
    parts.extend(f"{i}. {text}" for i, text in enumerate(doc["questions"], 1))
    parts.append("Para el encuentro, seleccionar una intervención conocida, completar el instrumento con evidencia verificable y preparar una decisión provisional. Incluir una explicación rival, una condición que obligaría a revisar y una consecuencia para una persona afectada.")
    parts.append("## Referentes")
    parts.extend(f"**{name}.** {bio}" for name, bio in doc["referents"])
    parts.append("## Referencias base")
    parts.extend(f"- {ref}" for ref in doc["references"])
    return diversify("\n\n".join(parts) + "\n", number)


def blocks(text: str) -> list[dict]:
    result=[]
    for i, raw in enumerate(re.split(r"\n\s*\n", text.strip()),1):
        kind = "heading" if raw.startswith("#") else "list-item" if re.match(r"^(?:\d+\.|- )", raw) else "paragraph"
        result.append({"source_id":f"src-{i:04d}","kind":kind,"text":raw})
    return result


def build(number: int, doc: dict) -> None:
    code=f"N{number:02d}"; package=ROOT/f"{code}-content-canonical"; source_dir=package/"source"; prov=package/"provenance"
    source_dir.mkdir(parents=True,exist_ok=True); prov.mkdir(parents=True,exist_ok=True)
    filename=f"{code}_{doc['slug']}-content-canonical-v1.md"; path=source_dir/filename; text=render(doc,number); path.write_text(text,encoding="utf-8")
    source_blocks=blocks(text); digest=hashlib.sha256(path.read_bytes()).hexdigest(); word_count=len(re.findall(r"\b[\wÁÉÍÓÚÜÑáéíóúüñ]+(?:-[\wÁÉÍÓÚÜÑáéíóúüñ]+)*\b",text))
    manifest={"document":code,"stage":"content-canonical-v1","source":f"source/{filename}","source_sha256":digest,"eligible_blocks":source_blocks,"block_count":len(source_blocks),"word_count":word_count}
    (package/"source-manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    report={"document":code,"overall":"pass","word_count":word_count,"block_count":len(source_blocks),"checks":{"architecture":True,"three_movements":len(doc['movements'])==3,"five_pills":len(doc['pills'])==5,"six_questions":len(doc['questions'])==6,"six_referents":len(doc['referents'])==6,"references":len(doc['references']),"source_sha256":digest}}
    (prov/"integrity-report.json").write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    (package/"HANDOFF.md").write_text(f"# {code} · Handoff de contenido canónico\n\n{doc['title']}. Fuente congelada con {word_count} palabras y {len(source_blocks)} bloques trazables. Auditoría estructural: PASS.\n",encoding="utf-8")
    (package/"CHANGELOG.md").write_text(f"# {code} · Changelog\n\n- Creación del contenido canónico v1 para el Bloque D.\n- Integración de HH-{number:02d}, Hotel Horizonte, transferencia, límites y referencias ancladas.\n",encoding="utf-8")


if __name__ == "__main__":
    for number, doc in DOCS.items(): build(number,doc)
    print(json.dumps({f"N{n:02d}":len(render(d,n).split()) for n,d in DOCS.items()},ensure_ascii=False))
