#!/usr/bin/env python3
"""Remove production metadata from the public METSI release without changing content."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path
from typing import Any

from PIL import Image
from pypdf import PdfReader, PdfWriter


ROOT = Path(__file__).resolve().parent
SITE = ROOT / "site"
AUDIT_DIR = ROOT / "qa-reports" / "public-release-sanitization"
AUDIT_PATH = AUDIT_DIR / "public-release-sanitization.json"
FORBIDDEN_PUBLIC_TEXT = re.compile(
    r"(?i)(?:openai|chatgpt|codex|claude|gemini|gamma|midjourney|dall.?e|"
    r"stable diffusion|ai[- ]generated|generated by|markdown|\.md\b|"
    r"canonical[_ -]?source|package[_ -]?source|qa[_ -]?(?:report|validator))"
)


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def pdf_paths() -> list[Path]:
    readings = sorted((SITE / "pdf").rglob("*.pdf"), key=lambda path: path.name)
    program = SITE / "covers" / "programa" / "programa-metsi-2026.pdf"
    paths = readings + [program]
    if len(paths) != 38:
        raise RuntimeError(f"Expected 38 public PDFs, found {len(paths)}")
    return paths


def annotation_values(reader: PdfReader) -> list[str]:
    values: list[str] = []
    for page in reader.pages:
        for reference in page.get("/Annots", []):
            annotation = reference.get_object()
            for key in ("/Subtype", "/Contents", "/T", "/Subj", "/A", "/AA"):
                if key in annotation:
                    values.append(f"{key}={annotation[key]}")
    return values


def page_boxes(reader: PdfReader) -> list[dict[str, list[float]]]:
    rows: list[dict[str, list[float]]] = []
    for page in reader.pages:
        row: dict[str, list[float]] = {}
        for name in ("mediabox", "cropbox", "trimbox", "bleedbox", "artbox"):
            box = getattr(page, name)
            row[name] = [float(value) for value in box]
        rows.append(row)
    return rows


def text_digest(reader: PdfReader) -> tuple[str, list[dict[str, Any]]]:
    digest = hashlib.sha256()
    hits: list[dict[str, Any]] = []
    for number, page in enumerate(reader.pages, 1):
        text = page.extract_text() or ""
        digest.update(text.encode("utf-8"))
        digest.update(b"\x00PAGE\x00")
        for match in FORBIDDEN_PUBLIC_TEXT.finditer(text):
            hits.append({"page": number, "value": match.group(0)})
    return digest.hexdigest(), hits


def inspect_pdf(path: Path) -> dict[str, Any]:
    reader = PdfReader(str(path), strict=False)
    root = reader.trailer["/Root"]
    annotations = annotation_values(reader)
    annotation_hits = [value for value in annotations if FORBIDDEN_PUBLIC_TEXT.search(value)]
    text_sha256, text_hits = text_digest(reader)
    metadata = {str(key): str(value) for key, value in (reader.metadata or {}).items()}
    return {
        "pages": len(reader.pages),
        "bytes": path.stat().st_size,
        "sha256": file_sha256(path),
        "text_sha256": text_sha256,
        "page_boxes": page_boxes(reader),
        "annotation_count": len(annotations),
        "annotation_sha256": hashlib.sha256("\n".join(annotations).encode("utf-8")).hexdigest(),
        "visible_forbidden_hits": text_hits,
        "annotation_forbidden_hits": annotation_hits,
        "metadata": metadata,
        "metadata_stream": "/Metadata" in root,
        "trailer_id": "/ID" in reader.trailer,
        "root_active_content": [key for key in ("/OpenAction", "/AA", "/Collection") if key in root],
        "embedded_files": "/Names" in root and "/EmbeddedFiles" in root["/Names"].get_object(),
    }


def sanitize_pdf(path: Path) -> dict[str, Any]:
    before = inspect_pdf(path)
    already_clean = (
        not before["metadata"]
        and not before["metadata_stream"]
        and not before["trailer_id"]
        and not before["root_active_content"]
        and not before["embedded_files"]
        and not before["visible_forbidden_hits"]
        and not before["annotation_forbidden_hits"]
    )
    if already_clean:
        return {
            "file": path.relative_to(ROOT).as_posix(),
            "before": {key: before[key] for key in ("bytes", "sha256", "metadata", "metadata_stream", "trailer_id")},
            "after": {key: before[key] for key in ("bytes", "sha256", "metadata", "metadata_stream", "trailer_id")},
            "preserved": {field: True for field in ("pages", "text_sha256", "page_boxes", "annotation_count", "annotation_sha256")},
            "visible_text_clear": True,
            "annotations_clear": True,
        }
    source = PdfReader(str(path), strict=False)
    writer = PdfWriter(clone_from=source)
    writer._info = None
    writer._ID = None
    for key in ("/Metadata", "/PieceInfo", "/OpenAction", "/AA", "/Collection"):
        writer.root_object.pop(key, None)
    names = writer.root_object.get("/Names")
    if names is not None:
        names_object = names.get_object()
        names_object.pop("/EmbeddedFiles", None)
        names_object.pop("/JavaScript", None)
        if not names_object:
            writer.root_object.pop("/Names", None)
    temporary = path.with_suffix(path.suffix + ".sanitizing")
    with temporary.open("wb") as stream:
        writer.write(stream)
    temporary.replace(path)
    after = inspect_pdf(path)
    invariant_fields = ("pages", "text_sha256", "page_boxes", "annotation_count", "annotation_sha256")
    changed = [field for field in invariant_fields if before[field] != after[field]]
    clean = (
        not after["metadata"]
        and not after["metadata_stream"]
        and not after["trailer_id"]
        and not after["root_active_content"]
        and not after["embedded_files"]
        and not after["visible_forbidden_hits"]
        and not after["annotation_forbidden_hits"]
    )
    if changed or not clean:
        raise RuntimeError(f"Sanitization failed for {path}: changed={changed}, clean={clean}")
    return {
        "file": path.relative_to(ROOT).as_posix(),
        "before": {key: before[key] for key in ("bytes", "sha256", "metadata", "metadata_stream", "trailer_id")},
        "after": {key: after[key] for key in ("bytes", "sha256", "metadata", "metadata_stream", "trailer_id")},
        "preserved": {field: True for field in invariant_fields},
        "visible_text_clear": True,
        "annotations_clear": True,
    }


def sanitize_og_image() -> dict[str, Any]:
    path = SITE / "og.png"
    before_hash = file_sha256(path)
    with Image.open(path) as image:
        pixels = hashlib.sha256(image.convert("RGBA").tobytes()).hexdigest()
        size = image.size
        temporary = path.with_suffix(".sanitizing.png")
        image.save(temporary, format="PNG", optimize=True)
    temporary.replace(path)
    with Image.open(path) as image:
        after_pixels = hashlib.sha256(image.convert("RGBA").tobytes()).hexdigest()
        metadata_keys = sorted(image.info)
    if pixels != after_pixels or size != image.size or "exif" in metadata_keys:
        raise RuntimeError("Open Graph image sanitization changed pixels or retained EXIF")
    return {
        "file": path.relative_to(ROOT).as_posix(),
        "before_sha256": before_hash,
        "after_sha256": file_sha256(path),
        "pixels_preserved": True,
        "metadata_keys": metadata_keys,
    }


def main() -> int:
    AUDIT_DIR.mkdir(parents=True, exist_ok=True)
    pdf_results = [sanitize_pdf(path) for path in pdf_paths()]
    deployed_program = SITE / "covers" / "programa" / "programa-metsi-2026.pdf"
    source_program = SITE / "programa" / "programa-metsi-2026.pdf"
    shutil.copyfile(deployed_program, source_program)
    if file_sha256(deployed_program) != file_sha256(source_program):
        raise RuntimeError("Program PDF copies differ after sanitization")
    report = {
        "scope": "Public METSI release, N00 to N36 and academic program",
        "status": "PASS",
        "policy": {
            "academic_discussion_of_ai_preserved": True,
            "production_metadata_removed": True,
            "markdown_or_internal_source_references_forbidden_in_public_documents": True,
        },
        "pdfs": pdf_results,
        "program_source_copy": source_program.relative_to(ROOT).as_posix(),
        "open_graph_image": sanitize_og_image(),
    }
    AUDIT_PATH.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": "PASS", "pdfs": len(pdf_results), "audit": str(AUDIT_PATH)}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
