#!/usr/bin/env python3
"""Audita que los PDF finales no expongan metadatos ni marcas de producción."""

from __future__ import annotations

import json
import re
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
FORBIDDEN = re.compile(
    r"(?i)(openai|chatgpt|codex|claude|gemini|gamma|midjourney|dall.?e|"
    r"generated by|ai[- ]generated|markdown|\.md\b|canonical[_ -]?source|"
    r"qa[_ -]?(report|validator)|localhost|file://)"
)
PACKAGES = {
    0: ("N00-v3-final", "v3"), 1: ("N01-v18-final", "v18"),
    2: ("N02-v15-final", "v15"), 3: ("N03-v10-final", "v10"),
    4: ("N04-v9-final", "v9"), 5: ("N05-v10-final", "v10"),
    6: ("N06-v10-final", "v10"), 7: ("N07-v10-final", "v10"),
    8: ("N08-v10-final", "v10"), 9: ("N09-v10-final", "v10"),
    10: ("N10-v9-final", "v9"),
    **{number: (f"N{number:02d}-v9-editorial", "v9") for number in range(11, 37)},
}


def main() -> None:
    rows = []
    for number, (folder, version) in PACKAGES.items():
        code = f"N{number:02d}"
        path = ROOT / folder / "output" / f"{code}-METSI-lectura-previa-{version}-final.pdf"
        reader = PdfReader(str(path), strict=False)
        root = reader.trailer["/Root"]
        text_hits = []
        annotation_hits = []
        for page_number, page in enumerate(reader.pages, 1):
            text = page.extract_text() or ""
            text_hits.extend({"page": page_number, "value": match.group(0)} for match in FORBIDDEN.finditer(text))
            for reference in page.get("/Annots", []):
                annotation = str(reference.get_object())
                annotation_hits.extend({"page": page_number, "value": match.group(0)} for match in FORBIDDEN.finditer(annotation))
        checks = {
            "metadata_empty": not dict(reader.metadata or {}),
            "metadata_stream_absent": "/Metadata" not in root,
            "trailer_id_absent": "/ID" not in reader.trailer,
            "embedded_files_absent": not ("/Names" in root and "/EmbeddedFiles" in root["/Names"].get_object()),
            "active_content_absent": not any(key in root for key in ("/OpenAction", "/AA", "/Collection")),
            "production_marks_absent_from_text": not text_hits,
            "production_marks_absent_from_annotations": not annotation_hits,
        }
        rows.append({
            "document": code,
            "pdf": path.relative_to(ROOT).as_posix(),
            "pages": len(reader.pages),
            "status": "PASS" if all(checks.values()) else "FAIL",
            "checks": checks,
            "text_hits": text_hits,
            "annotation_hits": annotation_hits,
        })
    report = {
        "summary": {
            "documents": len(rows),
            "passed": sum(row["status"] == "PASS" for row in rows),
            "failed": sum(row["status"] == "FAIL" for row in rows),
        },
        "documents": rows,
    }
    out = ROOT / "editorial-standard" / "final-pdf-metadata-audit-n00-n36.json"
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(report["summary"], ensure_ascii=False))
    if report["summary"]["failed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
