#!/usr/bin/env python3
"""Finalize, sanitize and audit the regionalized N01-N36 PDFs."""

from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

import pdfplumber
from pypdf import PdfReader


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from sanitize_final_pdfs import sanitize  # noqa: E402
from audit_pdf_text_overlaps_n00_n36 import page_collisions  # noqa: E402


VERSIONS = {1: 19, 2: 16, 3: 11, 4: 10, 5: 11, 6: 11, 7: 11, 8: 11, 9: 11, 10: 10}
REGIONAL_NAMES = ("Mario Bunge", "Humberto Maturana", "Fernando Flores", "Paulo Freire")
FORBIDDEN = re.compile(
    r"(?i)(openai|chatgpt|codex|claude|gemini|gamma|midjourney|dall.?e|"
    r"generated by|ai[- ]generated|markdown|\.md\b|canonical[_ -]?source|"
    r"qa[_ -]?(report|validator)|localhost|file://)"
)


def package(number: int) -> tuple[Path, int]:
    if number <= 10:
        version = VERSIONS[number]
        return ROOT / f"N{number:02d}-v{version}-final", version
    return ROOT / f"N{number:02d}-v10-editorial", 10


def paths(number: int) -> tuple[Path, Path]:
    root, version = package(number)
    stem = f"N{number:02d}-METSI-lectura-previa-v{version}"
    return root / "output" / f"{stem}.pdf", root / "output" / f"{stem}-final.pdf"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    source_manifest = json.loads((ROOT / "academic-content-regionalization-manifest-n01-n36.json").read_text())
    source_rows = {item["code"]: item for item in source_manifest["documents"]}
    rows = []
    for number in range(1, 37):
        code = f"N{number:02d}"
        raw, final = paths(number)
        if not raw.is_file():
            raise FileNotFoundError(raw)
        shutil.copy2(raw, final)
        pages, size = sanitize(final)
        reader = PdfReader(final, strict=False)
        all_text = "\n".join(page.extract_text() or "" for page in reader.pages)
        all_text_folded = all_text.casefold()
        all_text_normalized = re.sub(r"\s+", " ", all_text_folded)
        referents_text = "\n".join((reader.pages[i].extract_text() or "") for i in range(min(4, len(reader.pages))))
        referents_text_folded = referents_text.casefold()
        expected = source_rows[code]["featured_regional_referents"]
        expected_visible = {name: name.casefold() in referents_text_folded for name in expected}
        metadata = dict(reader.metadata or {})
        root = reader.trailer["/Root"]
        text_hits = sorted(set(match.group(0) for match in FORBIDDEN.finditer(all_text)))
        problem_pages = []
        with pdfplumber.open(final) as pdf:
            for page_number, page in enumerate(pdf.pages, 1):
                words = page.extract_words(use_text_flow=False) or []
                clipped = [
                    word.get("text") for word in words
                    if float(word["x0"]) < -0.5 or float(word["x1"]) > float(page.width) + 0.5
                    or float(word["top"]) < -0.5 or float(word["bottom"]) > float(page.height) + 0.5
                ]
                collisions = page_collisions(words)
                if clipped or collisions:
                    problem_pages.append({"page": page_number, "clipped": clipped[:12], "collisions": collisions[:12]})
        source = source_rows[code]
        checks = {
            "regional_bibliography_between_30_and_50": 30 <= source["regional_percentage"] <= 50,
            "two_featured_regional_referents": len(expected) == 2 and all(expected_visible.values()),
            "situated_section_present": bool(re.search(
                r"una\s*lectura\s*situada\s*desde\s*américa\s*latina",
                all_text_folded,
            )),
            "a4": all(abs(float(page.mediabox.width) - 595.28) <= 1 and abs(float(page.mediabox.height) - 841.89) <= 1 for page in reader.pages),
            "metadata_empty": not metadata,
            "metadata_stream_absent": "/Metadata" not in root,
            "trailer_id_absent": "/ID" not in reader.trailer,
            "production_marks_absent": not text_hits,
            "no_text_collisions_or_clipping": not problem_pages,
        }
        rows.append({
            "document": code,
            "pdf": final.relative_to(ROOT).as_posix(),
            "sha256": sha(final),
            "pages": pages,
            "bytes": size,
            "regional_references": source["references_regional"],
            "total_references": source["references_total"],
            "regional_percentage": source["regional_percentage"],
            "featured_regional_referents": expected,
            "referents_visible": expected_visible,
            "checks": checks,
            "problem_pages": problem_pages,
            "production_hits": text_hits,
            "status": "PASS" if all(checks.values()) else "FAIL",
        })
        print(f"AUDITED {code} {rows[-1]['status']} {pages} pages {source['regional_percentage']}%")
    report = {
        "audit": "METSI N01-N36 regionalization and final PDF QA",
        "date": "2026-09-15",
        "summary": {
            "documents": len(rows),
            "passed": sum(row["status"] == "PASS" for row in rows),
            "failed": sum(row["status"] == "FAIL" for row in rows),
            "pages": sum(row["pages"] for row in rows),
            "min_regional_percentage": min(row["regional_percentage"] for row in rows),
            "max_regional_percentage": max(row["regional_percentage"] for row in rows),
        },
        "documents": rows,
    }
    target = ROOT / "audits" / "regionalization-final-pdf-audit-n01-n36-2026-09-15.json"
    target.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(json.dumps(report["summary"], ensure_ascii=False))
    if report["summary"]["failed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
