"""Editorial microcopy grounded in the existing decision maps, not new syllabus."""
# Rows express steps only for flow maps; other families compare or group conditions.
MAPS = {
1: ('No todo sirve para lo mismo', 'Una herramienta ayuda a ejecutar. No decide por nosotros qué conviene hacer.', 'taxonomy', [
('Marco', 'Ordena conceptos y roles.', 'Sirve para mirar una situación sin olvidar aspectos importantes.'),
('Metodología', 'Justifica cómo trabajar.', 'Explica por qué elegir y combinar ciertos métodos en este caso.'),
('Método', 'Organiza una manera de proceder.', 'Por ejemplo, reconstruir un incidente para buscar explicaciones.'),
('Práctica', 'Es una actividad que se sostiene.', 'Por ejemplo, revisar periódicamente lo que estamos aprendiendo.'),
('Técnica', 'Define un procedimiento preciso.', 'Ayuda a realizar una parte concreta de la investigación.'),
('Herramienta', 'Facilita la ejecución.', 'Puede registrar y calcular; no reemplaza el juicio profesional.')],
'Antes de elegir', '¿Qué necesitamos comprender o decidir? Recién después elegimos cómo hacerlo.'),
2: ('El sistema no termina en la pantalla', 'Son cinco objetos relacionados. Confundirlos cambia el problema que intentamos resolver.', 'nested', [
('Situación problemática', 'Incluye tensiones, perspectivas, restricciones e historia.', 'Es el contexto que vuelve necesario intervenir.'),
('Sistema de trabajo', 'Personas y actividades producen un servicio.', 'La tecnología participa, pero no trabaja sola.'),
('Sistema de información', 'Se produce, interpreta y usa información.', 'Importa quién la entiende, la corrige y decide con ella.'),
('Sistema técnico', 'Aplicaciones, integraciones, dispositivos y redes.', 'Es la infraestructura que permite parte del trabajo.'),
('Aplicación', 'Es una pieza del sistema técnico.', 'Que funcione no demuestra que el servicio cumpla su promesa.')],
'Elegir la frontera', 'Para probar una función miramos la aplicación. Para explicar una promesa incumplida, ampliamos la mirada.'),
3: ('Un efecto puede volver como causa', 'La sobreventa puede reforzar el mismo problema que intenta resolver.', 'loop', [
('Presión por ocupación', 'Se busca vender más habitaciones.', 'Aumenta el margen de sobreventa.'),
('Sobreventa', 'Aumenta la exposición a reservas incompatibles.', 'Aparecen más excepciones que resolver.'),
('Reparación manual', 'El equipo dedica tiempo a reubicar y corregir.', 'Queda menos atención para actualizar los estados.'),
('Datos menos oportunos', 'La información llega tarde o queda incompleta.', 'La coordinación pierde una base confiable.'),
('Más incertidumbre', 'Comercial percibe más incertidumbre sobre la ocupación.', 'Esa incertidumbre puede impulsar más sobreventa.')],
'El ciclo vuelve al inicio', 'Incluí en el análisis reglas de canales, proveedores y otras condiciones externas, aunque no las controles.'),
4: ('Una afirmación necesita su historia', 'No es lo mismo observar algo que explicar por qué pasó o decidir qué hacer.', 'flow', [
('Fuente', 'Persona, sensor o documento.', '¿De dónde salió la información?'),
('Registro', 'Captura situada y parcial.', '¿Qué se anotó y en qué condiciones?'),
('Dato', 'Registro codificado según una definición.', '¿Qué significa cada valor?'),
('Interpretación', 'Significado que atribuimos a lo registrado.', '¿Qué lectura hacemos y qué otras son posibles?'),
('Hipótesis', 'Explicación que puede ponerse a prueba.', '¿Qué evidencia podría mostrar que estamos equivocados?'),
('Decisión', 'Acción con una condición de revisión.', '¿Quién decide y cuándo volveremos a evaluar?')],
'En cada paso', 'Conservá procedencia, definiciones, incertidumbre y responsables. Una transformación no debe borrar la anterior.'),
5: ('Participar no es tener el mismo poder', 'Un mapa de actores muestra quién puede actuar y quién carga con las consecuencias.', 'taxonomy', [
('Definir', 'Quién logra instalar un problema.', 'Su versión puede excluir otras experiencias.'),
('Conocer', 'Quién tiene información y experiencia sobre lo que ocurre.', 'Saber no siempre da autoridad para decidir.'),
('Autorizar', 'Quién habilita recursos o excepciones.', 'Cada decisión necesita un responsable.'),
('Ejecutar', 'Quién hace el trabajo y resuelve dificultades.', 'Puede advertir lo que el plan no contempló.'),
('Recibir las consecuencias', 'Quién recibe beneficios, costos o daños.', 'Puede ser alguien que no fue escuchado.'),
('Objetar y reparar', 'Quién puede cuestionar y pedir respuestas.', 'Escuchar exige poder corregir lo que falla.')],
'Contrapesos necesarios', 'Participación, decisiones reconstruibles y vías de objeción y reparación. Cambiar una regla también redistribuye poder.'),
7: ('De una pregunta a una decisión', 'La evidencia sirve cuando cambia lo que podemos afirmar y hacer.', 'flow', [
('Definir la pregunta', '¿Qué decisión necesita evidencia?', 'Una pregunta concreta permite elegir qué observar.'),
('Reunir rastros', 'Episodios, registros, contexto y fuentes independientes.', 'Buscá también un caso que contradiga la explicación.'),
('Comparar', '¿Qué coincide y qué no?', 'Un desacuerdo puede revelar una diferencia importante.'),
('Calibrar', '¿Hasta dónde llega lo encontrado?', 'Una pista no es todavía un patrón ni una causa demostrada.'),
('Sostener una afirmación', 'Explicar qué la apoya y qué la debilita.', 'Conservar dudas y explicaciones rivales.'),
('Decidir y volver a mirar', 'Actuar en proporción a lo que sabemos.', 'Definir qué comprobar después y cuándo revisar la decisión.')],
'No alcanza con acumular datos', 'La próxima observación debe poder cambiar la interpretación o la acción. Si nada puede cambiar, no estamos investigando.'),
8: ('Observar antes de explicar', 'Separar lo que pasó de lo que creemos que significa ayuda a investigar mejor.', 'layers', [
('Contexto y evento', 'Dónde, cuándo y en qué condiciones ocurrió.', 'Registrá la escena antes de atribuir una causa.'),
('Interpretación e incertidumbre', 'Qué explicación proponemos y qué falta saber.', 'La interpretación es una hipótesis, no el hecho observado.'),
('Contraste', 'Otras personas, otros rastros y nuevos episodios.', 'Buscá qué confirma o contradice esa interpretación.'),
('Función y consecuencia', 'Para qué sirve la práctica y qué efectos produce.', 'Algo incómodo puede estar protegiendo una condición necesaria.'),
('Decisión', 'Conservar, cambiar o hacer una prueba.', 'Volvé a observar el resultado de esa decisión.')],
'Pregunta de control', '¿Otra persona puede distinguir en el registro qué vimos y qué estamos suponiendo?'),
9: ('Accesible de principio a fin', 'Una etiqueta en la pantalla no garantiza que la persona pueda completar el recorrido.', 'flow', [
('Propósito y condiciones', 'Confirmar que el alojamiento sea compatible.', 'Considerar movilidad, teclado, conectividad y apoyos.'),
('Señal y acción', 'La pantalla ofrece una habitación adaptada.', 'La persona reserva y recibe una confirmación.'),
('Trabajo que sostiene la oferta', 'Verificar atributos y disponibilidad reales.', 'No alcanza con que la etiqueta esté cargada.'),
('Evidencia', 'Saber de dónde viene el dato y si sigue vigente.', 'Identificar quién puede confirmarlo o corregirlo.'),
('Falla y respuesta', 'Una promesa falsa puede impedir el ingreso.', 'Dar una alternativa verificable, un plazo y un responsable.')],
'La prueba es el recorrido completo', 'Incluí la excepción y la reparación. El servicio no es accesible si sólo funciona cuando todo sale bien.'),
10: ('Antes de aprobar una intervención', 'Nueve campos se controlan entre sí. No son casilleros para completar sin discutir.', 'matrix', [
('Situar el cambio', 'Situación observada · personas afectadas · resultado esperado.', 'Qué pasa, para quién y qué debería cambiar en una ventana definida.'),
('Sostener el argumento', 'Explicaciones rivales · evidencia y vacíos · frontera.', 'Qué podría explicar lo observado, qué lo apoya y qué quedó afuera.'),
('Limitar el compromiso', 'Restricciones y preferencias · protección y reparación · revisión.', 'Qué no debe degradarse y qué hallazgo obliga a volver al encuadre.')],
'Puerta de decisión', '¿La evidencia alcanza para esta acción? Aprobar, devolver, dividir o reformular antes de asumir un costo irreversible.'),
11: ('Un dato no habla por sí solo', 'Para usarlo como evidencia hay que poder reconstruir qué permite afirmar.', 'converge', [
('Afirmación', 'Delimitar qué se sostiene.', 'Sobre qué fenómeno, población y período estamos hablando.'),
('Rastro', 'Conservar cómo se obtuvo y transformó el dato.', 'Fuente, registros, operaciones realizadas y faltantes.'),
('Límite', 'Explicitar hasta dónde sirve.', 'Incertidumbre, condiciones de uso y señales para revisar.')],
'¿Alcanza para esta decisión?', 'Las demoras por canal permiten revisar una integración. No prueban, por sí solas, que todos los terceros sean la causa.'),
12: ('Pedir no es confirmar que ocurrió', 'Comando, evento y estado cumplen funciones diferentes.', 'flow', [
('Estado anterior', 'Qué se considera válido antes de actuar.', 'Debe poder reconocerse sin reconstrucciones informales.'),
('Comando', 'Una solicitud de cambio.', 'Puede quedar pendiente o ser rechazada: todavía no es un hecho.'),
('Condiciones para actuar', 'Autoridad, reglas, evidencia y tiempo.', 'Quién puede habilitar el cambio y con qué respaldo.'),
('Evento', 'Registro de lo que efectivamente ocurrió.', 'Conserva el hecho, no sólo la intención de producirlo.'),
('Estado vigente', 'Qué vale después de la transición.', 'Si hay un error, se repara sin borrar la historia.')],
'Hotel Horizonte', '“Limpieza terminada” no significa “lista para entregar”. También importan inspección, asignación, acceso y autorización.'),
13: ('La misma intención no debe duplicarse', 'Los mensajes pueden repetirse, demorarse o llegar fuera de orden.', 'flow', [
('Reconocer la intención', 'Asignar la última habitación disponible.', 'Un reintento a los ocho segundos no es una segunda reserva.'),
('Proteger la regla', 'Una habitación no puede tener dos asignaciones incompatibles.', 'Identidad estable, versión y autoridad protegen esa condición.'),
('No inventar éxito', 'Si el resultado es ambiguo, hacerlo visible.', 'No sobrescribir silenciosamente ni volver a aplicar el efecto.'),
('Reconciliar', 'Comparar canal de reservas, sistema del hotel y cerradura.', 'Una cancelación tardía exige revisar qué sigue vigente.'),
('Reparar', 'Resolver la discrepancia y conservar su historia.', 'Registrar quién actuó y qué consecuencia tuvo.')],
'Criterio de cierre', 'No alcanza con que cada sistema tenga un registro. Deben poder sostener una misma asignación válida.'),
14: ('Cuatro minutos no cuentan toda la espera', 'El mostrador ve una parte. La familia vive el recorrido completo.', 'timeline', [
('Llegada', 'El reloj empieza cuando comienza la necesidad de ingreso.', 'No cuando un sector decide iniciar su medición.'),
('Esperas y traspasos', 'Inspección, identidad, cerradura y autorizaciones.', 'Hacer visible quién recibe el caso y quién debe responder.'),
('Asignación y acceso', 'Confirmar una habitación y habilitar la llave.', 'Seguir la misma llegada a través de todas las áreas.'),
('Excepción o reparación', 'Una identidad discutida necesita autoridad y una respuesta.', 'El recorrido termina con ingreso efectivo o reparación.')],
'Dos mediciones distintas', 'Cuatro minutos en el mostrador pueden formar parte de una llegada que demora 27 minutos. Mejorar una tarea no asegura mejorar el conjunto.'),
15: ('La pregunta elige el dibujo', 'Cada representación permite ver unas relaciones y deja otras afuera.', 'matrix', [
('¿Dónde esperamos?', 'Vista de proceso.', 'Seguir trabajo, colas y traspasos de responsabilidad.'),
('¿Qué está confirmado?', 'Vista de estados.', 'Distinguir solicitudes, hechos y condiciones vigentes.'),
('¿De qué dependemos?', 'Vista de arquitectura.', 'Mostrar componentes, intercambios y restricciones.'),
('¿Quién puede decidir?', 'Vista de autoridad.', 'Precisar permisos y tratamiento de excepciones.'),
('¿Quién encuentra una barrera?', 'Vista de experiencia.', 'Reconstruir condiciones reales de uso y consecuencias.')],
'Probar la utilidad', 'Usá los mismos identificadores de reserva, habitación y episodio. ¿La audiencia puede decidir con la vista sin que su autor la traduzca?'),
16: ('Dos modelos distintos no siempre se contradicen', 'Primero hay que comparar el mismo episodio.', 'flow', [
('Alinear la comparación', 'Misma reserva, momento y evidencia.', 'Una confirmación recibida y una limpieza terminada no son lo mismo.'),
('Clasificar la diferencia', 'Distinto propósito, error, desfase temporal o tensión abierta.', 'No corregir un modelo sólo porque no se parece al otro.'),
('Asignar un tratamiento', 'Corregir, investigar, decidir o aceptar un riesgo explícito.', 'Cada opción exige una razón diferente.'),
('Cerrar con evidencia', 'Responsable, plazo y efecto comprobable.', 'Actualizar las representaciones que dependían de la diferencia.')],
'La coherencia se prueba', 'En HH-16, proceso, estados, experiencia y tablero hablan del mismo episodio. La comparación debe mostrar qué afirmación hace cada uno.'),
17: ('Cinco lógicas para decisiones distintas', 'Se pueden combinar, pero hay que explicar qué aporta cada una.', 'matrix', [
('Predictiva', 'Planificar compromisos costosos de cambiar.', 'Por ejemplo, contratos, migración y ventanas de intervención.'),
('Iterativa', 'Revisar una solución en versiones sucesivas.', 'Por ejemplo, mejorar una regla compartida sobre estados.'),
('Incremental', 'Ampliar una capacidad que ya funciona completa.', 'Por ejemplo, pasar de dos pisos a una población mayor.'),
('Adaptativa', 'Cambiar la secuencia según las señales.', 'No sostener el plan si la situación que lo justificaba cambió.'),
('Experimental', 'Probar una hipótesis con exposición protegida.', 'Por ejemplo, comprobar una promesa de llegada anticipada.')],
'Antes de ampliar', 'La evidencia debe alcanzar, la reparación debe funcionar y Recepción debe poder detener el uso. Elegí según conocimiento, costo del error y reversibilidad.'),
18: ('Cambiar la pieza sin perder la protección', 'Una práctica heredada puede conservar algo valioso aunque su implementación sea reemplazable.', 'comparison', [
('Llamada antes de reasignar', 'Conservar la protección del compromiso con el huésped.', 'Reemplazar la llamada sólo si otra solución protege lo mismo.'),
('Posible obligación', 'Verificar su fuente y alcance.', 'No tratar una interpretación pendiente como un requisito confirmado.'),
('Autoridad concentrada', 'Hacer explícito quién puede autorizar.', 'Distribuir permisos sin dejar decisiones sin responsable.'),
('Historial y versiones', 'Preservar los hechos y su significado.', 'Migrar sin borrar la posibilidad de reconstruir lo ocurrido.')],
'Prueba de modernización', 'Relacioná fuente, interpretación, diseño y ensayo. Retirá la práctica anterior cuando se haya probado que la protección continúa.'),
19: ('Comparar soluciones completas', 'No comparar sólo precio o tecnología: todas deben pasar la misma prueba.', 'converge', [
('Opciones de realización', 'Configurar · integrar · construir · contratar.', 'También considerar una respuesta manual o no automatizar.'),
('Una misma capacidad', 'Confirmar ingreso accesible con estados compatibles.', 'Una persona debe poder corregir y Recepción debe poder detener.'),
('Una misma prueba adversa', 'Qué ocurre cuando falla, cómo se repara y cómo se sale.', 'La alternativa más atractiva puede ocultar una dependencia costosa.')],
'Probar la salida', 'Exportar reglas y eventos y reconstruirlos en otra solución. Medir pérdida de significado, tiempo y costo antes de aceptar la dependencia.'),
20: ('Una estrategia necesita puertas de decisión', 'Un hito no es sólo una fecha: debe cambiar lo que estamos autorizados a hacer.', 'flow', [
('Comprender', 'Reconstruir episodios, evidencia e hipótesis.', 'No comprometer una solución antes de sostener el encuadre.'),
('Preparar', 'Asegurar personas, permisos y contingencia.', 'Una prueba necesita condiciones para detenerse o reparar.'),
('Probar', 'Observar el caso normal, la falla y la reparación.', 'La demostración favorable no alcanza por sí sola.'),
('Transferir', 'Operaciones puede sostener el uso y detenerlo.', 'El equipo no debe depender del conocimiento privado de quien diseñó.')],
'Si una puerta no abre', 'Investigar, reducir alcance, reparar o retirar. Ampliar no es la única salida posible; debe justificarse con evidencia.'),
21: ('Cuatro responsabilidades, una promesa', 'Proyecto, producto, servicio y plataforma no terminan al mismo tiempo.', 'matrix', [
('Proyecto', 'Organiza una transición temporal.', 'Cierra cuando entrega y transfiere lo comprometido.'),
('Producto', 'Sostiene valor para una población.', 'Decide qué mejorar y dónde seguir invirtiendo.'),
('Servicio', 'Responde por el uso en cada turno.', 'Incluye soporte, continuidad y reparación después del proyecto.'),
('Plataforma', 'Ofrece capacidades compartidas.', 'Gobierna contratos, acceso, evolución y posibilidades de salida.')],
'Prueba conjunta', 'Una entrega técnica puede estar terminada y la promesa seguir fallando: si el turno nocturno no puede reparar, la capacidad aún tiene un límite.'),
22: ('Una prueba debe poder decirnos que no', 'Aprender requiere admitir un resultado que debilite la idea inicial.', 'comparison', [
('Hipótesis principal', 'Verificar tres estados antes de prometer el ingreso.', 'Se espera reducir las reasignaciones.'),
('Explicación rival', 'Quizá la mejora provenga de un mensaje más claro.', 'El cambio de estados podría no ser la causa.'),
('Comparación', 'Misma base y resultados separados por turno, canal y habitación.', 'No mezclar poblaciones con condiciones diferentes.'),
('Protección', 'Una reasignación accesible crítica puede detener la prueba.', 'Una mejora promedio no compensa ese daño.')],
'Decisión del caso', 'Mantener el ingreso directo asistido sin expandir. Elena decide la ampliación; Recepción puede revertir. El alcance sigue a la evidencia.'),
23: ('Un corte pequeño debe funcionar completo', 'Terminar componentes aislados no demuestra que el huésped pueda ingresar.', 'layers', [
('Promesa e información', 'Qué se ofrece y con qué estados vigentes.', 'Una pantalla nueva con información vieja no alcanza.'),
('Decisión y autoridad', 'Quién confirma y quién puede detener.', 'La excepción debe tener una respuesta autorizada.'),
('Acción y reparación', 'Ingreso efectivo, soporte y retorno seguro.', 'La operación no se agrega después de “terminar”.'),
('Aprendizaje', 'Observar capacidad, evidencia y riesgo.', 'Contar tareas terminadas no prueba un resultado útil.')],
'Corte de HH-23', 'Canal directo, un turno y dos pisos, con revisión humana y retorno seguro. Ampliar una dimensión por vez y volver a validar.'),
28: ('El promedio puede esconder el problema', 'Un buen resultado general no autoriza todas las situaciones de uso.', 'matrix', [
('Llegada ordinaria', '194 de 200 ingresos demoran menos de diez minutos: 97%.', 'Permite evaluar ese canal y esa carga, no cualquier población.'),
('Llegada accesible', 'Verificar cada condición prometida antes de ofrecer.', 'Si falta una condición crítica, detener y dar una alternativa.'),
('Falla de identidad', 'Respuesta limitada y autorizada.', 'Llave restringida, doble registro y conciliación sin duplicados.')],
'Evidencia y autorización', 'Contrato, eventos, cerradura y observación física se complementan. Ninguno reemplaza a los demás. Elena asume el riesgo residual explícito.'),
29: ('Volver atrás no siempre repara', 'Una liberación cambia más que el código.', 'branch', [
('Antes de exponer', 'Código, configuración, infraestructura, datos, terceros y operación.', 'Probar el mismo artefacto que después se va a utilizar.'),
('Sin cambios persistidos', 'Volver a la versión anterior: rollback.', 'Verificar que el servicio realmente se recuperó.'),
('Con datos transformados', 'Corregir hacia adelante y reconciliar.', 'Restaurar código puede dejar datos incompatibles.'),
('Con una promesa ya recibida', 'Aislar, comunicar, reparar o compensar.', 'No se puede deshacer lo que el huésped ya vivió.')],
'Límite del piloto', 'Cincuenta transiciones o la primera discrepancia. Ricardo detiene; Lucía comprueba el resultado antes de ampliar.'),
30: ('El tablero está verde. La familia espera.', 'La disponibilidad técnica no cuenta toda la experiencia del servicio.', 'layers', [
('Señal técnica', 'Latencia, reintentos y resultados desconocidos.', 'Indica cómo responden los componentes.'),
('Recorrido', 'Reserva, asignación y llave.', 'Permite seguir una llegada de principio a fin.'),
('Negocio', 'Ingreso, contingencia y compensación.', 'Muestra si se sostiene la promesa del hotel.'),
('Experiencia', 'Espera, accesibilidad y ayuda.', 'Hace visible lo que la persona pudo completar.')],
'De la señal a la acción', 'Medir llave funcional en diez minutos, sin reasignación indebida y con acceso prometido. Alertar, asignar autoridad, contener y aprender; no sólo enviar mensajes.'),
31: ('Primero la tarea. Después la IA.', 'Una capacidad se justifica frente a una alternativa práctica, no por novedad.', 'taxonomy', [
('Validar', 'Reglas explícitas y comprobaciones deterministas.', 'Útil cuando la condición puede definirse con precisión.'),
('Buscar', 'Recuperar una política y su fuente.', 'La respuesta debe permitir comprobar procedencia y vigencia.'),
('Predecir', 'Estimar un resultado con incertidumbre.', 'Evaluar calibración y costo de equivocarse.'),
('Generar', 'Preparar un borrador.', 'Verificar, corregir o abstenerse antes de usarlo.'),
('Actuar', 'Modificar una reserva u otra condición real.', 'Requiere permisos, límites y capacidad de reparación.')],
'Límite del caso', 'El asistente prepara; Recepción y Comercial confirman. Comparar valor, supervisión y reparación con reglas, búsqueda y trabajo humano.'),
32: ('El permiso depende de la tarea', 'Un 91% promedio puede ocultar errores graves en un grupo pequeño.', 'matrix', [
('Consulta general', '96% de desempeño observado y tiempo para revisar.', 'Se admite preparar un borrador con confirmación humana.'),
('Solicitud accesible', 'Fallan cinco de doce casos; dos respuestas son impropias.', 'No autorizar acción autónoma. Escalar con la fuente visible.'),
('Compensación nocturna', 'Falta autoridad disponible para confirmar.', 'Permitir preparación, no ejecución.')],
'Reevaluar al cambiar el contexto', 'Modelo, población, tarea o supervisión nuevos requieren otra prueba. Importa si el equipo puede detectar el error y reparar antes del efecto.'),
33: ('La aprobación tiene condiciones', 'Autorizar un uso una vez no autoriza cualquier versión futura.', 'loop', [
('Registrar el uso', 'Propósito, población, autoridad y riesgos.', 'Nombrar qué se permite y bajo qué límites.'),
('Conservar la configuración', 'Modelo, fuentes, permisos y proveedor.', 'Poder reconstruir con qué versión se tomó una decisión.'),
('Observar cambios e incidentes', 'Una fuente contradictoria o un permiso nuevo cambian el uso.', 'Reevaluar; reducir exposición si la evidencia dejó de valer.'),
('Responder', 'Contener, explicar y reparar.', 'Cambiar la regla y probarla antes de volver a ampliar.'),
('Retirar cuando corresponde', 'Revocar permisos y sostener continuidad.', 'Preservar evidencia legítima y quitar dependencias residuales.')],
'Volver al registro', 'La respuesta al incidente actualiza las condiciones de uso. Una autorización sin seguimiento no equivale a gobierno.'),
35: ('Cambiar el recorrido, no el argumento', 'Cada audiencia necesita una entrada diferente a la misma intervención.', 'converge', [
('Argumento que se conserva', 'Afirmación, evidencia, razón, límite, objeción y revisión.', 'La tesis del caso mantiene un alcance asistido y una salida.'),
('Recorridos por audiencia', 'Dirección: recursos y riesgo. Tecnología: reconstrucción.', 'Operaciones: actuar y reparar. Comercial: promesa sostenible.'),
('Personas afectadas', 'Entender la consecuencia y poder objetarla.', 'Una objeción debe reabrir la afirmación que pone en duda.'),
('Transferencia', 'Explicar el criterio en un caso nuevo.', 'Actuar, detener o reparar sin copiar la solución anterior.')],
'Prueba de comprensión', '¿La otra persona puede justificar qué conservaría y qué cambiaría en otra situación? Repetir una frase no demuestra que pueda intervenir.'),
36: ('Salir bien no siempre significa aprender', 'Una mejora puede depender de trabajo invisible que la explicación inicial no contempló.', 'loop', [
('Resultado esperado', 'La integración debería reducir el trabajo manual.', 'Ese es el mecanismo que se quiere poner a prueba.'),
('Sorpresa', 'Baja la espera, pero Recepción anticipa excepciones en silencio.', 'El buen resultado no demuestra que la integración lo explique sola.'),
('Revisar la práctica', 'Un bucle: ajustar la acción.', 'Dos bucles: revisar también objetivo, reglas y autoridad.'),
('Cambiar algo comprobable', 'Acción, responsable y próximo episodio que puede refutarla.', 'La IA puede proponer preguntas; las personas verifican y deciden.'),
('Comprobar transferencia', 'Otra persona puede sostener el criterio en una situación nueva.', 'El aprendizaje debe aparecer en la práctica, no sólo en el relato.')],
'Volver a poner a prueba', 'El nuevo episodio puede confirmar o cuestionar el cambio. Aprender incluye conservar esa posibilidad abierta.'),
}
